### ISSUE TITLE
java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil. Didn't find class "org.bytedeco.javacpp.avutil" on path: DexPathList

### ISSUE THREAD

**Issue by satyamub** [Bilibili/ijkplayer#1148]
Hi All,

I am finding this weird issue, I am using this library to play the RTMP path. My App also includes the option to stream video as well for that I am using opencv and ffmpeg. I have included the below jar files to my libs folder for the streaming purpose and it was working well, I have added this and its keep telling the error message

ffmpeg-android-arm.jar
ffmpeg-android-x86.jar
ffmpeg.jar
javacpp.jar
javacv.jar
opencv-android-arm.jar
opencv-android-x86.jar
opencv.jar
videoinput.jar

I am thinking that there must be a clash because both using FFMpeg so how can i detect that clash and resolve it?

**Comment by bbcallen** [comment]
Can't tell nothing.
Too few information, and too many possibility

**Comment by satyamub** [comment]
Hi bbcallen I am using https://github.com/bytedeco/javacv this library for live streaming ... when I use them in different projects, there are working well like opencv which has ffnpeg is streaming the video and in another app which has this ijkplayer, I can see that stream, when I am trying to merge them, I found this below logcat

FATAL EXCEPTION: main
    Process: com.satya.recordrtmp, PID: 26565
    java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
            at org.bytedeco.javacpp.Loader.load(Loader.java:415)
            at org.bytedeco.javacpp.Loader.load(Loader.java:381)
            at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650)
            at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
            at com.satya.recordrtmp.MainActivity.initRecorder(MainActivity.java:190)
            at com.satya.recordrtmp.MainActivity.startRecording(MainActivity.java:205)
            at com.satya.recordrtmp.MainActivity.onClick(MainActivity.java:501)
            at android.view.View.performClick(View.java:4633)
            at android.view.View$PerformClick.run(View.java:19270)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5602)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:251)
            at org.bytedeco.javacpp.Loader.load(Loader.java:413)
            at org.bytedeco.javacpp.Loader.load(Loader.java:381)
            at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650)
            at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
            at com.satya.recordrtmp.MainActivity.initRecorder(MainActivity.java:190)
            at com.satya.recordrtmp.MainActivity.startRecording(MainActivity.java:205)
            at com.satya.recordrtmp.MainActivity.onClick(MainActivity.java:501)
            at android.view.View.performClick(View.java:4633)
            at android.view.View$PerformClick.run(View.java:19270)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5602)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NoClassDefFoundError: org/bytedeco/javacpp/avutil
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:251)
            at org.bytedeco.javacpp.Loader.load(Loader.java:413)
            at org.bytedeco.javacpp.Loader.load(Loader.java:381)
            at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650)
            at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
            at com.satya.recordrtmp.MainActivity.initRecorder(MainActivity.java:190)
            at com.satya.recordrtmp.MainActivity.startRecording(MainActivity.java:205)
            at com.satya.recordrtmp.MainActivity.onClick(MainActivity.java:501)
            at android.view.View.performClick(View.java:4633)
            at android.view.View$PerformClick.run(View.java:19270)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5602)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.bytedeco.javacpp.avutil" on path: DexPathList[[zip file "/data/app/com.satya.recordrtmp-4.apk"],nativeLibraryDirectories=[/data/app-lib/com.satya.recordrtmp-4, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:251)
            at org.bytedeco.javacpp.Loader.load(Loader.java:413)
            at org.bytedeco.javacpp.Loader.load(Loader.java:381)
            at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650)
            at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
            at com.satya.recordrtmp.MainActivity.initRecorder(MainActivity.java:190)
            at com.satya.recordrtmp.MainActivity.startRecording(MainActivity.java:205)
            at com.satya.recordrtmp.MainActivity.onClick(MainActivity.java:501)
            at android.view.View.performClick(View.java:4633)
            at android.view.View$PerformClick.run(View.java:19270)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5602)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by satyamub** [comment]
can we exclude libavutil from ijkplyaer in build time?

**Comment by bbcallen** [comment]
Sorry, the javacpp bridge seems too complicated to me.

No, libavutil is depended by all other FFmpeg modules.

**Comment by satyamub** [comment]
we commented out the     compile 'tv.danmaku.ijk.media:ijkplayer-java:0.4.5.1' from grade and it seems to be working now!!!
