### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/tv.danmaku.ijk.media.sample-2/lib/x86/libijkffmpeg.so: has text relocations

### ISSUE THREAD

**Issue by xeon2007** [Bilibili/ijkplayer#1171]
04-14 11:33:37.845 9153-9153/tv.danmaku.ijk.media.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: tv.danmaku.ijk.media.sample, PID: 9153
                                                                           java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/tv.danmaku.ijk.media.sample-2/lib/x86/libijkffmpeg.so: has text relocations
                                                                               at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                               at java.lang.System.loadLibrary(System.java:1076)
                                                                               at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
                                                                               at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:168)
                                                                               at tv.danmaku.ijk.media.sample.activities.VideoActivity.onCreate(VideoActivity.java:136)
                                                                               at android.app.Activity.performCreate(Activity.java:6237)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by bbcallen** [comment]
https://trac.ffmpeg.org/ticket/4928
This is an FFmpeg issue.

**Comment by xeon2007** [comment]
but my virtual machine is x86-64,not the x86.  is there any way run the sample on x86-64 vm?

**Comment by bbcallen** [comment]
build x86_64 so files.

**Comment by xeon2007** [comment]
thx,i added   all32Compile project(':ijkplayer-x86_64') with modifying minSdkVersion to 9,the sample builds successfully,it runs like a charm on x86_64!
