### ISSUE TITLE
下载demo运行出错==》java.lang.UnsatisfiedLinkError: Couldn't load ijkffmpeg from loader dalvik.system.PathClassLoader

### ISSUE THREAD

**Issue by zhouclcode** [Bilibili/ijkplayer#1237]
Process: tv.danmaku.ijk.media.sample, PID: 2173
                                                 java.lang.UnsatisfiedLinkError: Couldn't load ijkffmpeg from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.sample-1.apk"],nativeLibraryDirectories=[/data/app-lib/tv.danmaku.ijk.media.sample-1, /system/lib]]]: findLibrary returned null
                                                     at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                     at java.lang.System.loadLibrary(System.java:526)
                                                     at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
                                                     at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:168)
                                                     at tv.danmaku.ijk.media.sample.activities.VideoActivity.onCreate(VideoActivity.java:136)
                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by bbcallen** [comment]
Read README first.

**Comment by ChadCSong** [comment]
Chose ABIs you needed.
