### ISSUE TITLE
android unsatisfiedlinkerror

### ISSUE THREAD

**Issue by zhousuqiang** [Bilibili/ijkplayer#1278]
我把so库文件放到自己项目lib目录下，然后进行System.loadLibrary()时报出错unsatisfiedlinkerror，请问是因为so文件在编译时，已经固定了包名的原因吗？

**Comment by bbcallen** [comment]
No

**Comment by zhousuqiang** [comment]
那请问您知道是什么原因导致的吗？

**Comment by bbcallen** [comment]
I don't know.

**Comment by zhousuqiang** [comment]
谁遇到过，请帮忙看看，谢谢大家了，错误log如下：
java.lang.UnsatisfiedLinkError: Couldn't load ijkffmpeg from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.huan.edu.tvplayer.example2-1.apk,libraryPath=/data/app-lib/com.huan.edu.tvplayer.example2-1]: findLibrary returned null
                                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                                                    at java.lang.System.loadLibrary(System.java:535)
                                                                                    at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)

**Comment by Android4MediaPlayer** [comment]
没有找到库

**Comment by zhousuqiang** [comment]
我把armeabi和armeabi-v7a目录(包括里面的so)放到项目libs目录下的，按理说不应该找不到呀

**Comment by Android4MediaPlayer** [comment]
请详细描述下 不然没法帮你看问题

**Comment by zhousuqiang** [comment]
解决了，谢谢各位的热心支持，原因是因为我做了个library项目放到libs下了，然后其它项目再引用这个library项目然后打包不知道为什么不会把libs目录下的so打包进入，我把so放到jinLibs目录下再打包就可以加载so了。
