### ISSUE TITLE
MI 2s手机上UnsatisfiedLinkError

### ISSUE THREAD

**Issue by lyqaiym** [Bilibili/ijkplayer#1290]
abi是armeabi-v7a,armeabi
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libxesffmpeg.so" (built with --hash-style=gnu?)
	at java.lang.Runtime.loadLibrary(Runtime.java:371)
	at java.lang.System.loadLibrary(System.java:989)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:168)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:209)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:205)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:196)
	at com.xueersi.parentsmeeting.modules.coursevideo.videoplayer.media.MIJKMediaPlayer.<init>(MIJKMediaPlayer.java:19)

**Comment by bbcallen** [comment]
Seems you have modified the build script?
