### ISSUE TITLE
genymotion 6.0 emulator crash

### ISSUE THREAD

**Issue by dalu9527** [Bilibili/ijkplayer#1305]
E/art: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:862)
                                                                at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                                at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                                at java.lang.Thread.run(Thread.java:818)

**Comment by bbcallen** [comment]
Sorry, I don't maintain support for emulator
