### ISSUE TITLE
这个错误一般是什么原因呢

### ISSUE THREAD

**Issue by HelloDearWorld** [Bilibili/ijkplayer#1510]
06-21 15:11:30.299 com.lingxicollege A/MobUncaughtExceptionHandler: JNI_ERR returned from JNI_OnLoad in "/data/app/com.lingxicollege-1/lib/arm/libijksdl.so"
                                                                    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.lingxicollege-1/lib/arm/libijksdl.so"
                                                                        at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                                        at java.lang.System.loadLibrary(System.java:988)
                                                                        at tv.danmaku.ijk.lxmedia.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:154)
                                                                        at tv.danmaku.ijk.lxmedia.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:166)
                                                                        at tv.danmaku.ijk.lxmedia.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:206)
                                                                        at tv.danmaku.ijk.lxmedia.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:202)
                                                                        at tv.danmaku.ijk.lxmedia.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:193)

**Comment by bbcallen** [comment]
You didn't build native library successfully.

**Comment by pollyfat** [comment]
try to add 

-keep class tv.danmaku.ijk.media.player.** { *; }
-keep class tv.danmaku.ijk.media.player.IjkMediaPlayer.**{*; }
-keep class tv.danmaku.ijk.media.player.ffmpeg.FFmpegApi.**{*; }
-keep class <YOUR PACKAGE NAME>.ijkplayer.** { *; }

to your proguard file,<YOUR PACKAGE NAME> depends on your ijkplayer package location.It works for me.

**Comment by gongtingshisi** [comment]
why the fix can resolve the problem,from #2490 ? I mean, code confusion when compiling  will cause link lib error on runtime? @pollyfat

**Comment by fukemy** [comment]
not working to me
