### ISSUE TITLE
Ubuntu编译出来的android版的ijkplayer少了libijksdl.so和libijkutil.so怎么办?

### ISSUE THREAD

**Issue by 15301089517** [Bilibili/ijkplayer#1537]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.example-1/base.apk"],nativeLibraryDirectories=[/data/app/tv.danmaku.ijk.media.example-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libijksdl.so"
                                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                                  at java.lang.System.loadLibrary(System.java:989)
                                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
                                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:169)
                                                                                  at tv.danmaku.ijk.media.example.activities.VideoActivity.onCreate(VideoActivity.java:136)
                                                                                  at android.app.Activity.performCreate(Activity.java:5976)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441)
                                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
06-25 00:00:23.453 22752-22752/tv.danmaku.ijk.media.example I/Process: Sending signal. PID: 22752 SIG: 9

**Comment by bbcallen** [comment]
Then build them.
