### ISSUE TITLE
有个错误null指针 

### ISSUE THREAD

**Issue by qixing0918** [Bilibili/ijkplayer#1575]
### 07-04 15:14:48.886 12315-12315/com.hotbitmapgg.ohmybilibili E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.hotbitmapgg.ohmybilibili, PID: 12315
                                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setVisibility(int)' on a null object reference
                                                                                  at com.hotbitmapgg.ohmybilibili.activity.BiliBiliLivePlayerActivity.stopAnim(BiliBiliLivePlayerActivity.java:170)
                                                                                  at com.hotbitmapgg.ohmybilibili.activity.BiliBiliLivePlayerActivity.access$000(BiliBiliLivePlayerActivity.java:39)
                                                                                  at com.hotbitmapgg.ohmybilibili.activity.BiliBiliLivePlayerActivity$1.handleMessage(BiliBiliLivePlayerActivity.java:112)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:147)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5456)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:970)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:765)

**Comment by bbcallen** [comment]
It has nothing to do with ijkplayer.
