### ISSUE TITLE
When I call IjkMediaPlayer.loadLibrariesOnce(null),crashed with the log in comment

### ISSUE THREAD

**Issue by kingty** [bilibili/ijkplayer#1656]
what i do is below:
        compile 'tv.danmaku.ijk.media:ijkplayer-java:0.6.0'
        compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.6.0'

```
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.p1.mobile.putong-1/lib/arm/libijksdl.so"
                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                          at java.lang.System.loadLibrary(System.java:1076)
                                                                          at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
                                                                          at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:169)
                                                                          at v.VTexturePlayer.onSurfaceTextureAvailable(VTexturePlayer.java:94)
                                                                          at android.view.TextureView.getHardwareLayer(TextureView.java:368)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16441)
                                                                          at android.view.View.draw(View.java:17238)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16459)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16424)
                                                                          at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
                                                                          at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
                                                                          at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
                                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:3134)
                                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2933)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2522)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:158)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by kingty** [comment]
@bbcallen 
called in this method to init the mediaplayer

```
@Override
	public void onSurfaceTextureAvailable(SurfaceTexture surface, int width, int height) {
		Log.d(TAG, "surface ok now!!! " + width + " " + height);
		this.surface = new Surface(surface);

		IjkMediaPlayer.loadLibrariesOnce(null);
		IjkMediaPlayer.native_profileBegin("libijkplayer.so");

		player = new IjkMediaPlayer();
		player.setSurface(this.surface);
		if (playWhenSurfaceReady) {
			adjustAspectRatio(width, height, aspectRatio);
			Log.d(TAG, "someone waiting for the surface! play now");
			playInner();
		} else if (resetIfAvailable && listener != null) {
			completed = false;
			firstCallOfPlay = true;
			player.reset();
			listener.onStop();
		}
	}
```

**Comment by bbcallen** [comment]
Demo depends on local project, not jcenter.
Do you have any other native library in your project?

**Comment by kingty** [comment]
@bbcallen yes,I have another ffmpeg binary and many others native libs in my project which not remove yet,because I have not  integrate all the functions in your build binary.
So, is that cause this problem?

**Comment by bbcallen** [comment]
What do your lib directory looks like?

**Comment by bbcallen** [comment]
How many files are placed in your lib directory?

**Comment by kingty** [comment]
src/main/jniLibs/armeabi-v7a/....so

![image](https://cloud.githubusercontent.com/assets/3754040/16938806/3a339532-4dae-11e6-9b1f-77a647c03061.png)

**Comment by bbcallen** [comment]
It seems that you have x86 so, too.
Make sure every abi directory contains all so files or empty at all.

**Comment by kingty** [comment]
When I delete the x86 folder,it occurs too.
```
07-20 13:43:47.011 6606-6606/com.p1.mobile.putong W/System.err: java.lang.NoSuchMethodError: no non-static method "Ltv/danmaku/ijk/media/player/misc/IMediaDataSource;.readAt(J[BII)I"
07-20 13:43:47.011 6606-6606/com.p1.mobile.putong W/System.err:     at java.lang.Runtime.nativeLoad(Native Method)
07-20 13:43:47.011 6606-6606/com.p1.mobile.putong W/System.err:     at java.lang.Runtime.doLoad(Runtime.java:435)
07-20 13:43
```

`java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.p1.mobile.putong-1/lib/arm/libijksdl.so"`

**Comment by bbcallen** [comment]
Can't reproduce here.
No idea, at all.

**Comment by cassydius** [comment]
I had the same problem. I found the solution in another ticket. I added those lines to proguard rules and it worked:

**Comment by fukemy** [comment]
@cedrtang not working when run in simulator

**Comment by yudesong** [comment]
-keep class tv.danmaku.ijk.media.player.* {; }
-keep class tv.danmaku.ijk.media.player.IjkMediaPlayer{; }
-keep class tv.danmaku.ijk.media.player.ffmpeg.FFmpegApi{; }

**Comment by twlkyao** [comment]
> -keep class tv.danmaku.ijk.media.player.* {; }
> -keep class tv.danmaku.ijk.media.player.IjkMediaPlayer{; }
> -keep class tv.danmaku.ijk.media.player.ffmpeg.FFmpegApi{; }

I encounted this in debug mode, any idea?
