### ISSUE TITLE
v0.6 is config compile

### ISSUE THREAD

**Issue by a137235** [Bilibili/ijkplayer#1663]
将 ffmpeg3.1重新编译好了后替换掉libijkffmpeg.so，会直接崩溃掉
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "ijkav_get_inject_callback" referenced by "/data/app/xin.yufeng.multimedia.app.music-1/lib/arm/libijkplayer.so"...
                                                                                     at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                                     at java.lang.System.loadLibrary(System.java:1076)
                                                                                     at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
                                                                                     at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:170)
                                                                                     at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:209)
                                                                                     at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:205)
                                                                                     at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:196)

**Comment by a137235** [comment]
然后我想重新编译ijkmedia也出现
[armeabi] SharedLibrary  : libijksdl.so
ijksdl/ffmpeg/ijksdl_vout_overlay_ffmpeg.c:165: error: undefined reference to 'av_frame_unref'
ijksdl/ffmpeg/ijksdl_vout_overlay_ffmpeg.c:97: error: undefined reference to 'av_image_get_buffer_size'
ijksdl/ffmpeg/ijksdl_vout_overlay_ffmpeg.c:98: error: undefined reference to 'av_buffer_alloc'
ijksdl/ffmpeg/ijksdl_vout_overlay_ffmpeg.c:102: error: undefined reference to 'av_image_fill_arrays'
ijksdl/ffmpeg/ijksdl_vout_overlay_ffmpeg.c:213: error: undefined reference to 'av_frame_ref'
ijksdl/ffmpeg/ijksdl_vout_overlay_ffmpeg.c:257: error: undefined reference to 'sws_getCachedContext'
ijksdl/ffmpeg/ijksdl_vout_overlay_ffmpeg.c:265: error: undefined reference to 'sws_scale'
ijksdl/ffmpeg/ijksdl_vout_overlay_ffmpeg.c:270: error: undefined reference to 'av_get_pix_fmt_name'
ijksdl/ffmpeg/ijksdl_vout_overlay_ffmpeg.c:270: error: undefined reference to 'av_get_pix_fmt_name'
ijksdl/ffmpeg/ijksdl_vout_overlay_ffmpeg.c:118: error: undefined reference to 'sws_freeContext'

**Comment by bbcallen** [comment]
There is some modification in libijkffmpeg. You can't replace it with other ffmpeg build directly.

**Comment by a137235** [comment]
那我应该怎么操作？在V0.51的时候都可以直接替换，现在编译libijksdl也出现问题，求帮助。

**Comment by bbcallen** [comment]
Check if you have built ffmpeg successfully.

**Comment by a137235** [comment]
Thank you for your time,I build successfully.must linux build

**Comment by agaochen** [comment]
请问你解决了这个问题吗？我也有同样的问题。怎么解决了的，我是想用自己编译的ffmpeg库替换ijkffmpeg.so。我的邮箱：czg2003@163.com

**Comment by xinzhengzhang** [comment]
Both change your ffmpeg and ijk lib at same time
