### ISSUE TITLE
Error,when use.

### ISSUE THREAD

**Issue by var1993** [Bilibili/ijkplayer#1718]
Log:
java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                                 at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                                 at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:862)
                                                                 at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                                 at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                                 at java.lang.Thread.run(Thread.java:818)

gradle 远程依赖

compile 'tv.danmaku.ijk.media:ijkplayer-java:0.6.0'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.5.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.5.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.5.1'
    compile 'com.android.support:appcompat-v7:23.1.1'

**Comment by var1993** [comment]
我把android studio 的即时编译关闭之后，报错信息变了，如下：
                                                                     java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.fxtv.threebears-1/base.apk"],nativeLibraryDirectories=[/data/app/com.fxtv.threebears-1/lib/arm64, /data/app/com.fxtv.threebears-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"

**Comment by bbcallen** [comment]
compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.6.0'

**Comment by var1993** [comment]
uses-sdk:minSdkVersion 14 cannot be smaller than version 21 declared in library [tv.danmaku.ijk.media:ijkplayer-arm64:0.6.0] /Users/var/work/android/project/fxtv/source/v270/fxtv_phone/fxtv/build/intermediates/exploded-aar/tv.danmaku.ijk.media/ijkplayer-arm64/0.6.0/AndroidManifest.xml

**Comment by bbcallen** [comment]
#1308

**Comment by pollyfat** [comment]
除了添加依赖没其他办法解决吗？添加依赖后小于21的都没办法使用了。

**Comment by lijun952048910** [comment]
08-29 19:07:12.338 25895-25910/com.wangzhi.MaMaHelp E/art: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
08-29 19:07:12.338 25895-25910/com.wangzhi.MaMaHelp E/System: Uncaught exception thrown by finalizer
08-29 19:07:12.338 25895-25910/com.wangzhi.MaMaHelp E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:955)
                                                                  at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:223)
                                                                  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:206)
                                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by chnouman** [comment]
facing same issue.

**Comment by agarwalmanu20** [comment]
any solution to this?
