### ISSUE TITLE
TextureRenderView onDetachedFromWindow error

### ISSUE THREAD

**Issue by shidongdi** [Bilibili/ijkplayer#1727]
列表里面视频播放出现error后，滑动列表出现以下错误：
java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
at android.graphics.SurfaceTexture.detachFromGLContext(SurfaceTexture.java:195)
at android.view.TextureView.destroySurface(TextureView.java:232)
at android.view.TextureView.access$000(TextureView.java:105)
at android.view.TextureView$1.run(TextureView.java:220)
at android.view.HardwareRenderer$Gl20Renderer.safelyRun(HardwareRenderer.java:2291)
at android.view.View.executeHardwareAction(View.java:12501)
at android.view.TextureView.onDetachedFromWindow(TextureView.java:217)
at com.videoplayer.widget.media.TextureRenderView.onDetachedFromWindow(TextureRenderView.java:87)
at android.view.View.dispatchDetachedFromWindow(View.java:12642)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2587)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2587)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2587)
at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4047)
at android.view.ViewGroup.removeAllViews(ViewGroup.java:3991)	
另外，OnErrorListener触发后不能通过reset重置播放器来重新播放么？

**Comment by bbcallen** [comment]
Please provide detailed reproduce steps.

**Comment by shidongdi** [comment]
recycleview里面添加以下监听，在滑动的时候添加或移除ijkplayer的容器View.
new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {
               //todo add ijkplayer view
                }
            }
            @Override
            public void onChildViewDetachedFromWindow(View view) {
                //todo remove ijkplayer view
                }
            }
 }
以上error发生在onChildViewDetachedFromWindow里.

**Comment by yxh1065494705yxh** [comment]
楼主解决了吗？我也遇到这个问题

**Comment by lgengsy** [comment]
楼主解决了吗？我也遇到这个问题
