### ISSUE TITLE
Error with library

### ISSUE THREAD

**Issue by breakdom** [Bilibili/ijkplayer#197]
Hello I have done all the steps as a guide but I received this error, I'm working on Mac OSX and Android Studio.

03-24 21:20:54.645  18480-18480/tv.danmaku.ijk.media.demo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: tv.danmaku.ijk.media.demo, PID: 18480
    java.lang.UnsatisfiedLinkError: Couldn't load ijkffmpeg from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.demo-13.apk"],nativeLibraryDirectories=[/data/app-lib/tv.danmaku.ijk.media.demo-13, /vendor/lib, /system/lib]]]: findLibrary returned null
            at java.lang.Runtime.loadLibrary(Runtime.java:358)
            at java.lang.System.loadLibrary(System.java:526)
            at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:98)
            at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:106)
            at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:147)
            at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:143)
            at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:135)
            at tv.danmaku.ijk.media.widget.VideoView.openVideo(VideoView.java:249)
            at tv.danmaku.ijk.media.widget.VideoView.access$2300(VideoView.java:61)
            at tv.danmaku.ijk.media.widget.VideoView$8.surfaceCreated(VideoView.java:513)
            at android.view.SurfaceView.updateWindow(SurfaceView.java:601)
            at android.view.SurfaceView.access$000(SurfaceView.java:94)
            at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:184)
            at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:895)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2263)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1297)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6773)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
            at android.view.Choreographer.doCallbacks(Choreographer.java:613)
            at android.view.Choreographer.doFrame(Choreographer.java:583)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5748)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)

How can I fix? I added the path to the file in the NDK local.properties
Thanks.

**Comment by yrom** [comment]
Could you post the build log retrieved from *Gradle Console* or *Terminal*?

**Comment by breakdom** [comment]
how and where I can view the log because if I rebuild project in the log shows nothing

**Comment by yrom** [comment]
In Android Studio, View -> Tool Windows -> Gradle Console

**Comment by ctiao** [comment]
you can run gradlew with --info
```
./gradlew --info
```

**Comment by brystel** [comment]
You can try modify build.gradle file from ijkmediaplayer project.

Try with sourceSets: 
```
 sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            jni.srcDirs = []
            jniLibs.srcDir 'libs'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }
```

**Comment by breakdom** [comment]
./gradlew --info
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
ideaGroovyConsole.groovy: 1: unexpected token: . @ line 1, column 1.
   ./gradlew --info
   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:149)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:119)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:131)
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:359)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:142)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:108)
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:236)
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:162)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:912)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:574)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:550)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:527)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:279)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:258)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:613)
	at groovy.lang.GroovyShell.run(GroovyShell.java:480)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:231)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:64)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at console.run(console.txt:25)
	at groovy.ui.GroovyMain.processReader(GroovyMain.java:563)
	at groovy.ui.GroovyMain.processFiles(GroovyMain.java:473)
	at groovy.ui.GroovyMain.run(GroovyMain.java:373)
	at groovy.ui.GroovyMain.process(GroovyMain.java:361)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:120)
	at groovy.ui.GroovyMain.main(GroovyMain.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:106)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:121)

**Comment by breakdom** [comment]
Gradle output:

Executing tasks: [clean, :ijkmediademo:compileDebugSources, :ijkmediaplayer:compileDebugSources, :ijkmediawidget:compileDebugSources]

Configuration on demand is an incubating feature.
:ijkmediademo:clean
:ijkmediaplayer:clean
:ijkmediawidget:clean
:ijkmediademo:preBuild
:ijkmediademo:preDebugBuild
:ijkmediademo:checkDebugManifest
:ijkmediademo:preReleaseBuild
:ijkmediaplayer:compileLint
:ijkmediaplayer:copyReleaseLint UP-TO-DATE
:ijkmediaplayer:mergeReleaseProguardFiles UP-TO-DATE
:ijkmediaplayer:preBuild
:ijkmediaplayer:preReleaseBuild
:ijkmediaplayer:checkReleaseManifest
:ijkmediaplayer:prepareReleaseDependencies
:ijkmediaplayer:compileReleaseAidl
:ijkmediaplayer:compileReleaseRenderscript
:ijkmediaplayer:generateReleaseBuildConfig
:ijkmediaplayer:generateReleaseAssets UP-TO-DATE
:ijkmediaplayer:mergeReleaseAssets
:ijkmediaplayer:generateReleaseResValues UP-TO-DATE
:ijkmediaplayer:generateReleaseResources
:ijkmediaplayer:packageReleaseResources
:ijkmediaplayer:processReleaseManifest
:ijkmediaplayer:processReleaseResources
:ijkmediaplayer:generateReleaseSources
:ijkmediaplayer:compileReleaseJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:ijkmediaplayer:processReleaseJavaRes UP-TO-DATE
:ijkmediaplayer:packageReleaseJar
:ijkmediaplayer:compileReleaseNdk
:ijkmediaplayer:packageReleaseJniLibs UP-TO-DATE
:ijkmediaplayer:packageReleaseLocalJar UP-TO-DATE
:ijkmediaplayer:packageReleaseRenderscript UP-TO-DATE
:ijkmediaplayer:bundleRelease
:ijkmediawidget:compileLint
:ijkmediawidget:copyReleaseLint UP-TO-DATE
:ijkmediawidget:mergeReleaseProguardFiles UP-TO-DATE
:ijkmediawidget:preBuild
:ijkmediawidget:preReleaseBuild
:ijkmediawidget:checkReleaseManifest
:ijkmediawidget:preDebugBuild
:ijkmediawidget:preDebugTestBuild
:ijkmediawidget:prepareAndroidIjkmediaplayerUnspecifiedLibrary
:ijkmediawidget:prepareReleaseDependencies
:ijkmediawidget:compileReleaseAidl
:ijkmediawidget:compileReleaseRenderscript
:ijkmediawidget:generateReleaseBuildConfig
:ijkmediawidget:generateReleaseAssets UP-TO-DATE
:ijkmediawidget:mergeReleaseAssets
:ijkmediawidget:generateReleaseResValues UP-TO-DATE
:ijkmediawidget:generateReleaseResources
:ijkmediawidget:mergeReleaseResources
:ijkmediawidget:processReleaseManifest
:ijkmediawidget:processReleaseResources
:ijkmediawidget:generateReleaseSources
:ijkmediawidget:compileReleaseJava
:ijkmediawidget:processReleaseJavaRes UP-TO-DATE
:ijkmediawidget:packageReleaseJar
:ijkmediawidget:compileReleaseNdk
:ijkmediawidget:packageReleaseJniLibs UP-TO-DATE
:ijkmediawidget:packageReleaseLocalJar UP-TO-DATE
:ijkmediawidget:packageReleaseRenderscript UP-TO-DATE
:ijkmediawidget:packageReleaseResources
:ijkmediawidget:bundleRelease
:ijkmediademo:prepareAndroidIjkmediaplayerUnspecifiedLibrary
:ijkmediademo:prepareAndroidIjkmediawidgetUnspecifiedLibrary
:ijkmediademo:prepareDebugDependencies
:ijkmediademo:compileDebugAidl
:ijkmediademo:compileDebugRenderscript
:ijkmediademo:generateDebugBuildConfig
:ijkmediademo:generateDebugAssets UP-TO-DATE
:ijkmediademo:mergeDebugAssets
:ijkmediademo:generateDebugResValues UP-TO-DATE
:ijkmediademo:generateDebugResources
:ijkmediademo:mergeDebugResources
:ijkmediademo:processDebugManifest
:ijkmediademo:processDebugResources
:ijkmediademo:generateDebugSources
:ijkmediademo:compileDebugJava
:ijkmediademo:compileDebugNdk
:ijkmediademo:compileDebugSources
:ijkmediaplayer:preDebugBuild
:ijkmediaplayer:checkDebugManifest
:ijkmediaplayer:prepareDebugDependencies
:ijkmediaplayer:compileDebugAidl
:ijkmediaplayer:compileDebugRenderscript
:ijkmediaplayer:generateDebugBuildConfig
:ijkmediaplayer:generateDebugAssets UP-TO-DATE
:ijkmediaplayer:mergeDebugAssets
:ijkmediaplayer:generateDebugResValues UP-TO-DATE
:ijkmediaplayer:generateDebugResources
:ijkmediaplayer:packageDebugResources
:ijkmediaplayer:processDebugManifest
:ijkmediaplayer:processDebugResources
:ijkmediaplayer:generateDebugSources
:ijkmediaplayer:compileDebugJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:ijkmediaplayer:compileDebugNdk
:ijkmediaplayer:compileDebugSources
:ijkmediawidget:checkDebugManifest
:ijkmediawidget:prepareDebugDependencies
:ijkmediawidget:compileDebugAidl
:ijkmediawidget:compileDebugRenderscript
:ijkmediawidget:generateDebugBuildConfig
:ijkmediawidget:generateDebugAssets UP-TO-DATE
:ijkmediawidget:mergeDebugAssets
:ijkmediawidget:generateDebugResValues UP-TO-DATE
:ijkmediawidget:generateDebugResources
:ijkmediawidget:mergeDebugResources
:ijkmediawidget:processDebugManifest
:ijkmediawidget:processDebugResources
:ijkmediawidget:generateDebugSources
:ijkmediawidget:compileDebugJava
:ijkmediawidget:compileDebugNdk
:ijkmediawidget:compileDebugSources

BUILD SUCCESSFUL

Total time: 6.53 secs

**Comment by yrom** [comment]
it seems you were building the stable version, you have to build manually

**Comment by breakdom** [comment]
What do you advise me to do?

**Comment by yrom** [comment]
:smile:  
```git checkout master
./init-android.sh
cd android
./gradlew assembleDebug
```

**Comment by breakdom** [comment]
ok I try and place the result

**Comment by breakdom** [comment]
FAILURE: Build failed with an exception.

* Where:
Script '/Users/breakdom/Desktop/ijkplayer-android/android/gradle/compile-ijkplayer.gradle' line: 25

* What went wrong:
A problem occurred configuring project ':ijkmediademo'.
> A problem occurred configuring project ':ijkmediawidget'.
   > A problem occurred configuring project ':ijkmediaplayer'.
      > Neither path nor baseDir may be null or empty string. path='null' basedir='/Users/breakdom/Desktop/ijkplayer-android/android/ijkmediaplayer'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by breakdom** [comment]
this with --stacktrace option

FAILURE: Build failed with an exception.

* Where:
Script '/Users/breakdom/Desktop/ijkplayer-android/android/gradle/compile-ijkplayer.gradle' line: 25

* What went wrong:
A problem occurred configuring project ':ijkmediademo'.
> A problem occurred configuring project ':ijkmediawidget'.
   > A problem occurred configuring project ':ijkmediaplayer'.
      > Neither path nor baseDir may be null or empty string. path='null' basedir='/Users/breakdom/Desktop/ijkplayer-android/android/ijkmediaplayer'

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':ijkmediademo'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:91)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:86)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:65)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':ijkmediawidget'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:91)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:86)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:65)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
	at org.gradle.api.internal.project.AbstractProject.evaluationDependsOn(AbstractProject.java:562)
	at org.gradle.api.internal.project.AbstractProject.evaluationDependsOn(AbstractProject.java:554)
	at com.android.build.gradle.internal.DependencyManager$_ensureConfigured_closure10.doCall(DependencyManager.groovy:564)
	at com.android.build.gradle.internal.DependencyManager$_ensureConfigured_closure10.call(DependencyManager.groovy)
	at com.android.build.gradle.internal.DependencyManager.ensureConfigured(DependencyManager.groovy:563)
	at com.android.build.gradle.internal.DependencyManager.resolveDependencyForConfig(DependencyManager.groovy:213)
	at com.android.build.gradle.internal.DependencyManager.resolveDependencies(DependencyManager.groovy:128)
	at com.android.build.gradle.internal.TaskManager.resolveDependencies(TaskManager.groovy:249)
	at com.android.build.gradle.internal.VariantManager.createVariantData(VariantManager.java:500)
	at com.android.build.gradle.internal.VariantManager.createVariantDataForProductFlavors(VariantManager.java:585)
	at com.android.build.gradle.internal.VariantManager.populateVariantDataList(VariantManager.java:364)
	at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:231)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.groovy:431)
	at com.android.build.gradle.BasePlugin$_createTasks_closure9.doCall(BasePlugin.groovy:373)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy13.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
	... 31 more
Caused by: org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':ijkmediaplayer'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:91)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:86)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:65)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
	at org.gradle.api.internal.project.AbstractProject.evaluationDependsOn(AbstractProject.java:562)
	at org.gradle.api.internal.project.AbstractProject.evaluationDependsOn(AbstractProject.java:554)
	at com.android.build.gradle.internal.DependencyManager$_ensureConfigured_closure10.doCall(DependencyManager.groovy:564)
	at com.android.build.gradle.internal.DependencyManager$_ensureConfigured_closure10.call(DependencyManager.groovy)
	at com.android.build.gradle.internal.DependencyManager.ensureConfigured(DependencyManager.groovy:563)
	at com.android.build.gradle.internal.DependencyManager.resolveDependencyForConfig(DependencyManager.groovy:213)
	at com.android.build.gradle.internal.DependencyManager.resolveDependencies(DependencyManager.groovy:128)
	at com.android.build.gradle.internal.TaskManager.resolveDependencies(TaskManager.groovy:249)
	at com.android.build.gradle.internal.VariantManager.createVariantData(VariantManager.java:500)
	at com.android.build.gradle.internal.VariantManager.createVariantDataForProductFlavors(VariantManager.java:585)
	at com.android.build.gradle.internal.VariantManager.populateVariantDataList(VariantManager.java:364)
	at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:231)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.groovy:431)
	at com.android.build.gradle.BasePlugin$_createTasks_closure9.doCall(BasePlugin.groovy:373)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy13.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
	... 54 more
Caused by: java.lang.IllegalArgumentException: Neither path nor baseDir may be null or empty string. path='null' basedir='/Users/breakdom/Desktop/ijkplayer-android/android/ijkmediaplayer'
	at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:65)
	at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:77)
	at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:60)
	at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:69)
	at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:620)
	at org.gradle.groovy.scripts.DefaultScript.file(DefaultScript.java:113)
	at org.gradle.api.Script$file$1.callCurrent(Unknown Source)
	at compile_ijkplayer_5ohai2eqx1cundk1wz4wghzt7.getAndroidNdkDir(/Users/breakdom/Desktop/ijkplayer-android/android/gradle/compile-ijkplayer.gradle:25)
	at compile_ijkplayer_5ohai2eqx1cundk1wz4wghzt7$_run_closure1.doCall(/Users/breakdom/Desktop/ijkplayer-android/android/gradle/compile-ijkplayer.gradle:36)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy13.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
	... 77 more


BUILD FAILED

Total time: 6.781 secs

**Comment by bbcallen** [comment]
Now, there is a whole new gradle build script
