### ISSUE TITLE
用EXOPlayer是报这个错 在全屏时

### ISSUE THREAD

**Issue by jianwenzhao** [Bilibili/ijkplayer#2003]
E/ExoPlayerImplInternal: Stop failed.
                                                                             java.lang.IllegalStateException
                                                                                 at android.media.MediaCodec.native_stop(Native Method)
                                                                                 at android.media.MediaCodec.stop(MediaCodec.java:1901)
                                                                                 at com.google.android.exoplayer.MediaCodecTrackRenderer.q(Unknown Source)
                                                                                 at com.google.android.exoplayer.MediaCodecTrackRenderer.j(Unknown Source)
                                                                                 at com.google.android.exoplayer.al.j(Unknown Source)
                                                                                 at com.google.android.exoplayer.bd.x(Unknown Source)
                                                                                 at com.google.android.exoplayer.q.e(Unknown Source)
                                                                                 at com.google.android.exoplayer.q.b(Unknown Source)
                                                                                 at com.google.android.exoplayer.q.n(Unknown Source)
                                                                                 at com.google.android.exoplayer.q.l(Unknown Source)
                                                                                 at com.google.android.exoplayer.q.handleMessage(Unknown Source)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                 at com.google.android.exoplayer.util.z.run(Unknown Source)

**Comment by bbcallen** [comment]
Then you should submit issue to exoplayer.
