### ISSUE TITLE
android java.lang.RuntimeException: createWindowSurface failed EGL_BAD_ALLOC怎么解决啊

### ISSUE THREAD

**Issue by dazhiyu** [Bilibili/ijkplayer#2077]
java.lang.RuntimeException: createWindowSurface failed EGL_BAD_ALLOC
    at android.view.HardwareRenderer$GlRenderer.createSurface(HardwareRenderer.java:1359)
    at android.view.HardwareRenderer$GlRenderer.createEglSurface(HardwareRenderer.java:1245)
    at android.view.HardwareRenderer$GlRenderer.initialize(HardwareRenderer.java:1062)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1935)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1311)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6711)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
    at android.view.Choreographer.doCallbacks(Choreographer.java:613)
    at android.view.Choreographer.doFrame(Choreographer.java:583)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:146)
    at android.app.ActivityThread.main(ActivityThread.java:5756)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
    at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by dazhiyu** [comment]
compile 'tv.danmaku.ijk.media:ijkplayer-java:0.5.1'
