### ISSUE TITLE
null mp

### ISSUE THREAD

**Issue by gogolq** [Bilibili/ijkplayer#2136]
java.lang.IllegalStateException: mpjni: start: null mp
	at tv.danmaku.ijk.media.player.IjkMediaPlayer._start(Native Method)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.start(IjkMediaPlayer.java:496)

我在调用start方法的时候，偶发这种崩溃，不知道是什么原因造成的，能否容错呢？

**Comment by bbcallen** [comment]
Very likely, you called start() at a wrong time, or from wrong thread.
