### ISSUE TITLE
How to solve

### ISSUE THREAD

**Issue by woyoudianhuai** [Bilibili/ijkplayer#2168]
FATAL EXCEPTION: main
                                                                              Process: tv.danmaku.ijk.media.example, PID: 12753
                                                                              Theme: themes:{}
                                                                              java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-support-annotations-23.0.1_55e35f4e0c8b0d39bc664c76a9b025a0820f8b42-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-otto-1.3.8_c5b64cb236f24b830738e84fb7f857bb1e2d3765-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-internal_impl-23.0.1_f5190db0db20b1a55f0ed35236f032ae2ab89a88-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-com.google.android.exoplayer-exoplayer-r1.5.11_9fb04663c3febf2c012b5ea2efc252a907a55e9b-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-com.android.support-support-v4-23.0.1_e2b393b1ff204f9f6915eba9a6f00e686cf7914e-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-com.android.support-recyclerview-v7-23.0.1_d94759305aed7d91358d7f9dd568208cdc6b152d-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-com.android.support-preference-v7-23.0.1_c43116b60f98a3f5a6f5fb3eaf4c719279e985a1-classes.dex", dex file "/data/data/tv.danmaku.ijk.media.example/files/instant-run/dex/slice-com.android.support-appcompat-v7-23.0.1_a43b2f080fa8fd62c921e5d0789ee0d7c90b3ee1-classes.dex"],nativeLibraryDirectories=[/data/app/tv.danmaku.ijk.media.example-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libijkffmpeg.so"
                                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                                  at java.lang.System.loadLibrary(System.java:1076)
                                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:163)
                                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:174)
                                                                                  at tv.danmaku.ijk.media.example.activities.VideoActivity.onCreate(VideoActivity.java:136)

**Comment by woyoudianhuai** [comment]
You must define ANDROID_NDK, ANDROID_SDK before starting.
They must point to your NDK and SDK directories.\n

**Comment by bbcallen** [comment]
Follow README
