### ISSUE TITLE
ijkplayer加载so文件出错

### ISSUE THREAD

**Issue by PillarChen** [Bilibili/ijkplayer#2226]
ijkplayer加载so文件出错，新建Demo中测试正常播放视频，但是迁移到项目中就无法正常加载so文件什么原因，提示信息：
E/GiraffePlayer: loadLibraries error
                                                                 java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.hxgx.clubapp-1/lib/arm64/libijkffmpeg.so" is 32-bit instead of 64-bit
                                                                     at java.lang.Runtime.loadLibrary(Runtime.java:384)
                                                                     at java.lang.System.loadLibrary(System.java:1086)
                                                                     at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
                                                                     at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:168)
                                                                     at com.hxgx.clubapp.ijkplayer.common.PlayerManager.<init>(PlayerManager.java:134)
                                                                     at com.hxgx.clubapp.ijkplayer.ui.LiveTestActivity.initPlayer(LiveTestActivity.java:43)
                                                                     at com.hxgx.clubapp.ijkplayer.ui.LiveTestActivity.onCreate(LiveTestActivity.java:29)
                                                                     at android.app.Activity.performCreate(Activity.java:6367)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
                                                                     at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:150)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
11-07 15:51:49.089 22461-22461/com.hxgx.clubapp E/PlayerManager.java: [<init>:194]播放器不支持此设备

**Comment by xiangguoqiang** [comment]
请问如何解决啊？
