### ISSUE TITLE
Crash in demo when i make getEnableDetachedSurfaceTextureView() return true.

### ISSUE THREAD

**Issue by martin90s** [Bilibili/ijkplayer#2358]
I want ijkvideoview enabled when it has beed detached.so i open this switcher,but after i remove ijkvideoview and add to another parent. i get 

` java.lang.IllegalArgumentException: Cannot setSurfaceTexture to a released SurfaceTexture
                                                                                     at android.view.TextureView.setSurfaceTexture(TextureView.java:725)
                                                                                     at tv.danmaku.ijk.media.player.widget.media.TextureRenderView$InternalSurfaceHolder.bindToMediaPlayer(TextureRenderView.java:156)
                                                                                     at tv.danmaku.ijk.media.player.widget.media.IjkVideoView.bindSurfaceHolder(IjkVideoView.java:614)
                                                                                     at tv.danmaku.ijk.media.player.widget.media.IjkVideoView.access$2300(IjkVideoView.java:51)
                                                                                     at tv.danmaku.ijk.media.player.widget.media.IjkVideoView$8.onSurfaceCreated(IjkVideoView.java:648)
                                                                                     at tv.danmaku.ijk.media.player.widget.media.TextureRenderView$SurfaceCallback.onSurfaceTextureAvailable(TextureRenderView.java:259)`

**Comment by bbcallen** [comment]
You can not reuse TextureView safely.
The lifecycle of TextureView is weird on some devices.
You can only reuse SurfaceTexture.

**Comment by klauswng** [comment]
1、这个问题是由于改变了mTextureView的mSurfaceTexture导致的；
2、造成这样的原因可能是你将demo切换到后台，然后又切回到前台，此时会触发onSurfaceCreated，从而触发bindSurfaceHolder，从而调用mTextureView.setSurfaceTexture(surfaceTexture);，此时surfaceTexture是从播放器获取到的，与mTextureView.mSurface不一样，所以setSurfaceTexture中会执行mSurface.release()主动将其释放掉，然后更改为播放器的surface，而此时mSurfaceTexture保存的surface已经被release了。
3、此时如果重新创建播放器并设置播放器的surface，就会出现上面的crash，因为你此时设置的SurfaceTexture就是mSurfaceTexture。
@bbcallen @martin90s

**Comment by lgengsy** [comment]
@klauswng 怎么解决这个问题呢 ？？？

**Comment by lgengsy** [comment]
` if (mSurfaceTexture != null ){
                    textureHolder.setSurfaceTexture(mSurfaceTexture);
                    textureHolder.setSurfaceTextureHost(mTextureView.mSurfaceCallback);

                }else{
                    if (surfaceTexture != null){
                        mTextureView.setSurfaceTexture(surfaceTexture);
                    }

                }`
这样临时解决了下，没有出现了 。
