### ISSUE TITLE
运行demo中的sample在线视频崩溃

### ISSUE THREAD

**Issue by xiaoguxg** [Bilibili/ijkplayer#2372]
打开demo，运行sample中的视频会崩溃

**Comment by gewuxy** [comment]
我也遇到了这个问题：
FATAL EXCEPTION: main
                                                                              Process: tv.danmaku.ijk.media.example, PID: 12622
                                                                              java.lang.UnsatisfiedLinkError: Couldn't load ijkffmpeg from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.example-1.apk"],nativeLibraryDirectories=[/data/app-lib/tv.danmaku.ijk.media.example-1, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                                                  at java.lang.System.loadLibrary(System.java:526)
                                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:163)
                                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:174)
                                                                                  at tv.danmaku.ijk.media.example.activities.VideoActivity.onCreate(VideoActivity.java:136)
                                                                                  at android.app.Activity.performCreate(Activity.java:5293)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2154)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
                                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:136)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5049)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
                                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by Drjacky** [comment]
Same problem here.
```
02-20 17:38:01.668 505-3195/? I/ActivityManager: START u0 {cmp=tv.danmaku.ijk.media.example/.activities.VideoActivity (has extras)} from pid 3949
02-20 17:38:01.668 505-3195/? I/ActivityManager: start package name is tv.danmaku.ijk.media.example, class name is tv.danmaku.ijk.media.example.activities.VideoActivity, error code is 0
02-20 17:38:01.698 3949-3949/tv.danmaku.ijk.media.example I/dalvikvm: Could not find method android.widget.FrameLayout.<init>, referenced from method tv.danmaku.ijk.media.example.widget.media.IjkVideoView.<init>
02-20 17:38:01.698 3949-3949/tv.danmaku.ijk.media.example W/dalvikvm: VFY: unable to resolve direct method 17053: Landroid/widget/FrameLayout;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
02-20 17:38:01.698 3949-3949/tv.danmaku.ijk.media.example D/dalvikvm: VFY: replacing opcode 0x70 at 0x0005
02-20 17:38:01.708 3949-3949/tv.danmaku.ijk.media.example I/dalvikvm: Could not find method android.view.SurfaceView.<init>, referenced from method tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView.<init>
02-20 17:38:01.708 3949-3949/tv.danmaku.ijk.media.example W/dalvikvm: VFY: unable to resolve direct method 16245: Landroid/view/SurfaceView;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
02-20 17:38:01.708 3949-3949/tv.danmaku.ijk.media.example D/dalvikvm: VFY: replacing opcode 0x70 at 0x0000
                                                                      
                                                                      [ 02-20 17:38:01.718  3949: 3949 E/         ]
                                                                      SurfaceView doesn't support rotation (0)!
02-20 17:38:01.748 3949-3949/tv.danmaku.ijk.media.example D/dalvikvm: GC_FOR_ALLOC freed 162K, 8% free 2416K/2604K, paused 6ms, total 6ms
02-20 17:38:01.748 3949-3949/tv.danmaku.ijk.media.example D/AndroidRuntime: Shutting down VM
02-20 17:38:01.748 3949-3949/tv.danmaku.ijk.media.example W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x416f9ba8)
02-20 17:38:01.748 3949-3949/tv.danmaku.ijk.media.example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: tv.danmaku.ijk.media.example, PID: 3949
                                                                            java.lang.UnsatisfiedLinkError: Couldn't load ijkffmpeg from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.example-1.apk"],nativeLibraryDirectories=[/data/app-lib/tv.danmaku.ijk.media.example-1, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                                                at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                                                at java.lang.System.loadLibrary(System.java:526)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:175)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:186)
                                                                                at tv.danmaku.ijk.media.example.activities.VideoActivity.onCreate(VideoActivity.java:137)
                                                                                at android.app.Activity.performCreate(Activity.java:5281)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
                                                                                at dalvik.system.NativeStart.main(Native Method)
02-20 17:38:01.758 505-621/? W/ActivityManager:   Force finishing activity tv.danmaku.ijk.media.example/.activities.VideoActivity
02-20 17:38:01.758 3949-3949/tv.danmaku.ijk.media.example I/Process: Sending signal. PID: 3949 SIG: 9
02-20 17:38:01.758 505-621/? W/ActivityManager:   Force finishing activity tv.danmaku.ijk.media.example/.activities.FileExplorerActivity
02-20 17:38:01.808 505-2623/? D/ActivityManager: send app_CRASH broadcast, packageName:tv.danmaku.ijk.media.example
02-20 17:38:01.808 505-2623/? I/ActivityManager: Process tv.danmaku.ijk.media.example (pid 3949) has died.
02-20 17:38:01.808 505-3145/? I/WindowState: WIN DEATH: Window{41e04330 u0 tv.danmaku.ijk.media.example/tv.danmaku.ijk.media.example.activities.FileExplorerActivity}
02-20 17:38:01.808 505-2623/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1162 com.android.server.am.ActivityManagerService.onVideoPlayerCrashed:3689 com.android.server.am.ActivityManagerService.handleAppDiedLocked:3719 com.android.server.am.ActivityManagerService.appDiedLocked:3857 com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied:1046 
02-20 17:38:01.808 505-2623/? D/ActivityManager: resumeClassName is com.amlogic.mediaboxlauncher.Launcher
02-20 17:38:01.808 505-2623/? D/ActivityManager: resumePackageName is com.amlogic.mediaboxlauncher
02-20 17:38:01.818 651-651/? D/MediaBoxLauncher: ------onResume
02-20 17:38:01.828 721-741/? W/InputMethodWrapper: Session is null
02-20 17:38:01.828 505-824/? W/InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 3949 uid 10060
02-20 17:38:01.898 128-128/? W/SurfaceFlinger: couldn't log to binary event log: overflow.
02-20 17:38:02.498 505-515/? D/dalvikvm: GC_FOR_ALLOC freed 1897K, 22% free 9234K/11792K, paused 29ms, total 29ms
```

**Comment by raymond1012** [comment]
need to load lib, please follow README
