### ISSUE TITLE
Connection timed out（android）

### ISSUE THREAD

**Issue by jisuz** [Bilibili/ijkplayer#2394]
在测试摄像头的时候，采用的视频协议是HLS，有些摄像头连接一直无法连接上，出现了Connection timed out，想请教一下，这个是什么问题？
logcat如下：

12-06 15:37:09.051 16342-16342/? I/wpa_supplicant: wlan0: HEART-BEAT-ACK: 628
12-06 15:37:13.426 2421-2421/? E/Thermal-daemon: [ap] temp_new :37  temp_old :38
12-06 15:37:13.426 2421-2421/? E/Thermal-daemon: Report temperature: [ap] temp :37  report_threshold:1
12-06 15:37:16.956 2408-2925/? E/CommandListener: readDefRoute call readDefRoute
12-06 15:37:16.956 2408-2925/? E/SecondaryTablController: isWifiDefaultRouteExisted /system/bin/ip route
12-06 15:37:17.961 2408-2925/? E/CommandListener: readDefRoute Rsp ok
12-06 15:37:20.676 28262-31020/com.nenglong.giraffeplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
12-06 15:37:20.676 28262-31020/com.nenglong.giraffeplayer E/IJKMEDIA: http://61.191.35.42:10080/live.m3u8?token=b2d87d87bb8611e687040894ef09fdc3552198104a7e1a40ff88ea2f51979726: Connection timed out
12-06 15:37:20.676 28262-31020/com.nenglong.giraffeplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [31020]
12-06 15:37:20.681 28262-28262/com.nenglong.giraffeplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
12-06 15:37:24.071 16342-16342/? I/wpa_supplicant: wlan0: HEART-BEAT-ACK: 629

**Comment by jisuz** [comment]
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: av_version_info: ff3.2--ijk0.7.0--20161102--001
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: ijk_version_info: k0.7.2
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: ===== versions =====
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: ijkplayer    : k0.7.2
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: FFmpeg       : ff3.2--ijk0.7.0--20161102--001
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: libavutil    : 55.34.100
12-06 16:51:11.810 4749-7384/? I/IJKMEDIA: SDL_RunThread: [7384] ff_msg_loop
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: libavcodec   : 57.64.100
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: libavformat  : 57.56.100
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: libswscale   : 4.2.100
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: libswresample: 2.3.100
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: ===== options =====
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: player-opts : mediacodec                   = 0
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: player-opts : opensles                     = 0
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: player-opts : overlay-format               = 842225234
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: player-opts : framedrop                    = 1
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: player-opts : start-on-prepared            = 0
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: player-opts : packet-buffering             = 0
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: format-opts : ijkapplication               = 2039229856
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: format-opts : http-detect-range-support    = 0
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: format-opts : timeout                      = 50000000
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: format-opts : reconnect                    = 1
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: codec-opts  : skip_loop_filter             = 48
12-06 16:51:11.810 4749-4749/? I/IJKMEDIA: ===================
12-06 16:51:11.810 4749-7385/? I/IJKMEDIA: SDL_RunThread: [7385] ff_vout
12-06 16:51:11.810 4749-7386/? I/IJKMEDIA: SDL_RunThread: [7386] ff_read
12-06 16:51:11.815 4749-7386/? I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
12-06 16:51:11.815 4749-7386/? I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
12-06 16:51:11.845 6498-6498/com.nenglong.jxhd.client.yeb W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
12-06 16:51:11.855 2926-2941/? I/ActivityManager: Displayed com.nenglong.giraffeplayer/.ExternalRequestsActivity: +263ms
12-06 16:51:11.875 4749-7386/? I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
12-06 16:51:12.015 2408-2925/? E/CommandListener: readDefRoute Rsp ok
12-06 16:51:12.145 3350-17670/? I/HwLauncher: Launcher.LauncherProvider  begin check permission at checkPermission 
12-06 16:51:12.145 3350-17670/? W/System.err: java.lang.SecurityException: Permission Denial: reading com.huawei.android.launcher.LauncherProvider from pid=1709, uid=10087 requires com.huawei.android.launcher.permission.WRITE_SETTINGS: uid 10087 does not have com.huawei.android.launcher.permission.WRITE_SETTINGS.
12-06 16:51:12.145 3350-17670/? W/System.err:     at android.app.ContextImpl.enforce(ContextImpl.java:1775)
12-06 16:51:12.145 3350-17670/? W/System.err:     at android.app.ContextImpl.enforcePermission(ContextImpl.java:1787)
12-06 16:51:12.145 3350-17670/? W/System.err:     at android.content.ContextWrapper.enforcePermission(ContextWrapper.java:561)
12-06 16:51:12.145 3350-17670/? W/System.err:     at com.huawei.android.launcher.LauncherProvider.checkPermission(LauncherProvider.java:560)
12-06 16:51:12.145 3350-17670/? W/System.err:     at com.huawei.android.launcher.LauncherProvider.call(LauncherProvider.java:575)
12-06 16:51:12.145 3350-17670/? W/System.err:     at android.content.ContentProvider$Transport.call(ContentProvider.java:325)
12-06 16:51:12.145 3350-17670/? W/System.err:     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:284)
12-06 16:51:12.145 3350-17670/? W/System.err:     at android.os.Binder.execTransact(Binder.java:404)
12-06 16:51:12.145 3350-17670/? W/System.err:     at dalvik.system.NativeStart.run(Native Method)
12-06 16:51:12.145 3350-17670/? E/DatabaseUtils: Writing exception to parcel
                                                 java.lang.SecurityException: Permission Denial: reading com.huawei.android.launcher.LauncherProvider from pid=1709, uid=10087 requires com.huawei.android.launcher.permission.WRITE_SETTINGS: uid 10087 does not have com.huawei.android.launcher.permission.WRITE_SETTINGS.
                                                     at android.app.ContextImpl.enforce(ContextImpl.java:1775)
                                                     at android.app.ContextImpl.enforcePermission(ContextImpl.java:1787)
                                                     at android.content.ContextWrapper.enforcePermission(ContextWrapper.java:561)
                                                     at com.huawei.android.launcher.LauncherProvider.checkPermission(LauncherProvider.java:560)
                                                     at com.huawei.android.launcher.LauncherProvider.call(LauncherProvider.java:575)
                                                     at android.content.ContentProvider$Transport.call(ContentProvider.java:325)
                                                     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:284)
                                                     at android.os.Binder.execTransact(Binder.java:404)
                                                     at dalvik.system.NativeStart.run(Native Method)
