### ISSUE TITLE
BufferQueueProducer: connect(P): already connected (cur=2 req=3)

### ISSUE THREAD

**Issue by abepisces** [Bilibili/ijkplayer#2397]
Hi, all,
My APP has feature of playing media file which are from mobile phone either from YouTube streaming.
In case of mobile phone media file, play it by IjkMediaPlayer.
In case of YouTube streaming, play it by IjkExoMediaPlayer and embed ExoPlayer version 2.0.4.
Now, here is my problem, IjkExoMediaPlayer will initialize FAIL if playing WMV or DivX file by IjkMediaPlayer prior to initialize IjkExoMediaPlayer. I think the key error is shown on as title. Does it mean I didn't correct release some important resource?
I have made sure I have done
		m_MediaPlayer.release();
		m_MediaPlayer.setOnPreparedListener(null);
		m_MediaPlayer.setOnCompletionListener(null);
		m_MediaPlayer.setOnErrorListener(null);
		m_MediaPlayer = null;
		m_iCurrentState = MPMP.State.END;
                m_Surface.release();
	        m_Surface = null;

[My test procedure]
1. Set player to IjkMediaPlayer
2. Play a media which is encoded by WMV or DivX.
3. Stop playback
4. Set player to IjkExoMediaPlayer
5. Try to start play a YouTube stream.

[Result]
Video can not start playback and got error log as below.

[Brief Log]
E/BufferQueueProducer: [unnamed-32064-2] connect(P): already connected (cur=2 req=3)
E/MediaCodec: native_window_api_connect returned an error: Invalid argument (-22)
E/MediaCodec: configure failed with err 0xffffffea, resetting...

[Detail Log]
E/BufferQueueProducer: [unnamed-32064-2] connect(P): already connected (cur=2 req=3)
E/MediaCodec: native_window_api_connect returned an error: Invalid argument (-22)
E/MediaCodec: configure failed with err 0xffffffea, resetting...
              
              [ 12-06 20:16:19.705 28644:15237 E/         ]
              Destroy C2D instance
              
              [ 12-06 20:16:19.705 28644:15237 E/         ]
              Destroy C2D instance
I/OMXClient: Using client-side OMX mux.
W/System.err: android.media.MediaCodec$CodecException: Error 0xffffffea
W/System.err:     at android.media.MediaCodec.native_configure(Native Method)
W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:594)
W/System.err:     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:339)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:856)
W/System.err:     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:350)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:569)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:550)
W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:454)
W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:287)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err:     at android.os.Looper.loop(Looper.java:211)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err:     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
D/MediaCodecRenderer:  AMT_TAG maybeInitCodec #390codec.start() 
W/System.err: java.lang.IllegalStateException: start failed
W/System.err:     at android.media.MediaCodec.native_start(Native Method)
W/System.err:     at android.media.MediaCodec.start(MediaCodec.java:686)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:392)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:856)
W/System.err:     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:350)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:569)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:550)
W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:454)
W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:287)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err:     at android.os.Looper.loop(Looper.java:211)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err:     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
D/MediaCodecRenderer:  AMT_TAG maybeInitCodec #400onCodecInitialized() 
D/MediaCodecRenderer:  AMT_TAG maybeInitCodec #410codec.getInputBuffers() 
W/System.err: java.lang.IllegalStateException
W/System.err:     at android.media.MediaCodec.getInputBuffers(MediaCodec.java:1449)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:411)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:856)
W/System.err:     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:350)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:569)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:550)
W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:454)
W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:287)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err:     at android.os.Looper.loop(Looper.java:211)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err:     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
D/MediaCodecRenderer:  AMT_TAG maybeInitCodec #418codec.getOutputBuffers() 
W/System.err: java.lang.IllegalStateException
W/System.err:     at android.media.MediaCodec.getOutputBuffers(MediaCodec.java:1477)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:419)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:856)
W/System.err:     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:350)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:569)
W/System.err:     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:550)
W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:454)
W/System.err:     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:287)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err:     at android.os.Looper.loop(Looper.java:211)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err:     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/ExoPlayerImplInternal: Internal runtime error.
                         java.lang.IllegalStateException
                             at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                             at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1107)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:958)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:555)
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:454)
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:287)
                             at android.os.Handler.dispatchMessage(Handler.java:98)
                             at android.os.Looper.loop(Looper.java:211)
                             at android.os.HandlerThread.run(HandlerThread.java:61)
                             at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
D/MediaCodecRenderer:  AMT_TAG releaseCodec #512 
D/IjkExoMediaPlayer:  AMT_TAG access$3 #910 onPlayerError #852 error:com.google.android.exoplayer2.ExoPlaybackException
E/MPMP: onError:1
E/MPMP: extra:1
E/MPMP: ID:3
D/Streaming Media: MEDIA_ERROR_UNKNOWN
D/Streaming Media: MEDIA_INFO_UNKNOWN
D/MediaCodecRenderer:  AMT_TAG releaseCodec #516 
                                           
                                           [ 12-06 20:16:19.742 28644:10789 E/         ]
                                           Destroy C2D instance
                                           
                                           [ 12-06 20:16:19.742 28644:10789 E/         ]
                                           Destroy C2D instance

**Comment by xinzhengzhang** [comment]
IjkExoMediaPlayer is just a wrapper of ExoPlayer and I am not familiar with it.
I think that you should ask them directly.

**Comment by DipenBhagat** [comment]
I am also getting same error . 
 Have you found any solution?@abepisces

**Comment by AmitPal100001** [comment]
Hi @abepisces ,

I am getting same issue surfaceview already connected.  can you please share me solutions for that. Below is the logs.

03-15 15:01:44.429  2744  3364 E BufferQueueProducer: [SurfaceView - #0] connect: already connected (cur=2 req=3)
03-15 15:01:44.430  2819  2819 E         : 2866:IGraphicBufferProducer.cpp status_t (0)
03-15 15:01:44.430  2819  2819 E Surface : 2866: Suface.cpp connect err (-22)
03-15 15:01:44.430  2819  2819 E Surface : 2866: Suface.cpp connect mConsumerRunningBehind (-22) (3) (2)
03-15 15:01:44.430  2819  2819 E Surface : native cpp: Suface.cpp perform complete (-22)
03-15 15:01:44.430  2819  2819 E SurfaceUtils: Failed to connect to surface 0xf477e008, err -22
03-15 15:01:44.430  2819  2819 E MediaPlayerService: setVideoSurfaceTexture failed: -22
03-15 15:01:44.430  2819  2819 D NuPlayerDriver: reset(0xf477d700) at state 2
03-15 15:01:44.430  2819 10068 D NuPlayerDriver: notifyResetComplete(0xf477d700)
03-15 15:01:44.430  2819  2819 E Surface : 2866:Surface.cpp ::~Surface() (0)
03-15 15:01:44.433  9986  9986 D AndroidRuntime: Shutting down VM
03-15 15:01:44.435  9986  9986 E AndroidRuntime: FATAL EXCEPTION: main
03-15 15:01:44.435  9986  9986 E AndroidRuntime: Process: jp.co.ricoh.advop.customize, PID: 9986
03-15 15:01:44.435  9986  9986 E AndroidRuntime: java.lang.IllegalStateException
03-15 15:01:44.435  9986  9986 E AndroidRuntime: 	at android.media.MediaPlayer._prepare(Native Method)
03-15 15:01:44.435  9986  9986 E AndroidRuntime: 	at android.media.MediaPlayer.prepare(MediaPlayer.java:1274)
03-15 15:01:44.435  9986  9986 E AndroidRuntime: 	at jp.co.ricoh.advop.customize.view.VideoSurfaceView$1.onPostExecute(VideoSurfaceView.java:203)
03-15 15:01:44.435  9986  9986 E AndroidRuntime: 	at jp.co.ricoh.advop.customize.view.VideoSurfaceView$1.onPostExecute(VideoSurfaceView.java:120)
03-15 15:01:44.435  9986  9986 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:755)
03-15 15:01:44.435  9986  9986 E AndroidRuntime: 	at android.os.AsyncTask.access$900(AsyncTask.java:192)
03-15 15:01:44.435  9986  9986 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
03-15 15:01:44.435  9986  9986 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-15 15:01:44.435  9986  9986 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)


Thanks,
Amit
