### ISSUE TITLE
Android arm64 动态加载so报错

### ISSUE THREAD

**Issue by zhousuqiang** [Bilibili/ijkplayer#2456]
android api 22
cup arm64
设备小米盒子3 pro
问题描述so文件动态加载在64位系统上加载报错，32位系统正常，请帮忙分析谢谢。
log如下：
I/[EduTvPlayer_Log](12018): loadLibrary...libName = /data/data/com.huan.edu.tvplayer.example2/libs/libijkffmpeg.so , exists = true
I/[EduTvPlayer_Log](12018): loadLibrary...libName = /data/data/com.huan.edu.tvplayer.example2/libs/libijksdl.so , exists = true
E/art     (12018): dlopen("/data/data/com.huan.edu.tvplayer.example2/libs/libijksdl.so", RTLD_LAZY) failed: dlopen failed: library "libijkffmpeg.so" not found
E/AndroidRuntime(12018): java.lang.UnsatisfiedLinkError: dlopen failed: library "libijkffmpeg.so" not found
E/AndroidRuntime(12018): 	at java.lang.Runtime.load(Runtime.java:331)
E/AndroidRuntime(12018): 	at java.lang.System.load(System.java:981)
E/AndroidRuntime(12018): 	at com.huan.edu.tvplayer.utils.EPLibraryUtil$1$1.loadLibrary(EPLibraryUtil.java:85)
E/AndroidRuntime(12018): 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:175)
E/AndroidRuntime(12018): 	at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:78)
E/AndroidRuntime(12018): 	at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:59)
E/AndroidRuntime(12018): 	at android.os.AsyncTask.finish(AsyncTask.java:636)
E/AndroidRuntime(12018): 	at android.os.AsyncTask.access$500(AsyncTask.java:177)
E/AndroidRuntime(12018): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
E/AndroidRuntime(12018): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12018): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(12018): 	at android.app.ActivityThread.main(ActivityThread.java:5302)
E/AndroidRuntime(12018): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12018): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(12018): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:917)
E/AndroidRuntime(12018): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

**Comment by ctiao** [comment]
add dep      compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.7.5'

**Comment by zhousuqiang** [comment]
@ctiao 我是动态加载的so,在代码里面播放之前把so放到了/data/data/com.huan.edu.tvplayer.example2/libs/下，log里面我也打印了I/EduTvPlayer_Log: loadLibrary...libName = /data/data/com.huan.edu.tvplayer.example2/libs/libijkffmpeg.so , exists = true
明明so文件有，为什么加载时提示找不到呢？

**Comment by discoy** [comment]
who has idea with this issue?

**Comment by discoy** [comment]
@ctiao do you have idea with this issue?

**Comment by hseury** [comment]
请问最终有解决方案吗

**Comment by Chen-Ji-Mou** [comment]
是不是没有指定libs目录为so库加载路径，AS默认so库加载路径是jniLibs，可以在模块的build.gradle文件中指定
```gradle
android {
    ......
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}
```
