### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by loyabe** [Bilibili/ijkplayer#2493]
4.1 至4.3会出现这个问题
FATAL EXCEPTION: main
                                                                java.lang.UnsatisfiedLinkError: Cannot load library: find_library[1201]:   163 'libijksdl.so' failed to load previously
                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:370)
                                                                    at java.lang.System.loadLibrary(System.java:535)
                                                                    at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:163)
                                                                    at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:175)
                                                                    at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:215)
                                                                    at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:211)
                                                                    at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:202)
                                                                    at com.shuyu.gsyvideoplayer.GSYVideoManager.<init>(GSYVideoManager.java:189)
                                                                    at com.shuyu.gsyvideoplayer.GSYVideoManager.instance(GSYVideoManager.java:69)
                                                                    at com.shuyu.gsyvideoplayer.GSYVideoPlayer.isCurrentMediaListener(GSYVideoPlayer.java:1046)
                                                                    at com.shuyu.gsyvideoplayer.GSYVideoPlayer.setUp(GSYVideoPlayer.java:244)
                                                                    at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.setUp(StandardGSYVideoPlayer.java:146)
                                                                    at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.setUp(StandardGSYVideoPlayer.java:141)
                                                                    at com.hutchind.cordova.plugins.streamingmedia.PlayActivity.init(PlayActivity.java:75)
                                                                    at com.hutchind.cordova.plugins.streamingmedia.PlayActivity.onCreate(PlayActivity.java:60)
                                                                    at android.app.Activity.performCreate(Activity.java:5203)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2078)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2139)
                                                                    at android.app.ActivityThread.access$700(ActivityThread.java:143)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                    at android.os.Looper.loop(Looper.java:137)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:4960)

**Comment by loyabe** [comment]
4.4版本不会出现这个问题。
