### ISSUE TITLE
Didn't find class "tv.danmaku.ijk.media.player.IjkMediaException"

### ISSUE THREAD

**Issue by xin5739** [Bilibili/ijkplayer#2557]
运行sample出现了ClassNotFoundException， IjkMediaException在ijkplayer-java中的package路径是tv.danmaku.ijk.media.player.exceptions， 不过在ijkplayer_jni.c中
#define JNI_IJK_MEDIA_EXCEPTION "tv/danmaku/ijk/media/player/IjkMediaException"
二者的包名路径不一致， 是这个原因导致？

E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: tv.danmaku.ijk.media.sample, PID: 7777
                                                 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "tv.danmaku.ijk.media.player.IjkMediaException" on path: DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/tv.danmaku.ijk.media.sample-1/lib/arm, /data/app/tv.danmaku.ijk.media.sample-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at tv.danmaku.ijk.media.player.IjkMediaPlayer._prepareAsync(Native Method)
                                                     at tv.danmaku.ijk.media.player.IjkMediaPlayer.prepareAsync(IjkMediaPlayer.java:463)
                                                     at tv.danmaku.ijk.media.sample.widget.media.IjkVideoView.openVideo(IjkVideoView.java:319)
                                                     at tv.danmaku.ijk.media.sample.widget.media.IjkVideoView.access$2200(IjkVideoView.java:58)
                                                     at tv.danmaku.ijk.media.sample.widget.media.IjkVideoView$7.onSurfaceCreated(IjkVideoView.java:646)
                                                     at tv.danmaku.ijk.media.sample.widget.media.SurfaceRenderView$SurfaceCallback.surfaceCreated(SurfaceRenderView.java:233)
                                                     at android.view.SurfaceView.updateWindow(SurfaceView.java:597)
                                                     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:179)
                                                     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2082)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6045)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:672)

**Comment by panda912** [comment]
I have the same problem.
