### ISSUE TITLE
android.view.Surface.release never called.StrictMode:A resource was acquired at attached stack trace but never released

### ISSUE THREAD

**Issue by xh2009cn** [Bilibili/ijkplayer#2560]
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                                     java.lang.Throwable: Explicit termination method 'release' not called
                                                                                         at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                                         at android.view.Surface.setNativeObjectLocked(Surface.java:433)
                                                                                         at android.view.Surface.<init>(Surface.java:136)
                                                                                         at tv.danmaku.ijk.media.player.TextureMediaPlayer.setSurfaceTexture(TextureMediaPlayer.java:86)
                                                                                         at com.husor.android.hbvideoplayer.media.TextureRenderView$InternalSurfaceHolder.bindToMediaPlayer(TextureRenderView.java:165)
                                                                                         at com.husor.android.hbvideoplayer.media.IjkVideoView.bindSurfaceHolder(IjkVideoView.java:659)
                                                                                         at com.husor.android.hbvideoplayer.media.IjkVideoView.openVideo(IjkVideoView.java:572)
                                                                                         at com.husor.android.hbvideoplayer.media.IjkVideoView.setVideoURI(IjkVideoView.java:515)
                                                                                         at com.husor.android.hbvideoplayer.media.IjkVideoView.setVideoURI(IjkVideoView.java:498)
                                                                                         at com.husor.android.hbvideoplayer.media.IjkVideoView.setVideoPath(IjkVideoView.java:489)

**Comment by niufeihu** [comment]
i have the same question.did you solved it.
