### ISSUE TITLE
请问一下这个空异常的原因？？？

### ISSUE THREAD

**Issue by xieyucheng** [Bilibili/ijkplayer#2621]
Failed to apply optimization [4, 0]
01-23 14:43:06.646 10896-10986/ E/GLConsumer: [SurfaceTexture-0-10896-2] detachFromContext: GLConsumer is not attached to a context
01-23 14:43:06.646 10896-10986 E/OpenGLRenderer: Failed to detach SurfaceTexture from context -38
01-23 14:43:06.872 10896-10896 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.swl.koocan, PID: 10896
                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.HardwareLayer.setLayerPaint(android.graphics.Paint)' on a null object reference
                                                                    at android.view.TextureView.getHardwareLayer(TextureView.java:370)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                    at android.view.View.draw(View.java:15971)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                    at android.view.View.draw(View.java:16204)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                    at android.view.View.draw(View.java:15971)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                    at android.view.View.draw(View.java:15971)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                    at android.view.View.draw(View.java:15971)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                    at android.view.View.draw(View.java:15971)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                    at android.view.View.draw(View.java:16204)
                                                                    at android.support.v4.view.ViewPager.draw(ViewPager.java:2341)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                    at android.view.View.draw(View.java:15971)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                    at android.view.View.draw(View.java:15971)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                    at android.view.View.draw(View.java:15971)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                    at android.view.View.draw(View.java:15971)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                    at android.view.View.draw(View.java:15971)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                    at android.view.View.draw(View.java:15971)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                    at android.view.View.draw(View.java:16204)
                                                                    at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                                                                    at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
                                                                    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
                                                                    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
                                                                    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642)
                                                                    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2461)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                	at androi

**Comment by minghao8848** [comment]
你好，我把SurfaceView换成TextureView播放本地视频也会有这个问题，播放网络视频是正常的，请问你是怎么解决的
