### ISSUE TITLE
[OMX.hisi.video.decoder] 硬解4K视频失败

### ISSUE THREAD

**Issue by c19354837** [Bilibili/ijkplayer#2723]
在做机顶盒播放测试时，发现无法播放4K视频，初步断定是hisi解码出现问题，详细信息见下，希望能帮忙看下，谢谢

**测试硬件**
华为荣耀盒子，型号MediaQ M321

**现象**
使用硬解，播放低分辨率（1920*960）正常，播放4K视频黑屏，日志有报错，错误信息见后面
 注：使用Android的MediaPlayer播放均正常

**硬解配置**
```
mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 1);
mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "overlay-format", IjkMediaPlayer.SDL_FCC_RV32);
mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "framedrop", 1);
mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max-fps", 0);
mPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_CODEC, "skip_loop_filter", 48);
```

**错误信息**
```
02-21 15:06:35.931 18306-18324/? I/IJKMEDIA: max_frame_duration: 10.000
02-21 15:06:35.931 18306-18324/? I/IJKMEDIA: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'http://10.9.212.112:9090/video/nj.mp4':
02-21 15:06:35.931 18306-18324/? I/IJKMEDIA:   Metadata:
02-21 15:06:35.931 18306-18324/? I/IJKMEDIA:     major_brand     : 
02-21 15:06:35.932 18306-18324/? I/IJKMEDIA: mp42
02-21 15:06:35.932 18306-18324/? I/IJKMEDIA:     minor_version   : 
02-21 15:06:35.932 18306-18324/? I/IJKMEDIA: 0
02-21 15:06:35.933 18306-18324/? I/IJKMEDIA:     compatible_brands: 
02-21 15:06:35.933 18306-18324/? I/IJKMEDIA: mp42mp41
02-21 15:06:35.933 18306-18324/? I/IJKMEDIA:     creation_time   : 
02-21 15:06:35.933 18306-18324/? I/IJKMEDIA: 2015-04-15T08:48:18.000000Z
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA:   Duration: 
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: 00:02:28.61
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: , start: 
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: 0.000000
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: , bitrate: 
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: 15126 kb/s
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA:     Stream #0:0
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: (eng)
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: : Video: h264 (avc1 / 0x31637661), yuv420p(tv), 4096x2048 [SAR 1:1 DAR 2:1], 14996 kb/s
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: , 
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: 23.98 fps, 
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: 23.98 tbr, 
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: 24k tbn, 
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: 47.95 tbc
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA:  (default)
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA:     Metadata:
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA:       creation_time   : 
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: 2015-04-15T08:48:18.000000Z
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA:       handler_name    : 
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: Mainconcept Video Media Handler
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA:       encoder         : 
02-21 15:06:35.934 18306-18324/? I/IJKMEDIA: AVC Coding
02-21 15:06:35.935 18306-18324/? I/IJKMEDIA:     Stream #0:1
02-21 15:06:35.935 18306-18324/? I/IJKMEDIA: (eng)
02-21 15:06:35.935 18306-18324/? I/IJKMEDIA: : Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 125 kb/s
02-21 15:06:35.935 18306-18324/? I/IJKMEDIA:  (default)
02-21 15:06:35.935 18306-18324/? I/IJKMEDIA:     Metadata:
02-21 15:06:35.935 18306-18324/? I/IJKMEDIA:       creation_time   : 
02-21 15:06:35.935 18306-18324/? I/IJKMEDIA: 2015-04-15T08:48:18.000000Z
02-21 15:06:35.935 18306-18324/? I/IJKMEDIA:       handler_name    : 
02-21 15:06:35.935 18306-18324/? I/IJKMEDIA: #Mainconcept MP4 Sound Media Handler
02-21 15:06:35.939 18306-18324/? I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
02-21 15:06:35.939 18306-18324/? I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
02-21 15:06:35.944 18306-18324/? I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
02-21 15:06:35.944 18306-18324/? I/IJKMEDIA: audio_session_id = 203
02-21 15:06:35.945 18306-18324/? I/IJKMEDIA: AudioCodec: avcodec, aac
02-21 15:06:35.945 18306-18327/? I/IJKMEDIA: SDL_RunThread: [18327] ff_aout_android
02-21 15:06:35.945 18306-18328/? I/IJKMEDIA: SDL_RunThread: [18328] ff_audio_dec
02-21 15:06:35.945 1413-27708/? D/AudioPolicyManagerBase: startOutput() output 2, stream 3, session 203
02-21 15:06:35.945 1413-27708/? D/AudioPolicyManagerBase: startoutput ->setOutputDevice
02-21 15:06:35.945 1413-27708/? D/AudioPolicyManagerBase: AudioPolicyManagerBase::checkAndSetVolume 1,0.066000
02-21 15:06:35.950 18306-18324/? D/IJKMEDIA: ffpipenode_create_video_decoder_from_android_mediacodec()
02-21 15:06:35.950 18306-18324/? I/IJKMEDIA: API-Level: 19
02-21 15:06:35.950 18306-18324/? I/IJKMEDIA: ffpipenode_create_video_decoder_from_android_mediacodec: MediaCodec: H264_MAIN: enabled
02-21 15:06:35.950 18306-18324/? I/IJKMEDIA: AMediaFormat: video/avc, 4096x2048
02-21 15:06:35.950 18306-18324/? D/IJKMEDIA: SDL_AMediaFormatJava_createVideoFormat
02-21 15:06:35.951 18306-18324/? E/IJKMEDIA: csd-0[39]: 00000001
02-21 15:06:35.951 18306-18324/? E/IJKMEDIA: csd-0[39]: 674d4033
02-21 15:06:35.951 18306-18324/? E/IJKMEDIA: csd-0[39]: 96520020
02-21 15:06:35.951 18306-18324/? E/IJKMEDIA: csd-0[39]: 00203602
02-21 15:06:35.951 18306-18324/? E/IJKMEDIA: csd-0[39]: a1000003
02-21 15:06:35.951 18306-18324/? E/IJKMEDIA: csd-0[39]: 03e90000
02-21 15:06:35.951 18306-18324/? E/IJKMEDIA: csd-0[39]: bb809da1
02-21 15:06:35.951 18306-18324/? E/IJKMEDIA: csd-0[39]: 62d12000
02-21 15:06:35.951 18306-18324/? E/IJKMEDIA: csd-0[39]: 00000168
02-21 15:06:35.951 18306-18324/? E/IJKMEDIA: csd-0[39]: eb735200
02-21 15:06:35.951 18306-18324/? I/IJKMEDIA: amc: rotate notify: 0
02-21 15:06:35.951 18306-18322/? D/IJKMEDIA: FFP_MSG_VIDEO_ROTATION_CHANGED: 0
02-21 15:06:35.952 18306-18324/? D/IJKMEDIA: ffpipeline_select_mediacodec_l
02-21 15:06:35.953 18306-18324/? I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onSelectCodec: mime=video/avc, profile=77, level=51
02-21 15:06:35.955 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.hisi.video.decoder
02-21 15:06:35.956 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/3gpp
02-21 15:06:35.956 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/avc
02-21 15:06:35.961 18306-18324/? I/OMXClient: Using client-side OMX mux.
02-21 15:06:35.961 1413-1900/? D/HIOMX_CORE: OMX_GetHandle :: enter!
02-21 15:06:35.961 1413-1900/? D/HIOMX_CORE: OMX_GetHandle :: component name:OMX.hisi.video.decoder !
02-21 15:06:35.961 1413-1900/? D/HIOMX_CORE: OMX_GetHandle :: prepare to load  libOMX.hisi.video.decoder.so
02-21 15:06:35.963 1413-1900/? D/HIOMX_CORE: OMX_GetHandle :: load  libOMX.hisi.video.decoder.so ok
02-21 15:06:35.976 1413-1900/? E/HISI_OMXVDEC: get_supported_profile_level(): ProfileIndex(48) exceed!
02-21 15:06:35.976 1413-3154/? E/HISI_OMXVDEC: get_extension_index: OMX.google.android.index.storeMetaDataInBuffers not implemented!
02-21 15:06:35.976 1413-3154/? E/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
02-21 15:06:35.977 1413-1413/? E/HISI_OMXVDEC: get_extension_index: OMX.google.android.index.prepareForAdaptivePlayback not implemented!
02-21 15:06:35.977 1413-1413/? W/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
02-21 15:06:35.977 1413-1900/? V/OMXNodeInstance: calling destroyComponentInstance
02-21 15:06:36.060 2488-16707/? E/VPP_DLNA_LOG: [VPPDLNA]:SSDP recvd bad msg code = 1
02-21 15:06:36.061 2488-15541/? E/VPP_DLNA_LOG: [VPPDLNA]:SSDP recvd bad msg code = 1
02-21 15:06:36.063 2488-14440/? E/VPP_DLNA_LOG: [VPPDLNA]:SSDP recvd bad msg code = 1
02-21 15:06:36.155 2488-17154/? E/VPP_DLNA_LOG: [VPPDLNA]:SSDP recvd bad msg code = 1
02-21 15:06:36.157 2488-18160/? E/VPP_DLNA_LOG: [VPPDLNA]:SSDP recvd bad msg code = 1
02-21 15:06:36.159 2488-15681/? E/VPP_DLNA_LOG: [VPPDLNA]:SSDP recvd bad msg code = 1
02-21 15:06:36.470 1413-1900/? V/OMXNodeInstance: destroyComponentInstance returned err 0
02-21 15:06:36.470 1413-1900/? V/OMXNodeInstance: OMXNodeInstance going away.
02-21 15:06:36.472 18306-18324/? I/tv.danmaku.ijk.media.player.IjkMediaPlayer: candidate codec: OMX.hisi.video.decoder rank=700
02-21 15:06:36.472 18306-18324/? I/OMXClient: Using client-side OMX mux.
02-21 15:06:36.473 1413-1413/? D/HIOMX_CORE: OMX_GetHandle :: enter!
02-21 15:06:36.473 1413-1413/? D/HIOMX_CORE: OMX_GetHandle :: component name:OMX.hisi.video.decoder !
02-21 15:06:36.473 1413-1413/? D/HIOMX_CORE: OMX_GetHandle :: prepare to load  libOMX.hisi.video.decoder.so
02-21 15:06:36.474 1413-1413/? D/HIOMX_CORE: OMX_GetHandle :: load  libOMX.hisi.video.decoder.so ok
02-21 15:06:36.487 1413-1413/? E/HISI_OMXVDEC: get_supported_profile_level(): ProfileIndex(48) exceed!
02-21 15:06:36.488 1413-2590/? E/HISI_OMXVDEC: get_extension_index: OMX.google.android.index.storeMetaDataInBuffers not implemented!
02-21 15:06:36.488 1413-2590/? E/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
02-21 15:06:36.488 1413-3154/? E/HISI_OMXVDEC: get_extension_index: OMX.google.android.index.prepareForAdaptivePlayback not implemented!
02-21 15:06:36.488 1413-3154/? W/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
02-21 15:06:36.488 1413-1413/? V/OMXNodeInstance: calling destroyComponentInstance
02-21 15:06:36.982 1413-1413/? V/OMXNodeInstance: destroyComponentInstance returned err 0
02-21 15:06:36.982 1413-1413/? V/OMXNodeInstance: OMXNodeInstance going away.
02-21 15:06:36.984 18306-18324/? I/IjkMediaCodecInfo:  High Profile Level 51 (8,32768)
02-21 15:06:36.984 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/mp4v-es
02-21 15:06:36.984 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.mp3.decoder
02-21 15:06:36.985 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/mpeg
02-21 15:06:36.985 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.amrnb.decoder
02-21 15:06:36.985 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/3gpp
02-21 15:06:36.985 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.amrwb.decoder
02-21 15:06:36.986 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/amr-wb
02-21 15:06:36.986 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.aac.decoder
02-21 15:06:36.986 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/mp4a-latm
02-21 15:06:36.987 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.g711.alaw.decoder
02-21 15:06:36.988 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/g711-alaw
02-21 15:06:36.988 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.g711.mlaw.decoder
02-21 15:06:36.989 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/g711-mlaw
02-21 15:06:36.989 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.vorbis.decoder
02-21 15:06:36.989 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/vorbis
02-21 15:06:36.989 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.gsm.decoder
02-21 15:06:36.990 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/gsm
02-21 15:06:36.990 1914-1965/? D/WifiStateMachine: handleMessage: E msg.what=131155
02-21 15:06:36.990 1914-1965/? D/WifiStateMachine: processMsg: ConnectedState
02-21 15:06:36.991 1914-1965/? D/WifiStateMachine: processMsg: L2ConnectedState
02-21 15:06:36.991 1914-1965/? D/WifiHW: wifi command = IFNAME=wlan0 SIGNAL_POLL
02-21 15:06:36.991 2112-2112/? D/wpa_supplicant: RX ctrl_iface - hexdump(len=11): 53 49 47 4e 41 4c 5f 50 4f 4c 4c
02-21 15:06:36.991 2112-2112/? D/wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
02-21 15:06:36.991 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.mpeg4.decoder
02-21 15:06:36.991 2112-2112/? D/wpa_supplicant: nl80211: survey data missing!
02-21 15:06:36.992 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/mp4v-es
02-21 15:06:36.992 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.h263.decoder
02-21 15:06:36.992 1914-1965/? D/WifiStateMachine: handleMessage: X
02-21 15:06:36.992 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/3gpp
02-21 15:06:36.992 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.h264.decoder
02-21 15:06:36.992 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/avc
02-21 15:06:36.993 18306-18324/? I/tv.danmaku.ijk.media.player.IjkMediaPlayer: candidate codec: OMX.google.h264.decoder rank=200
02-21 15:06:36.993 18306-18324/? I/OMXClient: Using client-side OMX mux.
02-21 15:06:36.995 18306-18324/? D/HIOMX_CORE: OMX_Init :: enter!
02-21 15:06:36.995 18306-18324/? D/HIOMX_CORE: OMX_Init :: exit!
02-21 15:06:36.995 18306-18324/? D/HIOMX_CORE: OMX_ComponentNameEnum :: g_ComponentTable[0].name: OMX.hisi.video.decoder 
02-21 15:06:36.995 18306-18324/? D/HIOMX_CORE: OMX_ComponentNameEnum :: g_ComponentTable[1].name: OMX.hisi.video.encoder 
02-21 15:06:37.003 18306-18324/? E/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
02-21 15:06:37.003 18306-18324/? W/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
02-21 15:06:37.003 18306-18324/? V/OMXNodeInstance: calling destroyComponentInstance
02-21 15:06:37.004 18306-18324/? V/OMXNodeInstance: destroyComponentInstance returned err 0
02-21 15:06:37.005 18306-18324/? V/OMXNodeInstance: OMXNodeInstance going away.
02-21 15:06:37.006 18306-18324/? I/IjkMediaCodecInfo:  Unknown Profile Level 0 (0,0)
02-21 15:06:37.006 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.vp8.decoder
02-21 15:06:37.006 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/x-vnd.on2.vp8
02-21 15:06:37.006 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.vp9.decoder
02-21 15:06:37.006 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: video/x-vnd.on2.vp9
02-21 15:06:37.007 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.hisi.video.encoder
02-21 15:06:37.007 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.h263.encoder
02-21 15:06:37.007 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.amrnb.encoder
02-21 15:06:37.007 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.amrwb.encoder
02-21 15:06:37.008 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.aac.encoder
02-21 15:06:37.008 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.flac.encoder
02-21 15:06:37.008 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.vp8.encoder
02-21 15:06:37.008 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: AACEncoder
02-21 15:06:37.008 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:   found codec: OMX.google.raw.decoder
02-21 15:06:37.009 18306-18324/? D/tv.danmaku.ijk.media.player.IjkMediaPlayer:     mime: audio/raw
02-21 15:06:37.009 18306-18324/? I/tv.danmaku.ijk.media.player.IjkMediaPlayer: selected codec: OMX.hisi.video.decoder rank=700
02-21 15:06:37.009 18306-18324/? D/IJKMEDIA: SDL_AMediaCodecJava_createByCodecName
02-21 15:06:37.010 18306-18347/? I/OMXClient: Using client-side OMX mux.
02-21 15:06:37.011 1413-1900/? D/HIOMX_CORE: OMX_GetHandle :: enter!
02-21 15:06:37.011 1413-1900/? D/HIOMX_CORE: OMX_GetHandle :: component name:OMX.hisi.video.decoder !
02-21 15:06:37.011 1413-1900/? D/HIOMX_CORE: OMX_GetHandle :: prepare to load  libOMX.hisi.video.decoder.so
02-21 15:06:37.013 1413-1900/? D/HIOMX_CORE: OMX_GetHandle :: load  libOMX.hisi.video.decoder.so ok
02-21 15:06:37.019 18306-18324/? D/IJKMEDIA: SDL_AMediaCodecJava_init
02-21 15:06:37.019 18306-18324/? D/IJKMEDIA: SDL_AMediaCodec_increaseReference(): ref=1
02-21 15:06:37.019 18306-18324/? D/IJKMEDIA: SDL_AMediaCodecJava_configure_surface
02-21 15:06:37.019 18306-18324/? E/IJKMEDIA: configure acodec:0x1d200466 format:0x1d200452: surface:0x1d20045e
02-21 15:06:37.020 1413-2590/? E/HISI_OMXVDEC: get_extension_index: OMX.google.android.index.storeMetaDataInBuffers not implemented!
02-21 15:06:37.020 1413-2590/? E/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
02-21 15:06:37.020 18306-18347/? E/ACodec: [OMX.hisi.video.decoder] storeMetaDataInBuffers failed w/ err -2147483648
02-21 15:06:37.022 18306-18324/? D/IJKMEDIA: SDL_AMediaCodecJava_start
02-21 15:06:37.038 1413-18348/? D/HISI_OMXVDEC: [OmxState] Loaded --> Idle_Pending
02-21 15:06:37.138 1413-1900/? D/HISI_OMXVDEC: [OmxState] Idle_Pending --> Idle
02-21 15:06:37.138 18306-18324/? I/IJKMEDIA: reconfigure_codec_l:new acodec: 0x4bdbb5a0
02-21 15:06:37.138 18306-18324/? D/IJKMEDIA: SDL_AMediaCodec_increaseReference(): ref=2
02-21 15:06:37.138 18306-18324/? I/IJKMEDIA: VideoCodec: MediaCodec, OMX.hisi.video.decoder
02-21 15:06:37.139 18306-18324/? W/IJKMEDIA: fps: 23.976037 (too high)
02-21 15:06:37.139 18306-18324/? W/IJKMEDIA: fps: 23.976024 (too high)
02-21 15:06:37.139 18306-18353/? I/IJKMEDIA: SDL_RunThread: [18353] ff_video_dec
02-21 15:06:37.139 18306-18322/? D/IJKMEDIA: FFP_MSG_VIDEO_SIZE_CHANGED: 4096, 2048
02-21 15:06:37.139 18306-18322/? D/IJKMEDIA: FFP_MSG_SAR_CHANGED: 1, 1
02-21 15:06:37.139 18306-18322/? D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_PREPARED
02-21 15:06:37.139 18306-18322/? D/IJKMEDIA: FFP_MSG_PREPARED:
02-21 15:06:37.139 18306-18354/? I/IJKMEDIA: SDL_RunThread: [18354] amediacodec_input_thread
02-21 15:06:37.140 18306-18306/? D/IJKMEDIA: IjkMediaPlayer_start
02-21 15:06:37.140 18306-18306/? D/IJKMEDIA: ijkmp_start()
02-21 15:06:37.140 18306-18306/? D/IJKMEDIA: ijkmp_start()=0
02-21 15:06:37.140 18306-18322/? D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
02-21 15:06:37.141 1413-18348/? D/HISI_OMXVDEC: [OmxState] Idle --> Executing_Pending
02-21 15:06:37.142 18306-18327/? D/IJKMEDIA: avcodec/Audio: first frame decoded
02-21 15:06:37.142 1413-18348/? D/HISI_OMXVDEC: [OmxState] Execute_Pending --> Executing
02-21 15:06:37.142 18306-18322/? D/IJKMEDIA: FFP_MSG_AUDIO_RENDERING_START:
02-21 15:06:37.177 18306-18310/? D/dalvikvm: GC_CONCURRENT freed 157K, 7% free 3405K/3632K, paused 9ms+4ms, total 34ms
02-21 15:06:37.241 18306-18354/? D/IJKMEDIA: ffpipeline_set_surface_need_reconfigure_l(0)
02-21 15:06:37.241 18306-18354/? I/IJKMEDIA: feed_input_buffer: same surface, reuse previous surface
02-21 15:06:37.313 1413-18348/? E/HISI_OMXVDEC: [EP] DynamicResourcesUnavailable ERROR
02-21 15:06:37.313 18306-18347/? E/ACodec: [OMX.hisi.video.decoder] ERROR(0x8000101e)
02-21 15:06:37.313 18306-18346/? E/MediaCodec: Codec reported an error. (omx error 0x8000101e, internalError -2147483648)
02-21 15:06:37.314 18306-18353/? W/System.err: java.lang.IllegalStateException
02-21 15:06:37.314 18306-18353/? W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
02-21 15:06:37.314 18306-18353/? W/System.err:     at dalvik.system.NativeStart.run(Native Method)
02-21 15:06:37.314 18306-18353/? I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
02-21 15:06:37.315 18306-18354/? W/System.err: java.lang.IllegalStateException
02-21 15:06:37.315 18306-18354/? W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(Native Method)
02-21 15:06:37.317 18306-18354/? W/System.err:     at dalvik.system.NativeStart.run(Native Method)
02-21 15:06:37.317 18306-18354/? E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
02-21 15:06:37.318 18306-18354/? W/System.err: java.lang.IllegalStateException
02-21 15:06:37.319 18306-18354/? W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(Native Method)
02-21 15:06:37.319 18306-18354/? W/System.err:     at dalvik.system.NativeStart.run(Native Method)
02-21 15:06:37.319 18306-18354/? E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
02-21 15:06:37.320 18306-18354/? W/System.err: java.lang.IllegalStateException
02-21 15:06:37.321 18306-18354/? W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(Native Method)
02-21 15:06:37.321 18306-18354/? W/System.err:     at dalvik.system.NativeStart.run(Native Method)
之后无限抛出IllegalStateException异常
```

**Comment by teddyla** [comment]
hisi vdec issue.
02-21 15:06:37.313 1413-18348/? E/HISI_OMXVDEC: [EP] DynamicResourcesUnavailable ERROR
u could ask their fae for help or u search these msg from their release android source code

**Comment by zengyunpeng** [comment]
这个问题有解决吗

**Comment by liulei9385** [comment]
mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
                mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-avc", 1);
                mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-mpeg2", 1);
                mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-mpeg4", 1);
                mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-hevc", 1);
                mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 1);
                mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-handle-resolution-change", 1);
