### ISSUE TITLE
UnsatisfiedLinkError when ijkplayer and javacv both exist in one project

### ISSUE THREAD

**Issue by cccqcn** [Bilibili/ijkplayer#2733]
I'm facing almost the same problem as this issue:
https://github.com/Bilibili/ijkplayer/issues/1148 
The difference is: I'm not getting the ClassNotFoundException, but getting `java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil`. And currently the version of both ijkplayer and javacv are newer. 

To simplify the question, I just add one line in the project and the error occurs. 
`FFmpegFrameRecorder ff = new FFmpegFrameRecorder("", 1, 1, 1);`

The gradle:

```
    compile group: 'org.bytedeco', name: 'javacv', version: '1.3'
    compile group: 'org.bytedeco', name: 'javacpp', version: '1.3'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0-1.3', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0-1.3', classifier: 'android-x86'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.2.1-1.3', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.2.1-1.3', classifier: 'android-x86'

    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.7.7.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.7.7.1'
```
To successfully run javacv the gradle also include:

```
packagingOptions {
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.xml'
    }
```

When only add the javacv, it's fine. But when both of the javacv and the ffmpeg added, the problem occurs. 
I tried compiling different version in the gradle, but there is no help.

Here is the log:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.ijkapplication, PID: 31127
                  java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.Class.forName(Class.java:324)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:585)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:530)
                      at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1694)
                      at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:152)
                      at com.ijkapplication.MainActivity.onCreate(MainActivity.java:26)
                      at android.app.Activity.performCreate(Activity.java:6904)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                      at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:7406)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```
Anyone has any idea solving the problem?
JavaCV link: https://github.com/bytedeco/javacv

**Comment by cccqcn** [comment]
Solved after read these issues:
https://github.com/bytedeco/javacv/issues/310
https://github.com/bytedeco/javacv/issues/133

Now the core gradle changes to:
```
    compile group: 'org.bytedeco', name: 'javacv', version: '1.3'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.7.7.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.7.7.1'
```
only one line of javacv, but put the ".so" files in both opencv-android-arm.jar and ffmpeg-android-arm.jar in libs folder. Now there is no .jar file in the libs folder.

Also in gradle:
```
sourceSets.main {
        jniLibs.srcDirs 'libs'
        jni.srcDirs = [] 
    }
```
It's working now.
