### ISSUE TITLE
硬解失败以后，释放时异常退出

### ISSUE THREAD

**Issue by aslgd** [Bilibili/ijkplayer#2842]
用的meizu M463C，硬解2K以上的视频时，没有画面，结束播放release player时异常退出

请问有没有解决方案？

I/DEBUG   (  253): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

I/DEBUG   (  253): Build fingerprint: 'Meizu/meizu_m1note/m1note:4.4.4/KTU84P/m71c.Flyme_OS_4.2.20150312033938:user/release-keys'

I/DEBUG   (  253): Revision: '0'

I/DEBUG   (  253): pid: 17768, tid: 17795, name: UnityMain  >>> com.picovr.wing:player <<<

I/DEBUG   (  253): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000510

I/ThermalEngine( 2160): ACTION: CLUSTER - Setting CLUSTER[1] to 1344000

I/ThermalEngine( 2160): ACTION: CLUSTER - Setting CLUSTER[0] to 1113600

I/DEBUG   (  253):     r0 00000001  r1 400aee00  r2 00000000  r3 00000500

I/DEBUG   (  253):     r4 822d3a70  r5 833b46fc  r6 00000000  r7 834b4a68

I/DEBUG   (  253):     r8 822aa240  r9 82200510  sl 00001718  fp 000016d8

I/DEBUG   (  253):     ip 832b3c3c  sp 76fe78e0  lr 8241d187  pc 8241d18c  cpsr 200f0030

I/DEBUG   (  253):     d0  61657220726f6664  d1  757328656361665f

I/DEBUG   (  253):     d2  2f6e6f6d6d6f6374  d3  2f656d69746e7569

I/DEBUG   (  253):     d4  676e457974696e55  d5  6775626544656e69

I/DEBUG   (  253):     d6  73676e69646e6942  d7  7070632e6e65672e

I/DEBUG   (  253):     d8  0000000000000000  d9  0000000000000000

I/DEBUG   (  253):     d10 0000000000000000  d11 0000000000000000

I/DEBUG   (  253):     d12 0000000000000000  d13 0000000000000000

I/DEBUG   (  253):     d14 0000000000000000  d15 0000000000000000

I/DEBUG   (  253):     d16 40388c79a3f06000  d17 0000000000000000

I/DEBUG   (  253):     d18 be20c45f3cab7575  d19 000000003fd527d2

I/DEBUG   (  253):     d20 be20c45f3cab7575  d21 000000003fd527d2

I/DEBUG   (  253):     d22 3f6afcbfbecb174a  d23 000000003c15e871

I/DEBUG   (  253):     d24 ffffffffffffffff  d25 ffffffffffffffff

I/DEBUG   (  253):     d26 be20c45f41127af1  d27 000000004465816c

I/DEBUG   (  253):     d28 3f6afcbf3ecb174a  d29 000000003c15e871

I/DEBUG   (  253):     d30 bf368be33c04c3b8  d31 000000003ec1c61e

I/DEBUG   (  253):     scr 6000001b

I/DEBUG   (  253): 

I/DEBUG   (  253): backtrace:

I/DEBUG   (  253):     #00  pc 000a518c  /data/app-lib/com.picovr.wing-1/libijkffmpeg.so (avcodec_close+19)

I/DEBUG   (  253):     #01  pc 000a5183  /data/app-lib/com.picovr.wing-1/libijkffmpeg.so (avcodec_close+10)

I/DEBUG   (  253): 

I/DEBUG   (  253): stack:

I/DEBUG   (  253):          76fe78a0  400af000  /system/lib/libc.so

I/DEBUG   (  253):          76fe78a4  822088d0  

I/DEBUG   (  253):          76fe78a8  836e8fc8  

I/DEBUG   (  253):          76fe78ac  00000000  

I/DEBUG   (  253):          76fe78b0  00000100  

I/DEBUG   (  253):          76fe78b4  836e8fd0  

I/DEBUG   (  253):          76fe78b8  400af000  /system/lib/libc.so

I/DEBUG   (  253):          76fe78bc  8393c020  

I/DEBUG   (  253):          76fe78c0  400af000  /system/lib/libc.so

I/DEBUG   (  253):          76fe78c4  8393c020  

I/DEBUG   (  253):          76fe78c8  400af000  /system/lib/libc.so

I/DEBUG   (  253):          76fe78cc  833b4668  

I/DEBUG   (  253):          76fe78d0  00000000  

I/DEBUG   (  253):          76fe78d4  0000000c  

I/DEBUG   (  253):          76fe78d8  df0027ad  

I/DEBUG   (  253):          76fe78dc  00000000  

I/DEBUG   (  253):     #00  76fe78e0  822d3a70  

I/DEBUG   (  253):          ........  ........

I/DEBUG   (  253):     #01  76fe78e0  822d3a70  

I/DEBUG   (  253):          76fe78e4  833b46fc  

I/DEBUG   (  253):          76fe78e8  00000000  

I/DEBUG   (  253):          76fe78ec  825db0a9  /data/app-lib/com.picovr.wing-1/libijkffmpeg.so (avcodec_free_context+14)

I/DEBUG   (  253):          76fe78f0  00000000  

I/DEBUG   (  253):          76fe78f4  833b4668  

I/DEBUG   (  253):          76fe78f8  833b3020  

I/DEBUG   (  253):          76fe78fc  832985d3  /data/app-lib/com.picovr.wing-1/libijkplayer.so

I/DEBUG   (  253):          76fe7900  822aa020  

I/DEBUG   (  253):          76fe7904  00001588  

I/DEBUG   (  253):          76fe7908  b277fb8b  

I/DEBUG   (  253):          76fe790c  00000001  

I/DEBUG   (  253):          76fe7910  833b3020  

I/DEBUG   (  253):          76fe7914  821d4a80  

I/DEBUG   (  253):          76fe7918  400b3394  

I/DEBUG   (  253):          76fe791c  834b4a68

**Comment by aslgd** [comment]
设置解码器时候报的错误

D/IJKMEDIA(17768): SDL_AMediaCodecJava_configure_surface

E/IJKMEDIA(17768): configure acodec:0x1d6006fe format:0x1d2006ea: surface:0x1d2006f6

I/ACodec  (17768): DRC Mode: Dynamic Buffer Mode

E/OMX-VDEC-1080P(  259): Set Resolution failed

E/OMX-VDEC-1080P(  259): Setting buffer requirements (format) failed -1

E/OMX-VDEC-1080P(  259): Setting buffer requirements (reqbufs) failed -1

E/OMX-VDEC-1080P(  259): set_parameter: Error: 0x80001000, setting param 0x2000001

E/ACodec  (17768): [OMX.qcom.video.decoder.avc] configureCodec returning error -2147483648

E/MediaCodec(17768): Codec reported an error. (omx error 0x80001001, internalError -2147483648)

W/System.err(17768): java.lang.IllegalStateException

W/System.err(17768): 	at android.media.MediaCodec.native_configure(Native Method)

W/System.err(17768): 	at android.media.MediaCodec.configure(MediaCodec.java:262)

W/System.err(17768): 	at dalvik.system.NativeStart.run(Native Method)

E/IJKMEDIA(17768): reconfigure_codec_l:configure_surface: failed

D/IJKMEDIA(17768): SDL_AMediaCodec_decreaseReference(): ref=0

I/IJKMEDIA(17768): SDL_AMediaCodecJava_delete
