### ISSUE TITLE
报错问题求帮忙看看如何解决

### ISSUE THREAD

**Issue by duckzq** [Bilibili/ijkplayer#2868]
03-20 21:05:18.095 7831-7848/com.baicells.app E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                            at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                            at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:862)

**Comment by 0ct0cat** [comment]
pls close the java progurad.
