### ISSUE TITLE
No implementation found for void com.example.mylibrary.example.play.IjkMediaPlayer.native_profileBegin(java.lang.String) (tried Java_com_example_mylibrary_example_play_IjkMediaPlayer_native_1profileBegin and Java_com_example_mylibrary_example_play_IjkMediaPlayer_native_1profileBegin__Ljava_lang_String_2)

### ISSUE THREAD

**Issue by Jeffery336699** [Bilibili/ijkplayer#2882]
```
mMSettings = new Settings(this);
        videoView = (IjkVideoView) findViewById(R.id.videoview);
        // init player
        IjkMediaPlayer.loadLibrariesOnce(null);
        IjkMediaPlayer.native_profileBegin("libijkplayer.so");
//        videoView.setVideoURI(Uri.parse("http://106.36.45.36/live.aishang.ctlcdn.com/00000110240001_1/encoder/1/playlist.m3u8"));
        videoView.setVideoURI(Uri.parse("http://main.gslb.ku6.com/s1/hi6HCS-FCnkJMBbogyQwBQ../" +
                "1469508444312/0b91e5c057527b3d993ccea661d798d0/1490260595597/v160/16/" +
                "76/f481427e4c0b2aa4372c14297dbb5c0b-f4v-h264-aac-869-32-193283.0-21938064" +
                "-1469420316036-42e8e3c167c347eec8913cd47e954846-1-00-00-00.f4v?rate=400"));
        videoView.setOnPreparedListener(new IMediaPlayer.OnPreparedListener() {
            @Override
            public void onPrepared(IMediaPlayer mp) {
                videoView.start();
            }
        });
```
```
FATAL EXCEPTION: main
                                                                                Process: com.example.ling.mediaplaydemo, PID: 24629
                                                                                java.lang.UnsatisfiedLinkError: No implementation found for void com.example.mylibrary.example.play.IjkMediaPlayer.native_profileBegin(java.lang.String) (tried Java_com_example_mylibrary_example_play_IjkMediaPlayer_native_1profileBegin and Java_com_example_mylibrary_example_play_IjkMediaPlayer_native_1profileBegin__Ljava_lang_String_2)
                                                                                    at com.example.mylibrary.example.play.IjkMediaPlayer.native_profileBegin(Native Method)
                                                                                    at com.example.ling.mediaplaydemo.MainActivity.onCreate(MainActivity.java:25)
                                                                                    at android.app.Activity.performCreate(Activity.java:6127)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2617)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
                                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:187)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                    at android.os.Looper.loop(Looper.java:194)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5869)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
```
请问大神，播放一个在线视频该怎么播放？

**Comment by Jeffery336699** [comment]
this is mine problem,thanks
