### ISSUE TITLE
onControlResolveSegmentCount jni unsatisfactory link error

### ISSUE THREAD

**Issue by wangcan26** [Bilibili/ijkplayer#2925]
Hello all:
  When i integrate the ijkplayer with my own project, it reports a error as follow:

 E/IJKMEDIA: GetStaticMethodID failed: onControlResolveSegmentCount
                                             
                                             --------- beginning of crash
   java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.antvr.market-2/lib/arm/libijkplayer.so"
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                       at java.lang.System.loadLibrary(System.java:1076)
                                                       at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:174)
                                                       at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:187)
                                                       at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:226)
                                                       at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:222)
                                                       at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:213)

however , some projects integrate the ijkplayer without any errors;

**Comment by wangcan26** [comment]
I find throughout the ijkplayer on github with no any function named as onControlResolveSegmentCount

but i found this :
http://www.programcreek.com/java-api-examples/index.php?source_dir=MD-BiliBili-master/MDBilibili/player-java/src/main/java/tv/danmaku/ijk/media/player/IjkMediaPlayer.java

Any differences between the project of the link and the one on github
