### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed:

### ISSUE THREAD

**Issue by EvilsoulM** [bilibili/ijkplayer#2936]
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: "/lib/arm/libijkplayer.so" has bad ELF magic
       at java.lang.Runtime.loadLibrary(Runtime.java:375)
       at java.lang.System.loadLibrary(System.java:988)
       at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:174)
       at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:187)
       at com.ss.android.ugc.aweme.video.AsyncPlayer$PlayHandler.(AsyncPlayer.java:186)

版本 compile 'tv.danmaku.ijk.media:ijkplayer-java:0.7.7.1'

只有在某些机型会奔溃，相同机型有的有问题有的没问题。。,虽然量不大~

**Comment by lrannn** [comment]
亲解决了吗

**Comment by Guess0625** [comment]
请问这个问题最后怎么解决的？
