### ISSUE TITLE
Explicit termination method 'release' not called

### ISSUE THREAD

**Issue by niufeihu** [Bilibili/ijkplayer#3043]
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                             java.lang.Throwable: Explicit termination method 'release' not called
                                                                 at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                 at android.view.Surface.setNativeObjectLocked(Surface.java:459)
                                                                 at android.view.Surface.<init>(Surface.java:145)
                                                                 at ijkplayer.jiaxing.info.widget.media.TextureRenderView$InternalSurfaceHolder.openSurface(TextureRenderView.java:195)
                                                                 at ijkplayer.jiaxing.info.widget.media.TextureRenderView$InternalSurfaceHolder.bindToMediaPlayer(TextureRenderView.java:168)
                                                                 at ijkplayer.jiaxing.info.widget.media.IjkVideoView.bindSurfaceHolder(IjkVideoView.java:668)
                                                                 at ijkplayer.jiaxing.info.widget.media.IjkVideoView.openVideo(IjkVideoView.java:351)
                                                                 at ijkplayer.jiaxing.info.widget.media.IjkVideoView.access$2800(IjkVideoView.java:61)
                                                                 at ijkplayer.jiaxing.info.widget.media.IjkVideoView$9.onSurfaceCreated(IjkVideoView.java:717)
                                                                 at ijkplayer.jiaxing.info.widget.media.TextureRenderView$SurfaceCallback.onSurfaceTextureAvailable(TextureRenderView.java:266)
                                                                 at android.view.TextureView.getHardwareLayer(TextureView.java:368)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15161)
                                                                 at android.view.View.draw(View.java:15957)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15179)
                                                                 at android.view.View.draw(View.java:15957)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                 at android.view.View.draw(View.java:16190)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15184)
                                                                 at android.view.View.draw(View.java:15957)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                 at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1377)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15179)
                                                                 at android.view.View.draw(View.java:15957)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15179)
                                                                 at android.view.View.draw(View.java:15957)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15179)
                                                                 at android.view.View.draw(View.java:15957)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15179)
                                                                 at android.view.View.draw(View.java:15957)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15179)
                                                                 at android.view.View.draw(View.java:15957)
                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                 at android.view.View.draw(View.java:16190)
                                                                 at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2946)
                                                                 at android.view.View.updateDisplayListIfDirty(View.java:15184)
                                                                 at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
                                                                 at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
                                                                 at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
                                                                 at android.view.ViewRootImpl.draw(ViewRootImpl.java:2623)
                                                                 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2442)
                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2075)
                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                             	at android.view.Choreographer.doFrame(Cho

have someone has the same problem?

**Comment by iflove** [comment]
没人？
