### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by maoaixianyu** [Bilibili/ijkplayer#3086]
Some platform of android phone have this crash for
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/some/tinker/patch-4f6c5b6e/dex/classes.dex.jar", zip file "/data/data/csome/tinker/patch-4f6c5b6e/dex/classes2.dex.jar", zip file "/data/data/some/tinker/patch-4f6c5b6e/dex/test.dex.jar", zip file "/data/app/some-1.apk", zip file "/data/data/com.boxfish.stu/code_cache/secondary-dexes/some-1.apk.classes2.zip", zip file "/data/data/some/code_cache/secondary-dexes/some-1.apk.classes3.zip"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libijkffmpeg.so"
       at java.lang.Runtime.loadLibrary(Runtime.java:373)
       at java.lang.System.loadLibrary(System.java:540)
       at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:175)
       at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:186)

please help me

**Comment by zhanggao** [comment]
每种架构的文件夹里的so个数必须一致。
安装的时候手机会选择一个最适合自己的so文件夹。
解压自己apk看哪个缺少了。
