### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by HappyMiao** [Bilibili/ijkplayer#3170]
这样使用 
mIjkVideoView = (IjkVideoView) findViewById(R.id.mIjkVideoView);
mIjkVideoView.setVideoPath("rtmp://live.hkstv.hk.lxdns.com/live/hks");
mIjkVideoView.start();

运行报错了 
NullPointerException: Attempt to invoke virtual method 'void tv.danmaku.ijk.media.example.widget.media.InfoHudViewHolder.updateLoadCost(long)' on a null object reference
at  tv.danmaku.ijk.media.example.widget.media.IjkVideoView$2.onPrepared(IjkVideoView.java:414)
                                                                 at tv.danmaku.ijk.media.player.AbstractMediaPlayer.notifyOnPrepared(AbstractMediaPlayer.java:80)
                                                                 at tv.danmaku.ijk.media.player.IjkMediaPlayer$EventHandler.handleMessage(IjkMediaPlayer.java:957)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:135)

是我使用方式不对嘛？谢谢百忙中帮忙看以下，谢谢了

**Comment by raymond1012** [comment]
NullPointerException

**Comment by yanchengdeng** [comment]
我也遇到同样的问题  ，这样的使用方式 不正确吗？

**Comment by yanchengdeng** [comment]
ok    需要设置 ijkPlayer.setHudView(mHudView);

**Comment by czfyzzf** [comment]
同样的问题，搞了很久找不到方法
