### ISSUE TITLE
退出播放的时候释放资源崩溃

### ISSUE THREAD

**Issue by Chenqi105** [Bilibili/ijkplayer#3171]
4.4 手机播放视频，播放，切换后台暂停播放，在最前端的时候接着播放。退出播放崩溃
logjava.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
	at android.graphics.SurfaceTexture.detachFromGLContext(SurfaceTexture.java:195)
	at android.view.TextureView.destroySurface(TextureView.java:232)
	at android.view.TextureView.destroyHardwareResources(TextureView.java:344)
	at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2348)
	at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2355)
	at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2355)
	at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2355)
	at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2355)
	at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2355)
	at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2355)
	at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2355)
	at android.view.HardwareRenderer$Gl20Renderer.access$800(HardwareRenderer.java:1932)
	at android.view.HardwareRenderer$Gl20Renderer$2.run(HardwareRenderer.java:2340)
	at android.view.HardwareRenderer$Gl20Renderer.safelyRun(HardwareRenderer.java:2291)
	at android.view.HardwareRenderer$Gl20Renderer.destroyHardwareResources(HardwareRenderer.java:2334)
	at android.view.ViewRootImpl.destroyHardwareResources(ViewRootImpl.java:683)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1300)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1058)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5974)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
	at android.view.Choreographer.doCallbacks(Choreographer.java:593)
	at android.view.Choreographer.doFrame(Choreographer.java:562)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5315)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by raymond1012** [comment]
大概率是上层使用TextureView问题

**Comment by yingzi2011** [comment]
我也遇到了这个问题，不知道怎么解决

**Comment by lihanguang** [comment]
同遇到，请问有解决嘛？
