### ISSUE TITLE
重命名so后部分机型报错，请问是什么原因？

### ISSUE THREAD

**Issue by zhousuqiang** [Bilibili/ijkplayer#3211]
so重命名后个别机型会报错；
初始化代码如下：
IjkMediaPlayer.loadLibrariesOnce(new IjkLibLoader() {
                @Override
                public void loadLibrary(String libName) {
                    try {
                        System.loadLibrary("lexue"+libName);
                    } catch (UnsatisfiedLinkError e) {
                        e.printStackTrace();
                    } catch (SecurityException e) {
                        e.printStackTrace();
                    }
                }
            });
IjkMediaPlayer.native_profileBegin("liblexueijkplayer.so");

报错信息如下：
01-01 08:48:10.971 E/art     (20158): dlopen("/data/app/com.huan.edu.tvplayer.example2-1/lib/arm/liblexueijkplayer.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "SDL_SpeedSamplerReset" referenced by "liblexueijkplayer.so"...
01-01 08:48:10.971 D/ControlCenterWorkThread(19429): refreshDevices...
01-01 08:48:10.971 W/System.err(20158): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "SDL_SpeedSamplerReset" referenced by "liblexueijkplayer.so"...
01-01 08:48:10.972 D/ControlCenterWorkThread(19429): Mcontroller controlCenterWorkThread MCstartSearch
01-01 08:48:10.979 W/System.err(20158): 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
01-01 08:48:10.979 W/System.err(20158): 	at java.lang.System.loadLibrary(System.java:988)
01-01 08:48:10.979 W/System.err(20158): 	at com.huan.edu.tvplayer.utils.EPLibraryUtil$1$1.loadLibrary(EPLibraryUtil.java:88)
01-01 08:48:10.979 W/System.err(20158): 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:176)
01-01 08:48:10.979 W/System.err(20158): 	at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:83)
01-01 08:48:10.979 W/System.err(20158): 	at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:58)
01-01 08:48:10.979 W/System.err(20158): 	at android.os.AsyncTask.finish(AsyncTask.java:636)
01-01 08:48:10.979 W/System.err(20158): 	at android.os.AsyncTask.access$500(AsyncTask.java:177)
01-01 08:48:10.979 W/System.err(20158): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
01-01 08:48:10.979 W/System.err(20158): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-01 08:48:10.979 W/System.err(20158): 	at android.os.Looper.loop(Looper.java:135)
01-01 08:48:10.979 W/System.err(20158): 	at android.app.ActivityThread.main(ActivityThread.java:5275)
01-01 08:48:10.979 W/System.err(20158): 	at java.lang.reflect.Method.invoke(Native Method)
01-01 08:48:10.979 W/System.err(20158): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-01 08:48:10.979 W/System.err(20158): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:932)
01-01 08:48:10.979 W/System.err(20158): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:727)

01-01 08:48:11.146 E/art     (20158): No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_profileBegin(java.lang.String) (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1profileBegin and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1profileBegin__Ljava_lang_String_2)
01-01 08:48:11.146 D/AndroidRuntime(20158): Shutting down VM
01-01 08:48:11.147 E/AndroidRuntime(20158): FATAL EXCEPTION: main
01-01 08:48:11.147 E/AndroidRuntime(20158): Process: com.huan.edu.tvplayer.example2, PID: 20158
01-01 08:48:11.147 E/AndroidRuntime(20158): java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_profileBegin(java.lang.String) (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1profileBegin and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1profileBegin__Ljava_lang_String_2)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_profileBegin(Native Method)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at com.huan.edu.tvplayer.widget.EduIjkVideoView.initVideoLib(EduIjkVideoView.java:172)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at com.huan.edu.tvplayer.EduPlayerFragment$2.onInitFinish(EduPlayerFragment.java:209)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:107)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:58)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at android.os.AsyncTask.finish(AsyncTask.java:636)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at android.os.AsyncTask.access$500(AsyncTask.java:177)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at android.os.Looper.loop(Looper.java:135)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at android.app.ActivityThread.main(ActivityThread.java:5275)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at java.lang.reflect.Method.invoke(Native Method)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:932)
01-01 08:48:11.147 E/AndroidRuntime(20158): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:727)

**Comment by drivedreams** [comment]
你的很清楚




发自网易邮箱大师
在2017年06月12日 15:58，owen 写道：

so重命名后个别机型会报错；
初始化代码如下：
IjkMediaPlayer.loadLibrariesOnce(new IjkLibLoader() {
@override
public void loadLibrary(String libName) {
try {
System.loadLibrary("lexue"+libName);
} catch (UnsatisfiedLinkError e) {
e.printStackTrace();
} catch (SecurityException e) {
e.printStackTrace();
}
}
});
IjkMediaPlayer.native_profileBegin("liblexueijkplayer.so");

报错信息如下：
01-01 08:48:10.971 E/art (20158): dlopen("/data/app/com.huan.edu.tvplayer.example2-1/lib/arm/liblexueijkplayer.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "SDL_SpeedSamplerReset" referenced by "liblexueijkplayer.so"...
01-01 08:48:10.971 D/ControlCenterWorkThread(19429): refreshDevices...
01-01 08:48:10.971 W/System.err(20158): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "SDL_SpeedSamplerReset" referenced by "liblexueijkplayer.so"...
01-01 08:48:10.972 D/ControlCenterWorkThread(19429): Mcontroller controlCenterWorkThread MCstartSearch
01-01 08:48:10.979 W/System.err(20158): at java.lang.Runtime.loadLibrary(Runtime.java:371)
01-01 08:48:10.979 W/System.err(20158): at java.lang.System.loadLibrary(System.java:988)
01-01 08:48:10.979 W/System.err(20158): at com.huan.edu.tvplayer.utils.EPLibraryUtil$1$1.loadLibrary(EPLibraryUtil.java:88)
01-01 08:48:10.979 W/System.err(20158): at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:176)
01-01 08:48:10.979 W/System.err(20158): at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:83)
01-01 08:48:10.979 W/System.err(20158): at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:58)
01-01 08:48:10.979 W/System.err(20158): at android.os.AsyncTask.finish(AsyncTask.java:636)
01-01 08:48:10.979 W/System.err(20158): at android.os.AsyncTask.access$500(AsyncTask.java:177)
01-01 08:48:10.979 W/System.err(20158): at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
01-01 08:48:10.979 W/System.err(20158): at android.os.Handler.dispatchMessage(Handler.java:102)
01-01 08:48:10.979 W/System.err(20158): at android.os.Looper.loop(Looper.java:135)
01-01 08:48:10.979 W/System.err(20158): at android.app.ActivityThread.main(ActivityThread.java:5275)
01-01 08:48:10.979 W/System.err(20158): at java.lang.reflect.Method.invoke(Native Method)
01-01 08:48:10.979 W/System.err(20158): at java.lang.reflect.Method.invoke(Method.java:372)
01-01 08:48:10.979 W/System.err(20158): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:932)
01-01 08:48:10.979 W/System.err(20158): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:727)

01-01 08:48:11.146 E/art (20158): No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_profileBegin(java.lang.String) (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1profileBegin and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1profileBegin__Ljava_lang_String_2)
01-01 08:48:11.146 D/AndroidRuntime(20158): Shutting down VM
01-01 08:48:11.147 E/AndroidRuntime(20158): FATAL EXCEPTION: main
01-01 08:48:11.147 E/AndroidRuntime(20158): Process: com.huan.edu.tvplayer.example2, PID: 20158
01-01 08:48:11.147 E/AndroidRuntime(20158): java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_profileBegin(java.lang.String) (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1profileBegin and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1profileBegin__Ljava_lang_String_2)
01-01 08:48:11.147 E/AndroidRuntime(20158): at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_profileBegin(Native Method)
01-01 08:48:11.147 E/AndroidRuntime(20158): at com.huan.edu.tvplayer.widget.EduIjkVideoView.initVideoLib(EduIjkVideoView.java:172)
01-01 08:48:11.147 E/AndroidRuntime(20158): at com.huan.edu.tvplayer.EduPlayerFragment$2.onInitFinish(EduPlayerFragment.java:209)
01-01 08:48:11.147 E/AndroidRuntime(20158): at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:107)
01-01 08:48:11.147 E/AndroidRuntime(20158): at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:58)
01-01 08:48:11.147 E/AndroidRuntime(20158): at android.os.AsyncTask.finish(AsyncTask.java:636)
01-01 08:48:11.147 E/AndroidRuntime(20158): at android.os.AsyncTask.access$500(AsyncTask.java:177)
01-01 08:48:11.147 E/AndroidRuntime(20158): at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
01-01 08:48:11.147 E/AndroidRuntime(20158): at android.os.Handler.dispatchMessage(Handler.java:102)
01-01 08:48:11.147 E/AndroidRuntime(20158): at android.os.Looper.loop(Looper.java:135)
01-01 08:48:11.147 E/AndroidRuntime(20158): at android.app.ActivityThread.main(ActivityThread.java:5275)
01-01 08:48:11.147 E/AndroidRuntime(20158): at java.lang.reflect.Method.invoke(Native Method)
01-01 08:48:11.147 E/AndroidRuntime(20158): at java.lang.reflect.Method.invoke(Method.java:372)
01-01 08:48:11.147 E/AndroidRuntime(20158): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:932)
01-01 08:48:11.147 E/AndroidRuntime(20158): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:727)

**Comment by drivedreams** [comment]
其他so会dlopen 他 名字是写死的




发自网易邮箱大师
在2017年06月12日 19:44，ZhangHaihai 写道：
你的很清楚




发自网易邮箱大师
在2017年06月12日 15:58，owen 写道：

so重命名后个别机型会报错；
初始化代码如下：
IjkMediaPlayer.loadLibrariesOnce(new IjkLibLoader() {
@override
public void loadLibrary(String libName) {
try {
System.loadLibrary("lexue"+libName);
} catch (UnsatisfiedLinkError e) {
e.printStackTrace();
} catch (SecurityException e) {
e.printStackTrace();
}
}
});
IjkMediaPlayer.native_profileBegin("liblexueijkplayer.so");

报错信息如下：
01-01 08:48:10.971 E/art (20158): dlopen("/data/app/com.huan.edu.tvplayer.example2-1/lib/arm/liblexueijkplayer.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "SDL_SpeedSamplerReset" referenced by "liblexueijkplayer.so"...
01-01 08:48:10.971 D/ControlCenterWorkThread(19429): refreshDevices...
01-01 08:48:10.971 W/System.err(20158): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "SDL_SpeedSamplerReset" referenced by "liblexueijkplayer.so"...
01-01 08:48:10.972 D/ControlCenterWorkThread(19429): Mcontroller controlCenterWorkThread MCstartSearch
01-01 08:48:10.979 W/System.err(20158): at java.lang.Runtime.loadLibrary(Runtime.java:371)
01-01 08:48:10.979 W/System.err(20158): at java.lang.System.loadLibrary(System.java:988)
01-01 08:48:10.979 W/System.err(20158): at com.huan.edu.tvplayer.utils.EPLibraryUtil$1$1.loadLibrary(EPLibraryUtil.java:88)
01-01 08:48:10.979 W/System.err(20158): at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:176)
01-01 08:48:10.979 W/System.err(20158): at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:83)
01-01 08:48:10.979 W/System.err(20158): at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:58)
01-01 08:48:10.979 W/System.err(20158): at android.os.AsyncTask.finish(AsyncTask.java:636)
01-01 08:48:10.979 W/System.err(20158): at android.os.AsyncTask.access$500(AsyncTask.java:177)
01-01 08:48:10.979 W/System.err(20158): at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
01-01 08:48:10.979 W/System.err(20158): at android.os.Handler.dispatchMessage(Handler.java:102)
01-01 08:48:10.979 W/System.err(20158): at android.os.Looper.loop(Looper.java:135)
01-01 08:48:10.979 W/System.err(20158): at android.app.ActivityThread.main(ActivityThread.java:5275)
01-01 08:48:10.979 W/System.err(20158): at java.lang.reflect.Method.invoke(Native Method)
01-01 08:48:10.979 W/System.err(20158): at java.lang.reflect.Method.invoke(Method.java:372)
01-01 08:48:10.979 W/System.err(20158): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:932)
01-01 08:48:10.979 W/System.err(20158): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:727)

01-01 08:48:11.146 E/art (20158): No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_profileBegin(java.lang.String) (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1profileBegin and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1profileBegin__Ljava_lang_String_2)
01-01 08:48:11.146 D/AndroidRuntime(20158): Shutting down VM
01-01 08:48:11.147 E/AndroidRuntime(20158): FATAL EXCEPTION: main
01-01 08:48:11.147 E/AndroidRuntime(20158): Process: com.huan.edu.tvplayer.example2, PID: 20158
01-01 08:48:11.147 E/AndroidRuntime(20158): java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_profileBegin(java.lang.String) (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1profileBegin and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1profileBegin__Ljava_lang_String_2)
01-01 08:48:11.147 E/AndroidRuntime(20158): at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_profileBegin(Native Method)
01-01 08:48:11.147 E/AndroidRuntime(20158): at com.huan.edu.tvplayer.widget.EduIjkVideoView.initVideoLib(EduIjkVideoView.java:172)
01-01 08:48:11.147 E/AndroidRuntime(20158): at com.huan.edu.tvplayer.EduPlayerFragment$2.onInitFinish(EduPlayerFragment.java:209)
01-01 08:48:11.147 E/AndroidRuntime(20158): at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:107)
01-01 08:48:11.147 E/AndroidRuntime(20158): at com.huan.edu.tvplayer.utils.EPLibraryUtil$1.onPostExecute(EPLibraryUtil.java:58)
01-01 08:48:11.147 E/AndroidRuntime(20158): at android.os.AsyncTask.finish(AsyncTask.java:636)
01-01 08:48:11.147 E/AndroidRuntime(20158): at android.os.AsyncTask.access$500(AsyncTask.java:177)
01-01 08:48:11.147 E/AndroidRuntime(20158): at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
01-01 08:48:11.147 E/AndroidRuntime(20158): at android.os.Handler.dispatchMessage(Handler.java:102)
01-01 08:48:11.147 E/AndroidRuntime(20158): at android.os.Looper.loop(Looper.java:135)
01-01 08:48:11.147 E/AndroidRuntime(20158): at android.app.ActivityThread.main(ActivityThread.java:5275)
01-01 08:48:11.147 E/AndroidRuntime(20158): at java.lang.reflect.Method.invoke(Native Method)
01-01 08:48:11.147 E/AndroidRuntime(20158): at java.lang.reflect.Method.invoke(Method.java:372)
01-01 08:48:11.147 E/AndroidRuntime(20158): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:932)
01-01 08:48:11.147 E/AndroidRuntime(20158): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:727)

**Comment by zhousuqiang** [comment]
@drivedreams 你好，因为我们的app需要系统集成，有可能so文件有可能冲突，所以最好是重命名，请问重编译so改名字的话，都需要改哪些地方呢，我看看了mk文件，没有找到在哪修改ijkffmpeg.so的名称。

**Comment by drivedreams** [comment]
不是mk dlopen 是c 里写的 建议不要修改 要不升级就麻烦了
