### ISSUE TITLE
demo报错

### ISSUE THREAD

**Issue by HuangFuMaYe** [Bilibili/ijkplayer#3355]
各位，给的demo  报错，怎么整

**Comment by wheatdamon** [comment]
07-27 14:26:12.104 16085-16085/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: tv.danmaku.ijk.media.example, PID: 16085
                                                   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.example-1/base.apk"],nativeLibraryDirectories=[/data/app/tv.danmaku.ijk.media.example-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libijkffmpeg.so"
                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                       at java.lang.System.loadLibrary(System.java:1562)
                                                       at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:176)
                                                       at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:187)
                                                       at tv.danmaku.ijk.media.example.activities.VideoActivity.onCreate(VideoActivity.java:137)
                                                       at android.app.Activity.performCreate(Activity.java:6682)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by Android4MediaPlayer** [comment]
missing arm64 library

**Comment by wheatdamon** [comment]
compile project(':ijkplayer-java')
    compile project(':ijkplayer-exo')

    all32Compile project(':ijkplayer-armv5')
    all32Compile project(':ijkplayer-armv7a')
    all32Compile project(':ijkplayer-x86')

    all64Compile project(':ijkplayer-armv5')
    all64Compile project(':ijkplayer-armv7a')
    all64Compile project(':ijkplayer-arm64')
    all64Compile project(':ijkplayer-x86')
    all64Compile project(':ijkplayer-x86_64')

**Comment by caoanqi** [comment]
同样的问题 引入的库也是没有问题的：
e E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: tv.danmaku.ijk.media.example, PID: 18765
                                                                              java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.example-1/base.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_dependencies_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_0_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_1_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_2_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_3_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_4_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_5_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_6_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_7_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_8_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libijkffmpeg.so"
                                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                                  at java.lang.System.loadLibrary(System.java:988)
                                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:176)
                                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:187)
                                                                                  at tv.danmaku.ijk.media.example.activities.VideoActivity.onCreate(VideoActivity.java:137)
                                                                                  at android.app.Activity.performCreate(Activity.java:6039)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
                                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:154)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5296)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)


请问如何解决？谢谢
