### ISSUE TITLE
项目导入AS了 也装到手机里了 但是播放不了 什么问题啊 怎么打开之后全是些文件夹啊 Settings里面怎么设置都还是文件夹的形式

### ISSUE THREAD

**Issue by yulinwoniu666** [Bilibili/ijkplayer#3482]

**Comment by 963375877** [comment]
程序运行在安卓手机上时出现 抱歉XXX程序已退出，生成log日志，日志内容如下。
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.example-1/base.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_dependencies_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_0_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_1_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_2_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_3_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_4_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_5_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_6_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_7_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_8_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/tv.danmaku.ijk.media.example-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "
libijkffmpeg.so"
at java.lang.Runtime.loadLibrary(Runtime.java:367)
at java.lang.System.loadLibrary(System.java:1076)
at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:176)
at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:187)
at tv.danmaku.ijk.media.example.activities.VideoActivity.onCreate(VideoActivity.java:137)
at android.app.Activity.performCreate(Activity.java:6303)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
at android.app.ActivityThread.access$1000(ActivityThread.java:153)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:5524)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
原因couldn't find "libijkffmpeg.so" ,解决方法是进入原来的ijkplayer目录下，找到compile-ijk.sh 这个文件所在目录，我的是 /home/tbs/ijkplayer-master/android ，然后输入./ compile-ijk.sh执行它，会自动编译生成很多so文件，不用管，这时候重新打开android studio导入项目，运行问题解决。
希望对你有帮助
