### ISSUE TITLE
DEMO运行后报错UnsatisfiedLinkError  couldn't find "libijkffmpeg.so"

### ISSUE THREAD

**Issue by 541954852** [Bilibili/ijkplayer#3690]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.example-1/base.apk"],nativeLibraryDirectories=[/data/app/tv.danmaku.ijk.media.example-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
                                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                                  at java.lang.System.loadLibrary(System.java:1076)
                                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:178)
                                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:189)
                                                                                  at tv.danmaku.ijk.media.example.activities.VideoActivity.onCreate(VideoActivity.java:137)
                                                                                  at android.app.Activity.performCreate(Activity.java:6295)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2505)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2618)
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                  at android.os.Looper.loop(Looper.java:207)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5701)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

**Comment by msn465780** [comment]
因为直接更新项目里面没有.so文件，需要自己根据配置编译出来用
