### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by qiiyue** [Bilibili/ijkplayer#3718]
I have a problem in android, maybe we can solve this exception. in AndroidMediaPlayer,this is log.

java.lang.IllegalStateException.
at android.media.MediaPlayer.prepareAsync(Native Method)
at tv.danmaku.ijk.media.player.AndroidMediaPlayer.prepareAsync(AndroidMediaPlayer.java:166)

**Comment by lrs0304** [comment]
空指针是全世界最好解决的bug了，好好检查下你的ijkplayer是否是空指针

**Comment by qiiyue** [comment]
its not nullpointer, just catch the exception.
