### ISSUE TITLE
ava.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried  拉的最新代码编写的

### ISSUE THREAD

**Issue by nances** [Bilibili/ijkplayer#3728]
11-06 11:37:52.072 16037-16037/? E/CrashReport: sys default last handle start!
11-06 11:37:52.111 16037-17213/? I/DpmTcmClient: RegisterTcmMonitor from: org.apache.http.impl.conn.TcmIdleTimerMonitor
11-06 11:37:52.120 16037-16046/? E/art: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
11-06 11:37:52.120 16037-16046/? E/System: Uncaught exception thrown by finalizer
11-06 11:37:52.120 16037-16046/? E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                               at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                               at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:571)
                                               at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:230)
                                               at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:217)
                                               at java.lang.Thread.run(Thread.java:761)
                                           

麻烦帮忙看看这个问题，谢谢

**Comment by zhanggao** [comment]
这种问题大概率跟混淆有关，自己使用的问题。
看看这篇文章理解下so怎么用吧。
http://allenfeng.com/2016/11/06/what-you-should-know-about-android-abi-and-so/

**Comment by Owen0103** [comment]
这个跟混淆应该没关系吧，我没有开混淆也有这个问题，也是更新版本后出现的

**Comment by Guoooooo** [comment]
请问这个问题有解决吗 正常我在onDestory中调用了 IjkMediaPlayer.native profileEnd 但也此Exception

**Comment by Android4MediaPlayer** [comment]
估计so加载失败了
