### ISSUE TITLE
一个VerifyError异常

### ISSUE THREAD

**Issue by firelion0725** [Bilibili/ijkplayer#3794]
在测试IjkExoMediaPlayer时，在创建流程中的 创建Media 流程代码强制设置为ExoMediaPlayer
mMediaPlayer = createPlayer(Settings.PV_PLAYER__IjkExoMediaPlayer); 
设置为ExoMedia 但是在 mediaPlayer = new IjkExoMediaPlayer(mAppContext); 这行报错
com.leo.ijkplayer.test E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.leo.ijkplayer.test, PID: 514
                                                                    java.lang.VerifyError: tv/danmaku/ijk/media/exo/demo/EventLogger
                                                                        at tv.danmaku.ijk.media.exo.IjkExoMediaPlayer.<init>(IjkExoMediaPlayer.java:59)
                                                                        at tv.danmaku.ijk.media.example.widget.media.IjkVideoView.createPlayer(IjkVideoView.java:1025)
                                                                        at tv.danmaku.ijk.media.example.widget.media.IjkVideoView.openVideo(IjkVideoView.java:318)
                                                                        at tv.danmaku.ijk.media.example.widget.media.IjkVideoView.access$2500(IjkVideoView.java:63)
                                                                        at tv.danmaku.ijk.media.example.widget.media.IjkVideoView$9.onSurfaceCreated(IjkVideoView.java:696)
                                                                        at tv.danmaku.ijk.media.example.widget.media.SurfaceRenderView$SurfaceCallback.surfaceCreated(SurfaceRenderView.java:234)
                                                                        at android.view.SurfaceView.updateWindow(SurfaceView.java:583)
                                                                        at android.view.SurfaceView.access$000(SurfaceView.java:88)
                                                                        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
                                                                        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1944)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1042)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5905)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:593)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:562)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
                                                                        at android.os.Handler.handleCallback(Handler.java:733)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5314)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                        at dalvik.system.NativeStart.main(Native Method)

不知道 是改的问题 还是 其他问题

**Comment by Greathfs** [comment]
我今天也报了这个错误
