### ISSUE TITLE
Android 7.0 动态加载 .so, crash

### ISSUE THREAD

**Issue by panda912** [Bilibili/ijkplayer#3828]
`java.lang.UnsatisfiedLinkError: dlopen failed: library "/storage/emulated/0/Android/data/com.xxx.xxx/files/jniLibs/libijkffmpeg.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
                                                                       at java.lang.Runtime.load0(Runtime.java:897)
                                                                       at java.lang.System.load(System.java:1505)
                                                                       at com.xxx.xxx.ApplicationLike.loadLibrary(ApplicationLike.java:568)
                                                                       at com.xxx.xxx.ApplicationLike.onCreate(ApplicationLike.java:187)
                                                                       at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:173)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1027)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5683)
                                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1700)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                       at android.os.Looper.loop(Looper.java:203)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6434)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
`

**Comment by LeeKaFoon** [comment]
Excuse me, how did you solve it

**Comment by rw321** [comment]
Excuse me, how did you solve it

**Comment by rw321** [comment]
> Excuse me, how did you solve it

did you solve it now
