### ISSUE TITLE
GiONEE GN9006 播放视频崩溃

### ISSUE THREAD

**Issue by phoche** [Bilibili/ijkplayer#3920]
java.lang.IllegalStateException
	at tv.danmaku.ijk.media.player.IjkMediaPlayer._prepareAsync(Native Method)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.prepareAsync(IjkMediaPlayer.java:508)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer$EventHandler.handleMessage(IjkMediaPlayer.java:991)
 	at android.os.Handler.dispatchMessage(Handler.java:111)
 	at android.os.Looper.loop(Looper.java:194)
 	at android.app.ActivityThread.main(ActivityThread.java:5536)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:372)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by raymond1012** [comment]
IllegalStateException    状态不对，自己check下状态
