### ISSUE TITLE
求助！！

### ISSUE THREAD

**Issue by czfyzzf** [Bilibili/ijkplayer#3969]
一运行就错误了 
mVideoView.setVideoURI(Uri.parse(mUrl));       
 mVideoView.setOnPreparedListener(new IMediaPlayer.OnPreparedListener() {
            @Override
            public void onPrepared(IMediaPlayer mp) {
                mVideoView.start();
            }
        });

 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.zzf.superplayer.superplayer.weight.media.InfoHudViewHolder.updateLoadCost(long)' on a null object reference
                                                                                   at com.zzf.superplayer.superplayer.weight.media.IjkVideoView$2.onPrepared(IjkVideoView.java:417)
                                                                                   at tv.danmaku.ijk.media.player.AbstractMediaPlayer.notifyOnPrepared(AbstractMediaPlayer.java:80)
                                                                                   at tv.danmaku.ijk.media.player.IjkMediaPlayer$EventHandler.handleMessage(IjkMediaPlayer.java:968)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                   at android.os.Looper.loop(Looper.java:194)

**Comment by Android4MediaPlayer** [comment]
你把这个hudview可以去掉的

**Comment by czfyzzf** [comment]
已经解决，InfoHudViewHolder其实是example里面的一个信息显示窗口，把IjkVideoView里面有关的，全部注释掉就可以了
