### ISSUE TITLE
Cannot play video on Coolpad 8675 with MT6592

### ISSUE THREAD

**Issue by jpxiong** [Bilibili/ijkplayer#402]
It seems the decoder's error, how to solve this kind of error ?
Thanks.
```
08-14 14:41:03.879: D/IJKMEDIA(3333): IjkMediaPlayer_start
08-14 14:41:03.879: D/IJKMEDIA(3333): ijkmp_start()
08-14 14:41:03.879: D/IJKMEDIA(3333): ijkmp_get_msg: FFP_REQ_START
08-14 14:41:03.879: D/IJKMEDIA(3333): ijkmp_start()=0
08-14 14:41:03.880: I/VideoView(3333): VIDEO: 540x960x0.562500[SAR:0:0], Surface: 540x960, LP: 720x1280, Window: 720x1280x0.562500
08-14 14:41:03.881: I/VideoView(3333): VIDEO: 540x960x0.562500[SAR:0:1], Surface: 540x960, LP: 720x1280, Window: 720x1280x0.562500
08-14 14:41:03.891: I/SurfaceView(3333): updateWindow -- setFrame
08-14 14:41:03.892: I/SurfaceView(3333): Changes: creating=false format=false size=true visible=false left=false top=false mUpdateWindowNeeded=false mReportDrawNeeded=false redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=true
08-14 14:41:03.892: I/SurfaceView(3333): Cur surface: Surface(name=null)/@0x438b5e98
08-14 14:41:03.908: V/SurfaceView(3333): com.pili.pldroid.player.widget.VideoView{438b5b58 VFE..... .F....I. 0,0-720,1230 #7f0b0077 app:id/video_view} got resized: w=720 h=1230, cur w=-1 h=-1
08-14 14:41:03.913: I/SurfaceView(3333): New surface: Surface(name=null)/@0x438b5f48, vis=true, frame=Rect(0, 50 - 720, 1280)
08-14 14:41:03.913: I/SurfaceView(3333): surfaceChanged -- format=4 w=540 h=960
08-14 14:41:03.913: I/SurfaceView(3333): surfaceChanged callback +
08-14 14:41:03.913: D/IJKMEDIA(3333): IjkMediaPlayer_start
08-14 14:41:03.914: D/IJKMEDIA(3333): ijkmp_start()
08-14 14:41:03.914: D/IJKMEDIA(3333): ijkmp_get_msg: FFP_REQ_START
08-14 14:41:03.914: D/IJKMEDIA(3333): ijkmp_start()=0
08-14 14:41:03.914: I/SurfaceView(3333): surfaceChanged callback -
08-14 14:41:03.914: V/SurfaceView(3333): Layout: x=0 y=50 w=720 h=1230, frame=Rect(0, 0 - 720, 1230)
08-14 14:41:03.915: D/ListView(3333): mSelectorRect.setEmpty in layoutChildren this=com.umtone.haoshuo.view.DropdownListView{433eb410 VFED..C. ......ID 0,96-720,1122 #7f0b0025 app:id/message_chat_listview}
08-14 14:41:03.915: I/SurfaceView(3333): updateWindow -- OnPreDrawListener, mHaveFrame = true
08-14 14:41:03.915: I/SurfaceView(3333): updateWindow -- OnScrollChangedListener
08-14 14:41:03.916: D/OpenGLRenderer(3333): prepareDirty (0.00, 0.00, 720.00, 1280.00) opaque 1 <0x7e195230>
08-14 14:41:03.917: D/OpenGLRenderer(3333): finish <0x7e195230>
08-14 14:41:03.930: I/SurfaceView(3333): updateWindow -- OnPreDrawListener, mHaveFrame = true
08-14 14:41:03.930: D/OpenGLRenderer(3333): prepareDirty (0.00, 0.00, 720.00, 1280.00) opaque 1 <0x7e195230>
08-14 14:41:03.932: D/OpenGLRenderer(3333): finish <0x7e195230>
08-14 14:41:03.934: D/GraphicBuffer(3333): close handle(0x7da42530) (w:384 h:78 f:1)
08-14 14:41:04.867: I/MediaCodec(3333): [getInputBuffers]:IN
08-14 14:41:04.874: I/MediaCodec(3333): [getInputBuffers]:IN
08-14 14:41:04.879: I/MediaCodec(3333): [getInputBuffers]:IN
08-14 14:41:04.890: I/MediaCodec(3333): [getInputBuffers]:IN
08-14 14:41:04.899: E/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] ERROR(0x80001005)
08-14 14:41:04.899: W/ACodec(3333): OMXCodec::onEvent--OMX Bad Parameter!!
08-14 14:41:04.900: E/MediaCodec(3333): Codec reported an error. (omx error 0x80001005, internalError -1103)
08-14 14:41:04.900: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.900: W/System.err(3333):     at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
08-14 14:41:04.900: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.900: I/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
08-14 14:41:04.904: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.904: W/System.err(3333):     at android.media.MediaCodec.dequeueInputBuffer(Native Method)
08-14 14:41:04.904: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.904: E/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
08-14 14:41:04.905: D/IJKMEDIA(3333): SDL_VoutFFmpeg_CreateOverlay(w=540, h=960, fmt=_AMC(0x434d415f, vout=0x804bcfb8)
08-14 14:41:04.905: D/IJKMEDIA(3333): FFP_MSG_VIDEO_SIZE_CHANGED: 540, 960
08-14 14:41:04.906: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.907: W/System.err(3333):     at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
08-14 14:41:04.907: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.907: I/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
08-14 14:41:04.908: I/VideoView(3333): VIDEO: 540x960x0.562500[SAR:0:1], Surface: 540x960, LP: 720x1280, Window: 720x1280x0.562500
08-14 14:41:04.911: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.911: W/System.err(3333):     at android.media.MediaCodec.dequeueInputBuffer(Native Method)
08-14 14:41:04.911: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.911: E/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
08-14 14:41:04.911: D/IJKMEDIA(3333): SDL_VoutFFmpeg_CreateOverlay(w=540, h=960, fmt=_AMC(0x434d415f, vout=0x804bcfb8)
08-14 14:41:04.911: D/IJKMEDIA(3333): FFP_MSG_VIDEO_SIZE_CHANGED: 540, 960
08-14 14:41:04.912: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.912: W/System.err(3333):     at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
08-14 14:41:04.912: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.912: I/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
08-14 14:41:04.912: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.912: W/System.err(3333):     at android.media.MediaCodec.dequeueInputBuffer(Native Method)
08-14 14:41:04.912: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.912: E/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
08-14 14:41:04.913: D/IJKMEDIA(3333): SDL_VoutFFmpeg_CreateOverlay(w=540, h=960, fmt=_AMC(0x434d415f, vout=0x804bcfb8)
08-14 14:41:04.913: D/IJKMEDIA(3333): FFP_MSG_VIDEO_SIZE_CHANGED: 540, 960
08-14 14:41:04.913: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.913: W/System.err(3333):     at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
08-14 14:41:04.914: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.914: I/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
08-14 14:41:04.916: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.916: W/System.err(3333):     at android.media.MediaCodec.dequeueInputBuffer(Native Method)
08-14 14:41:04.919: I/SurfaceView(3333): updateWindow -- setFrame
08-14 14:41:04.920: D/ListView(3333): mSelectorRect.setEmpty in layoutChildren this=com.umtone.haoshuo.view.DropdownListView{433eb410 VFED..C. ......ID 0,96-720,1122 #7f0b0025 app:id/message_chat_listview}
08-14 14:41:04.921: I/SurfaceView(3333): updateWindow -- OnPreDrawListener, mHaveFrame = true
08-14 14:41:04.921: I/SurfaceView(3333): updateWindow -- OnScrollChangedListener
08-14 14:41:04.922: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.922: E/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
08-14 14:41:04.922: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.922: W/System.err(3333):     at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
08-14 14:41:04.922: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.923: I/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
08-14 14:41:04.923: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.923: W/System.err(3333):     at android.media.MediaCodec.dequeueInputBuffer(Native Method)
08-14 14:41:04.923: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.923: E/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
08-14 14:41:04.924: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.924: W/System.err(3333):     at android.media.MediaCodec.dequeueInputBuffer(Native Method)
08-14 14:41:04.924: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.924: E/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
08-14 14:41:04.925: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.925: W/System.err(3333):     at android.media.MediaCodec.dequeueInputBuffer(Native Method)
08-14 14:41:04.925: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.925: E/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
08-14 14:41:04.925: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.925: W/System.err(3333):     at android.media.MediaCodec.dequeueInputBuffer(Native Method)
08-14 14:41:04.925: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.925: E/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
08-14 14:41:04.926: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.926: W/System.err(3333):     at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
08-14 14:41:04.926: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.927: I/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
08-14 14:41:04.928: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.928: W/System.err(3333):     at android.media.MediaCodec.dequeueInputBuffer(Native Method)
08-14 14:41:04.928: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.928: E/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
08-14 14:41:04.928: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.928: W/System.err(3333):     at android.media.MediaCodec.dequeueInputBuffer(Native Method)
08-14 14:41:04.928: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.928: E/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
08-14 14:41:04.931: D/OpenGLRenderer(3333): prepareDirty (0.00, 0.00, 720.00, 1280.00) opaque 1 <0x7e195230>
08-14 14:41:04.932: D/OpenGLRenderer(3333): finish <0x7e195230>
08-14 14:41:04.937: I/VideoView(3333): VIDEO: 540x960x0.562500[SAR:0:1], Surface: 540x960, LP: 720x1280, Window: 720x1280x0.562500
08-14 14:41:04.938: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.939: I/VideoView(3333): VIDEO: 540x960x0.562500[SAR:0:1], Surface: 540x960, LP: 720x1280, Window: 720x1280x0.562500
08-14 14:41:04.939: W/System.err(3333):     at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
08-14 14:41:04.939: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.939: I/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
08-14 14:41:04.947: D/dalvikvm(3333): threadid=62: interp stack at 0x8206c000
08-14 14:41:04.947: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.947: W/System.err(3333):     at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
08-14 14:41:04.948: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.948: I/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
08-14 14:41:04.948: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.948: W/System.err(3333):     at android.media.MediaCodec.releaseOutputBuffer(Native Method)
08-14 14:41:04.948: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.948: E/IJKMEDIA(3333): SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer
08-14 14:41:04.948: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.949: W/System.err(3333):     at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
08-14 14:41:04.949: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.949: I/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
08-14 14:41:04.952: I/SurfaceView(3333): updateWindow -- setFrame
08-14 14:41:04.953: D/ListView(3333): mSelectorRect.setEmpty in layoutChildren this=com.umtone.haoshuo.view.DropdownListView{433eb410 VFED..C. ......ID 0,96-720,1122 #7f0b0025 app:id/message_chat_listview}
08-14 14:41:04.953: I/SurfaceView(3333): updateWindow -- OnPreDrawListener, mHaveFrame = true
08-14 14:41:04.953: I/SurfaceView(3333): updateWindow -- OnScrollChangedListener
08-14 14:41:04.955: D/OpenGLRenderer(3333): prepareDirty (0.00, 0.00, 720.00, 1280.00) opaque 1 <0x7e195230>
08-14 14:41:04.957: D/OpenGLRenderer(3333): finish <0x7e195230>
08-14 14:41:04.959: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.959: W/System.err(3333):     at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
08-14 14:41:04.959: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.959: I/IJKMEDIA(3333): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
08-14 14:41:04.959: W/System.err(3333): java.lang.IllegalStateException
08-14 14:41:04.960: W/System.err(3333):     at android.media.MediaCodec.releaseOutputBuffer(Native Method)
08-14 14:41:04.960: W/System.err(3333):     at dalvik.system.NativeStart.run(Native Method)
08-14 14:41:04.960: E/IJKMEDIA(3333): SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer

08-14 14:41:08.339: I/View(3333): Touch down dispatch to android.widget.Button{4392dfa8 VFED..C. ........ 0,0-128,96 #7f0b0079 app:id/back_btn}, event = MotionEvent { action=ACTION_DOWN, id[0]=0, x[0]=44.937588, y[0]=41.928185, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=86261157, downTime=86261157, deviceId=2, source=0x1002 }
08-14 14:41:08.348: I/SurfaceView(3333): updateWindow -- OnPreDrawListener, mHaveFrame = true
08-14 14:41:08.349: D/OpenGLRenderer(3333): prepareDirty (0.00, 0.00, 720.00, 1280.00) opaque 1 <0x7e195230>
08-14 14:41:08.350: D/OpenGLRenderer(3333): finish <0x7e195230>
08-14 14:41:08.374: I/View(3333): Touch up dispatch to android.widget.Button{4392dfa8 VFED..C. ...P.... 0,0-128,96 #7f0b0079 app:id/back_btn}, event = MotionEvent { action=ACTION_UP, id[0]=0, x[0]=44.937588, y[0]=41.928185, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=86261194, downTime=86261157, deviceId=2, source=0x1002 }
08-14 14:41:08.380: V/Provider/Settings(3333): get setting for user 0 by user 0 so skipping cache
08-14 14:41:08.381: V/Provider/Settings(3333):  from settings cache , name = sound_effects_enabled , value = 0
08-14 14:41:08.381: D/IJKMEDIA(3333): ijkmp_stop()
08-14 14:41:08.382: D/dalvikvm(3333): threadid=62: threadExitCheck(0x7b519a38) count=0
08-14 14:41:08.382: D/dalvikvm(3333): threadid=62: thread exiting, not yet detached (count=0)
08-14 14:41:08.383: D/dalvikvm(3333): threadid=62: bye!
08-14 14:41:08.384: D/dalvikvm(3333): threadid=42: bye!
08-14 14:41:08.385: D/IJKMEDIA(3333): message_loop exit
08-14 14:41:08.385: D/IJKMEDIA(3333): ijkmp_stop()=0
08-14 14:41:08.385: D/IJKMEDIA(3333): IjkMediaPlayer_release
08-14 14:41:08.385: D/IJKMEDIA(3333): ijkmp_set_android_surface(surface=0x0)
08-14 14:41:08.386: D/IJKMEDIA(3333): ffpipeline_set_surface()
08-14 14:41:08.387: D/IJKMEDIA(3333): ijkmp_set_android_surface(surface=0x0)=void
08-14 14:41:08.387: D/IJKMEDIA(3333): ijkmp_shutdown_l()
08-14 14:41:08.401: D/AudioTrack(3333): audiotrack 0x804b20e0 stop done
08-14 14:41:08.401: D/AudioTrack(3333): ~audioTrack 0x804b20e0
08-14 14:41:08.401: D/AudioTrackCenter(3333): removeTrack, trackPtr:0x804b20e0
08-14 14:41:08.401: D/dalvikvm(3333): threadid=59: bye!
08-14 14:41:08.402: D/IPCThreadState(3333): [DN #5] BR_CLEAR_DEATH_NOTIFICATION_DONE cookie 0x7e0c5e48
08-14 14:41:08.402: D/dalvikvm(3333): threadid=58: threadExitCheck(0x7e0aa950) count=0
08-14 14:41:08.402: D/dalvikvm(3333): threadid=58: thread exiting, not yet detached (count=0)
08-14 14:41:08.403: D/dalvikvm(3333): threadid=58: bye!
08-14 14:41:09.022: I/IJKMEDIA(3333): MediaCodec: enqueue_thread_func: exit: 0
08-14 14:41:09.022: D/IJKMEDIA(3333): SDL_AMediaCodecJava_stop
08-14 14:41:09.022: D/dalvikvm(3333): threadid=61: threadExitCheck(0x7f244a40) count=0
08-14 14:41:09.022: D/dalvikvm(3333): threadid=61: thread exiting, not yet detached (count=0)
08-14 14:41:09.022: D/dalvikvm(3333): threadid=61: bye!
08-14 14:41:09.033: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Now Executing->Idle
08-14 14:41:09.040: W/MemoryDealer(3333): madvise(0x86733000, 397312, MADV_REMOVE) returned Operation not permitted
08-14 14:41:09.043: W/MemoryDealer(3333): madvise(0x866d1000, 397312, MADV_REMOVE) returned Operation not permitted
08-14 14:41:09.044: W/MemoryDealer(3333): madvise(0x86670000, 397312, MADV_REMOVE) returned Operation not permitted
08-14 14:41:09.044: W/MemoryDealer(3333): madvise(0x8660e000, 397312, MADV_REMOVE) returned Operation not permitted
08-14 14:41:09.056: W/MemoryDealer(3333): madvise(0x86362000, 397312, MADV_REMOVE) returned Operation not permitted
08-14 14:41:09.056: W/MemoryDealer(3333): madvise(0x86300000, 397312, MADV_REMOVE) returned Operation not permitted
08-14 14:41:09.059: W/MemoryDealer(3333): madvise(0x8629e000, 397312, MADV_REMOVE) returned Operation not permitted
08-14 14:41:09.061: W/MemoryDealer(3333): madvise(0x8623c000, 397312, MADV_REMOVE) returned Operation not permitted
08-14 14:41:09.061: I/ACodec(3333): freeBuffersOnPort
08-14 14:41:09.061: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8b33458
08-14 14:41:09.062: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8a865b0
08-14 14:41:09.063: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8a86438
08-14 14:41:09.064: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8a62d88
08-14 14:41:09.065: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8b404e8
08-14 14:41:09.065: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8b17380
08-14 14:41:09.066: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8b17220
08-14 14:41:09.067: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8a5a4d0
08-14 14:41:09.067: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8a5a7a0
08-14 14:41:09.068: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8ab8858
08-14 14:41:09.069: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8a5c840
08-14 14:41:09.070: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8a5c740
08-14 14:41:09.070: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8b40110
08-14 14:41:09.071: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8b382a8
08-14 14:41:09.072: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8a65648
08-14 14:41:09.073: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8aa35c8
08-14 14:41:09.074: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8bbde20
08-14 14:41:09.074: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8bbddb8
08-14 14:41:09.075: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8aa3658
08-14 14:41:09.076: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Calling cancelBuffer on buffer 0xb8a5d180
08-14 14:41:09.077: I/ACodec(3333): freeBuffersOnPort
08-14 14:41:09.077: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Now Idle->Loaded
08-14 14:41:09.077: D/ACodec(3333): [OMX.MTK.VIDEO.DECODER.AVC] Now Loaded
08-14 14:41:09.078: I/MediaCodec(3333): [onMessageReceived][msg='AMessage(what = 'codc', target = 6) = {
08-14 14:41:09.078: I/MediaCodec(3333):   int32_t what = 1935896429
08-14 14:41:09.078: I/MediaCodec(3333): }' ][what=kWhatShutdownCompleted][mState=8]:IN
08-14 14:41:09.078: D/GraphicBuffer(3333): close handle(0x8172e800) (w:544 h:960 f:259)
08-14 14:41:09.078: D/GraphicBuffer(3333): close handle(0x7e18d330) (w:544 h:960 f:259)
08-14 14:41:09.078: D/GraphicBuffer(3333): close handle(0x7e0ac8a0) (w:544 h:960 f:259)
08-14 14:41:09.078: D/GraphicBuffer(3333): close handle(0x7cf9ebf0) (w:544 h:960 f:259)
08-14 14:41:09.079: D/GraphicBuffer(3333): close handle(0x7e045d00) (w:544 h:960 f:259)
08-14 14:41:09.079: D/GraphicBuffer(3333): close handle(0x7df9c690) (w:544 h:960 f:259)
08-14 14:41:09.079: D/GraphicBuffer(3333): close handle(0x7e1acbc0) (w:544 h:960 f:259)
08-14 14:41:09.079: D/GraphicBuffer(3333): close handle(0x7e041140) (w:544 h:960 f:259)
08-14 14:41:09.079: D/GraphicBuffer(3333): close handle(0x7d1766a0) (w:544 h:960 f:259)
08-14 14:41:09.079: D/GraphicBuffer(3333): close handle(0x7e04fa98) (w:544 h:960 f:259)
08-14 14:41:09.080: D/GraphicBuffer(3333): close handle(0x7e1669a0) (w:544 h:960 f:259)
08-14 14:41:09.080: D/GraphicBuffer(3333): close handle(0x7dfa0628) (w:544 h:960 f:259)
08-14 14:41:09.080: D/GraphicBuffer(3333): close handle(0x7da42cd8) (w:544 h:960 f:259)
08-14 14:41:09.080: D/GraphicBuffer(3333): close handle(0x7e0d5990) (w:544 h:960 f:259)
08-14 14:41:09.080: D/GraphicBuffer(3333): close handle(0x7b948120) (w:544 h:960 f:259)
08-14 14:41:09.080: D/GraphicBuffer(3333): close handle(0x7e6dacf8) (w:544 h:960 f:259)
08-14 14:41:09.081: D/GraphicBuffer(3333): close handle(0x7e0383a8) (w:544 h:960 f:259)
08-14 14:41:09.081: D/GraphicBuffer(3333): close handle(0x7d9f8c88) (w:544 h:960 f:259)
08-14 14:41:09.081: D/GraphicBuffer(3333): close handle(0x7e145fe8) (w:544 h:960 f:259)
08-14 14:41:09.081: D/GraphicBuffer(3333): close handle(0x7d171920) (w:544 h:960 f:259)
08-14 14:41:09.081: D/GraphicBuffer(3333): close handle(0x7d958ec0) (w:544 h:960 f:259)
08-14 14:41:09.085: I/IJKMEDIA(3333): MediaCodec: func_run_sync: exit: -1
08-14 14:41:09.085: D/dalvikvm(3333): threadid=60: threadExitCheck(0x7e0b0008) count=0
08-14 14:41:09.085: D/dalvikvm(3333): threadid=60: thread exiting, not yet detached (count=0)
08-14 14:41:09.085: D/dalvikvm(3333): threadid=60: bye!
08-14 14:41:09.088: D/dalvikvm(3333): threadid=57: threadExitCheck(0x7cfa20c0) count=0
08-14 14:41:09.088: D/dalvikvm(3333): threadid=57: thread exiting, not yet detached (count=0)
08-14 14:41:09.088: D/dalvikvm(3333): threadid=57: bye!
08-14 14:41:09.088: E/IJKMEDIA(3333): SDL_Overlay(ffmpeg): overlay_free_l(0x7b918160)
08-14 14:41:09.088: E/IJKMEDIA(3333): SDL_Overlay(ffmpeg): overlay_free_l(0x7e037ac0)
08-14 14:41:09.088: E/IJKMEDIA(3333): SDL_Overlay(ffmpeg): overlay_free_l(0x7b917f18)
08-14 14:41:09.089: D/IJKMEDIA(3333): ijkmp_shutdown_l()=void
08-14 14:41:09.089: D/IJKMEDIA(3333): ijkmp_dec_ref(): ref=0
08-14 14:41:09.089: D/IJKMEDIA(3333): ijkmp_shutdown_l()
08-14 14:41:09.089: D/IJKMEDIA(3333): ijkmp_shutdown_l()=void
```

**Comment by Android4MediaPlayer** [comment]
OMXCodec::onEvent--OMX Bad Parameter!! checkout sps and pps

**Comment by jpxiong** [comment]
It works fine on other Android Phones. So it doesn't matter about the sps and pps.

**Comment by Android4MediaPlayer** [comment]
The MTK H264 decoder need the parameter csd-0 and csd-1 to init the decoder(You can get some information at http://developer.android.com/reference/android/media/MediaCodec.html). csd-0 and csd-1 stands for SPS and PPS of H264.We can use the code below to set these two parameters.
byte[] sps = {0,0,0,1,103,100,0,40,-84,52,-59,1,-32,17,31,120,11,80,16,16,31
              ,0,0,3,3,-23,0,0,-22,96,-108};
byte[] pps = {0,0,0,1,104,-18,60,-128};
MediaFormat mFormat = MediaFormat.createVideoFormat("video/avc", width, height);
mFormat.setByteBuffer("csd-0", ByteBuffer.wrap(sps));
mFormat.setByteBuffer("csd-1", ByteBuffer.wrap(pps));
Maybe that's whay we got the OMX Bad Parameter error message.

**Comment by jpxiong** [comment]
Thanks. I will try it. I have a question: where are the sps and pps array datas from ? Is there any link for that ?

**Comment by jpxiong** [comment]
@Android4MediaPlayer 
It crashed :

I/libexynosv4l2( 9923): open video device /dev/video7
E/EXYNOS_LOG( 9923): HAL format is unsupported(0xe92d4010)
E/EXYNOS_VIDEO_ENC( 9923): [Exynos_OMX_ExtensionSetup] unsupported color format : ANB color is 0x0
E/ACodec  (10243): [OMX.Exynos.AVC.Encoder] ERROR(0x80001006)
E/MediaCodec(10243): Codec reported an error. (omx error 0x80001006, internalError -2147483648)
E/EXYNOS_LOG( 9923): HAL format is unsupported(0x30)
E/EXYNOS_VIDEO_ENC( 9923): [Exynos_OMX_ExtensionSetup] unsupported color format : ANB color is 0x0
E/ACodec  (10243): [OMX.Exynos.AVC.Encoder] ERROR(0x80001006)
E/MediaCodec(10243): Codec reported an error. (omx error 0x80001006, internalError -2147483648)

**Comment by Android4MediaPlayer** [comment]
encoder?  HAL format is unsupported

**Comment by jpxiong** [comment]
No. I added the sps/pps what you said, then crash happened.

**Comment by jpxiong** [comment]
@Android4MediaPlayer 
Where are the values as the following from:
```
byte[] sps = {0,0,0,1,103,100,0,40,-84,52,-59,1,-32,17,31,120,11,80,16,16,31
,0,0,3,3,-23,0,0,-22,96,-108};
byte[] pps = {0,0,0,1,104,-18,60,-128};
```

Could you please share the link? Thanks.
