### ISSUE TITLE
stop and release the player

### ISSUE THREAD

**Issue by leonard0629** [Bilibili/ijkplayer#414]
what i need to do before i finsh the activity in which the video is playing.
i tried videoview.stopplayback but something wrong with it.
```
08-19 14:38:13.538  17874-17874/com.test.app D/IJKMEDIA﹕ IjkMediaPlayer_reset
08-19 14:38:13.538  17874-17874/com.test.app D/IJKMEDIA﹕ IjkMediaPlayer_release
08-19 14:38:13.538  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)
08-19 14:38:13.538  17874-17874/com.test.app D/IJKMEDIA﹕ ffpipeline_set_surface()
08-19 14:38:13.538  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)=void
08-19 14:38:13.538  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_shutdown_l()
08-19 14:38:13.548  17874-18218/com.test.app D/IJKMEDIA﹕ message_loop exit
08-19 14:38:13.548  17874-18219/com.test.app E/IJKMEDIA﹕ voud_display_overlay_l: NULL native_window
08-19 14:38:13.548  17874-18251/com.test.app D/IJKMEDIA﹕ SDL_AMediaCodecJava_stop
08-19 14:38:13.548  17874-18219/com.test.app D/dalvikvm﹕ threadid=37: thread exiting, not yet detached (count=0)
08-19 14:38:13.558  17874-18243/com.test.app I/ACodec﹕ [OMX.qcom.video.decoder.avc] Now Executing->Idle
08-19 14:38:13.558  17874-18252/com.test.app W/System.err﹕ java.lang.IllegalStateException
08-19 14:38:13.558  17874-18252/com.test.app W/System.err﹕ at android.media.MediaCodec.dequeueInputBuffer(Native Method)
08-19 14:38:13.558  17874-18252/com.test.app W/System.err﹕ at dalvik.system.NativeStart.run(Native Method)
08-19 14:38:13.558  17874-18252/com.test.app E/IJKMEDIA﹕ SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
08-19 14:38:13.558  17874-18252/com.test.app I/IJKMEDIA﹕ MediaCodec: enqueue_thread_func: exit: -1
08-19 14:38:13.558  17874-18252/com.test.app D/dalvikvm﹕ threadid=36: thread exiting, not yet detached (count=0)
08-19 14:38:13.568  17874-18243/com.test.app I/ACodec﹕ [OMX.qcom.video.decoder.avc] Now Idle->Loaded
08-19 14:38:13.568  17874-18243/com.test.app I/ACodec﹕ [OMX.qcom.video.decoder.avc] Now Loaded
08-19 14:38:13.568  17874-18251/com.test.app I/IJKMEDIA﹕ MediaCodec: func_run_sync: exit: 0
08-19 14:38:13.568  17874-18251/com.test.app D/dalvikvm﹕ threadid=35: thread exiting, not yet detached (count=0)
08-19 14:38:13.578  17874-18223/com.test.app D/dalvikvm﹕ threadid=34: thread exiting, not yet detached (count=0)
08-19 14:38:13.598  17874-18220/com.test.app D/dalvikvm﹕ threadid=32: thread exiting, not yet detached (count=0)
08-19 14:38:13.608  17874-17874/com.test.app E/IJKMEDIA﹕ SDL_Overlay(ffmpeg): overlay_free_l(0x7e17b828)
08-19 14:38:13.608  17874-17874/com.test.app W/System.err﹕ java.lang.IllegalStateException
08-19 14:38:13.608  17874-17874/com.test.app W/System.err﹕ at android.media.MediaCodec.releaseOutputBuffer(Native Method)
08-19 14:38:13.608  17874-17874/com.test.app W/System.err﹕ at tv.danmaku.ijk.media.player.IjkMediaPlayer._reset(Native Method)
08-19 14:38:13.608  17874-17874/com.test.app W/System.err﹕ at tv.danmaku.ijk.media.player.IjkMediaPlayer.reset(IjkMediaPlayer.java:427)
08-19 14:38:13.608  17874-17874/com.test.app W/System.err﹕ at com.test.widget.MyVideoView.release(MyVideoView.java:566)
08-19 14:38:13.608  17874-17874/com.test.app W/System.err﹕ at com.test.widget.MyVideoView.access$2400(MyVideoView.java:24)
08-19 14:38:13.608  17874-17874/com.test.app W/System.err﹕ at com.test.widget.MyVideoView$8.surfaceDestroyed(MyVideoView.java:560)
08-19 14:38:13.608  17874-17874/com.test.app W/System.err﹕ at android.view.SurfaceView.updateWindow(SurfaceView.java:586)
08-19 14:38:13.608  17874-17874/com.test.app W/System.err﹕ at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:240)
08-19 14:38:13.608  17874-17874/com.test.app W/System.err﹕ at android.view.View.dispatchWindowVisibilityChanged(View.java:8492)
08-19 14:38:13.608  17874-17874/com.test.app W/System.err﹕ at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1087)
08-19 14:38:13.608  17874-17874/com.test.app W/System.err﹕ at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1087)
08-19 14:38:13.608  17874-17874/com.test.app W/System.err﹕ at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1087)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1087)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1087)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1532)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6585)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at android.view.Choreographer.doCallbacks(Choreographer.java:603)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at android.view.Choreographer.doFrame(Choreographer.java:573)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:733)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at android.os.Looper.loop(Looper.java:136)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5586)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
08-19 14:38:13.618  17874-17874/com.test.app W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
08-19 14:38:13.628  17874-17874/com.test.app E/IJKMEDIA﹕ SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer
08-19 14:38:13.628  17874-17874/com.test.app E/IJKMEDIA﹕ SDL_Overlay(ffmpeg): overlay_free_l(0x7e578888)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ java.lang.IllegalStateException
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at android.media.MediaCodec.releaseOutputBuffer(Native Method)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at tv.danmaku.ijk.media.player.IjkMediaPlayer._reset(Native Method)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at tv.danmaku.ijk.media.player.IjkMediaPlayer.reset(IjkMediaPlayer.java:427)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at com.test.widget.MyVideoView.release(MyVideoView.java:566)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at com.test.widget.MyVideoView.access$2400(MyVideoView.java:24)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at com.test.widget.MyVideoView$8.surfaceDestroyed(MyVideoView.java:560)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at android.view.SurfaceView.updateWindow(SurfaceView.java:586)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:240)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at android.view.View.dispatchWindowVisibilityChanged(View.java:8492)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1087)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1087)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1087)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1087)
08-19 14:38:13.628  17874-17874/com.test.app W/System.err﹕ at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1087)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1532)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6585)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at android.view.Choreographer.doCallbacks(Choreographer.java:603)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at android.view.Choreographer.doFrame(Choreographer.java:573)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:733)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at android.os.Looper.loop(Looper.java:136)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5586)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
08-19 14:38:13.638  17874-17874/com.test.app W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
08-19 14:38:13.638  17874-17874/com.test.app E/IJKMEDIA﹕ SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer
08-19 14:38:13.638  17874-17874/com.test.app E/IJKMEDIA﹕ SDL_Overlay(ffmpeg): overlay_free_l(0x7d9dc518)
08-19 14:38:13.648  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_shutdown_l()=void
08-19 14:38:13.648  17874-17874/com.test.app D/IJKMEDIA﹕ IjkMediaPlayer_native_setup
08-19 14:38:13.648  17874-17874/com.test.app D/IJKMEDIA﹕ ffpipeline_create_from_android()
08-19 14:38:13.648  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_set_format_callback(0x7e2a21f1, 0x1d400662)
08-19 14:38:13.648  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_set_format_callback()=void
08-19 14:38:13.648  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()
08-19 14:38:13.648  17874-17874/com.test.app D/IJKMEDIA﹕ ffpipeline_set_mediacodec_select_callback
08-19 14:38:13.648  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_android_set_mediacodec_select_callback()=void
08-19 14:38:13.648  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_dec_ref(): ref=0
08-19 14:38:13.648  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_shutdown_l()
08-19 14:38:13.648  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_shutdown_l()=void
08-19 14:38:13.648  17874-17874/com.test.app I/IJKMEDIA﹕ SDL_AMediaCodecJava_delete
08-19 14:38:13.658  17874-18243/com.test.app I/ACodec﹕ [OMX.qcom.video.decoder.avc] Now uninitialized
08-19 14:38:13.658  17874-17874/com.test.app D/IJKMEDIA﹕ IjkMediaPlayer_release
08-19 14:38:13.658  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)
08-19 14:38:13.658  17874-17874/com.test.app D/IJKMEDIA﹕ ffpipeline_set_surface()
08-19 14:38:13.658  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_set_android_surface(surface=0x0)=void
08-19 14:38:13.658  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_shutdown_l()
08-19 14:38:13.658  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_shutdown_l()=void
08-19 14:38:13.658  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_dec_ref(): ref=0
08-19 14:38:13.658  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_shutdown_l()
08-19 14:38:13.658  17874-17874/com.test.app D/IJKMEDIA﹕ ijkmp_shutdown_l()=void
08-19 14:38:13.848  17874-17874/com.test.app D/IJKMEDIA﹕ IjkMediaPlayer_native_profileEnd
08-19 14:38:13.848  17874-17874/com.test.app D/aprof-fake﹕ fake-momcleanup
08-19 14:38:13.848  17874-17874/com.test.app D/IJKMEDIA﹕ moncleanup
```
can you give me some suggestion to solve this. i just want release the videoview and finish current activity

**Comment by leonard0629** [comment]
is anyone know? this issue occurs when the surface destory such as Activity.onPause, Activity.onDestory

**Comment by leonard0629** [comment]
????

**Comment by bbcallen** [comment]
I can't see what is wrong.
Exception seems already be catched.

**Comment by leonard0629** [comment]
so can you give me the code to release safely when activity onPause or onDestory?
maybe it's the version problem? i complie the lib just as the readme on index page

**Comment by bbcallen** [comment]
What do you mean 'unsafe'? crash? ANR?
I can't see any problem in your log, except the exception warning.

**Comment by leonard0629** [comment]
avoid the exception

**Comment by bbcallen** [comment]
Patch welcome.

**Comment by qazmoon** [comment]
这个问题最新版本修复了吗？貌似是在mediacodec播放过程中按下home键再切换过来时发生的吧，
可能是在按下home后已经配置的mediacodec的surface被重置了，无法再重建。
是这个原因吗？

**Comment by bbcallen** [comment]
Feel free to reopen if any more question.
