### ISSUE TITLE
demo运行崩溃

### ISSUE THREAD

**Issue by zypguhe** [Bilibili/ijkplayer#4181]
Android 运行demo，点击对应条目，本应进入播放页面，但是会崩溃，错误如下：
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.example-1/base.apk"],nativeLibraryDirectories=[/data/app/tv.danmaku.ijk.media.example-1/lib/arm64, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "libijkffmpeg.so"
                                                                                  at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                                                  at java.lang.System.loadLibrary(System.java:1533)
                                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
                                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:190)
                                                                                  at tv.danmaku.ijk.media.example.activities.VideoActivity.onCreate(VideoActivity.java:137)
                                                                                  at android.app.Activity.performCreate(Activity.java:6915)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                  at android.os.Looper.loop(Looper.java:156)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

手机为华为荣耀8青春版

**Comment by TokenYc** [comment]
Demo默认的依赖是未编译的

**Comment by fakefacebook** [comment]
How can compile that dependancy?

**Comment by TokenYc** [comment]
just follow the README @fakefacebook
