### ISSUE TITLE
打包之后报java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Lee-Jian** [Bilibili/ijkplayer#4225]
compile 'tv.danmaku.ijk.media:ijkplayer-java:0.8.8'
 compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.8'
 compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.8.8'
打包运行后播放视频闪退 报UnsatisfiedLinkError错误
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.peoplecitic.finance-1/lib/arm/libijksdl.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	at java.lang.System.loadLibrary(System.java:1076)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.a(IjkMediaPlayer.java:179)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:191)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.a(IjkMediaPlayer.java:231)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.(IjkMediaPlayer.java:227)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.(IjkMediaPlayer.java:218)
	at com.peoplecitic.finance.video.FinanceVideoPlayer.z(FinanceVideoPlayer.java:373)
	at com.peoplecitic.finance.video.FinanceVideoPlayer.a(FinanceVideoPlayer.java:188)
	at com.peoplecitic.finance.video.FinanceAdVideoPlayerController.b(FinanceAdVideoPlayerController.java:307)
	at com.peoplecitic.finance.activity.MainActivity.a(MainActivity.java:729)
	at com.peoplecitic.finance.activity.MainActivity.b(MainActivity.java:83)
	at com.peoplecitic.finance.activity.MainActivity$6.a(MainActivity.java:679)
	at com.peoplecitic.finance.activity.MainActivity$6.onResponse(MainActivity.java:671)
	at com.android.volley.toolbox.GsonRequest.deliverResponse(GsonRequest.java:120)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5458)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by twlkyao** [comment]
> compile 'tv.danmaku.ijk.media:ijkplayer-java:0.8.8'
> compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.8'
> compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.8.8'
> 打包运行后播放视频闪退 报UnsatisfiedLinkError错误
> java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.peoplecitic.finance-1/lib/arm/libijksdl.so"
> at java.lang.Runtime.loadLibrary(Runtime.java:372)
> at java.lang.System.loadLibrary(System.java:1076)
> at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.a(IjkMediaPlayer.java:179)
> at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:191)
> at tv.danmaku.ijk.media.player.IjkMediaPlayer.a(IjkMediaPlayer.java:231)
> at tv.danmaku.ijk.media.player.IjkMediaPlayer.(IjkMediaPlayer.java:227)
> at tv.danmaku.ijk.media.player.IjkMediaPlayer.(IjkMediaPlayer.java:218)
> at com.peoplecitic.finance.video.FinanceVideoPlayer.z(FinanceVideoPlayer.java:373)
> at com.peoplecitic.finance.video.FinanceVideoPlayer.a(FinanceVideoPlayer.java:188)
> at com.peoplecitic.finance.video.FinanceAdVideoPlayerController.b(FinanceAdVideoPlayerController.java:307)
> at com.peoplecitic.finance.activity.MainActivity.a(MainActivity.java:729)
> at com.peoplecitic.finance.activity.MainActivity.b(MainActivity.java:83)
> at com.peoplecitic.finance.activity.MainActivity$6.a(MainActivity.java:679)
> at com.peoplecitic.finance.activity.MainActivity$6.onResponse(MainActivity.java:671)
> at com.android.volley.toolbox.GsonRequest.deliverResponse(GsonRequest.java:120)
> at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
> at android.os.Handler.handleCallback(Handler.java:739)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:148)
> at android.app.ActivityThread.main(ActivityThread.java:5458)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

How do you resolve this problem

**Comment by snowf07** [comment]
me too .
`   java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.tuji.tv-VqdMKC-hNIAdKzUCz7ZxJg==/lib/arm/libijksdl.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:162)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:174)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:214)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:210)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:201)
        at tv.danmaku.ijk.media.widget.MediaPlayerWrapper.openVideo(MediaPlayerWrapper.java:641)
        at tv.danmaku.ijk.media.widget.MediaPlayerWrapper.setVideoUrl(MediaPlayerWrapper.java:194)
        at tv.danmaku.ijk.media.widget.TextureVideoView$1.run(TextureVideoView.java:147)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)`
