### ISSUE TITLE
Android ijkplayer  issue

### ISSUE THREAD

**Issue by yejong2013** [Bilibili/ijkplayer#4532]
when i try following url, I can get errors.
https://github.com/Bilibili/ijkplayer

11-18 00:44:43.486 7988-7995/? E/zygote: Failed writing handshake bytes (-1 of 14): Broken pipe
11-18 00:44:46.820 7988-7988/tv.danmaku.ijk.media.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tv.danmaku.ijk.media.example, PID: 7988
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/base.apk", zip file "/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/split_lib_dependencies_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/split_lib_resources_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/split_lib_slice_0_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/split_lib_slice_1_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/split_lib_slice_2_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/split_lib_slice_3_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/split_lib_slice_4_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/split_lib_slice_5_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/split_lib_slice_6_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/split_lib_slice_7_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/split_lib_slice_8_apk.apk", zip file "/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/tv.danmaku.ijk.media.example-ZGY2YDmFPDGleOlQG1vWiQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libijkffmpeg.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:190)
        at tv.danmaku.ijk.media.example.activities.VideoActivity.onCreate(VideoActivity.java:137)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by fakefacebook** [comment]
have you got solution for this issue?
