### ISSUE TITLE
Android 9.0 音频加速有问题

### ISSUE THREAD

**Issue by mjnhmd** [Bilibili/ijkplayer#4571]
最新的0.8.8版本，调用setSpeed
报错如下
12-13 15:42:49.097 22497-22548/com.xiao.nicevieoplayer E/J4A: J4AC_android_media_AudioTrack__setSpeed 1.100000
12-13 15:42:49.097 22497-22548/com.xiao.nicevieoplayer D/AudioTrack: isSampleRateSpeedAllowed_l denied mAfLatency:80  mAfFrameCount:1920  mAfSampleRate:48000  sampleRate:44100  speed:1.100000 mFrameCount:3544 < minFrameCount:3888
12-13 15:42:49.097 22497-22548/com.xiao.nicevieoplayer W/AudioTrack: setPlaybackRate(1.100000, 1.000000) failed (buffer size)
12-13 15:42:49.097 22497-22548/com.xiao.nicevieoplayer W/System.err: java.lang.IllegalArgumentException: arguments out of range
12-13 15:42:49.097 22497-22548/com.xiao.nicevieoplayer W/System.err:     at android.media.AudioTrack.native_set_playback_params(Native Method)
12-13 15:42:49.097 22497-22548/com.xiao.nicevieoplayer W/System.err:     at android.media.AudioTrack.setPlaybackParams(AudioTrack.java:1902)
12-13 15:42:49.098 22497-22548/com.xiao.nicevieoplayer W/System.err: java.lang.IllegalArgumentException: arguments out of range
12-13 15:42:49.098 22497-22548/com.xiao.nicevieoplayer W/System.err:     at android.media.AudioTrack.native_set_playback_params(Native Method)
12-13 15:42:49.098 22497-22548/com.xiao.nicevieoplayer W/System.err:     at android.media.AudioTrack.setPlaybackParams(AudioTrack.java:1902)

**Comment by wchl09** [comment]
https://github.com/Bilibili/ijkplayer/issues/4569

**Comment by RubinX** [comment]
这个问题可以抓下日志，目前只发现在小米手机上
mAfFrameCount:1920 mAfSampleRate:48000 sampleRate:44100 speed:2.000000 mFrameCount:3544 < minFrameCount:7068

原因是：
ijkplayer调用getMinBufferSize(stereo,44100,16bit) 结果返回为7088，minFrameCount: 7088/4 = 1772
ijkplayer创建AudioTrack时bufferSizeInBytes设置为2xgetMinBufferSize，即 mFrameCount:3544
按照google官方代码注释 setPlaybackParams，只需要mFrameCount >= speed*getMinBufferSize/4 就可以了。也就是说mFrameCount=3544就可以了。
但是基于android9的mi8，在调用setPlaybackParams时要求2 x speed x getMinBufferSize/4

**Comment by RubinX** [comment]
解决方案有两种：
1。创建AudioTrack是，bufferSizeInBytes参数设置为4*minBufferSize，可能会导致音频延迟增加一倍
2。走软的加速，即soundtouch，可能会增加性能消耗

感觉这是小米的一个bug。

**Comment by perrrfeck** [comment]
> 解决方案有两种：
> 1。创建AudioTrack是，bufferSizeInBytes参数设置为4*minBufferSize，可能会导致音频延迟增加一倍
> 2。走软的加速，即soundtouch，可能会增加性能消耗
> 
> 感觉这是小米的一个bug。

你发的是尼玛的臭逼 IjkPlayer的AudioTrack是你能控制的？ 不贴代码下说什么呢
