### ISSUE TITLE
设置倍数异常（Set the multiple exception）

### ISSUE THREAD

**Issue by YBill** [Bilibili/ijkplayer#4586]
##### 问题：设置倍数为1.0以及以下没有问题，设置倍数大于1.0时没有效果，报错如下（There is no problem when setting the multiples to 1.0 and below. If the setting multiple is greater than 1.0, there is no effect. The error is as follows:）：

```
12-25 18:54:37.516 567-1893/? E/audio_hw_dolby: audio_extn_dolby_ds2_set_endpoint: Dolby set endpint :0x2
12-25 18:54:37.517 567-1893/? E/ACDB-LOADER: Error: ACDB AFE returned = -19
12-25 18:54:37.517 3645-3652/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]
12-25 18:54:37.519 1668-2658/? W/PowerManagerService: LIMIT_APP: getNetworkBytes use time = 14
12-25 18:54:37.522 1668-2658/? W/AppOps: isskipsystem  code:40  uid:1013
    Finishing op nesting under-run: uid 1013 pkg media code 40 time=0 duration=0 nesting=0
12-25 18:54:37.523 31506-31506/mypackage I/IJKMEDIA: Playback rate: 1.500000
12-25 18:54:37.580 31506-3123/mypackage E/J4A: J4AC_android_media_AudioTrack__setSpeed 1.500000
12-25 18:54:37.581 31506-3123/mypackage W/System.err: java.lang.IllegalArgumentException: arguments out of range
        at android.media.AudioTrack.native_set_playback_params(Native Method)
        at android.media.AudioTrack.setPlaybackParams(AudioTrack.java:1422)
12-25 18:54:37.582 31506-3123/mypackage W/System.err: java.lang.IllegalArgumentException: arguments out of range
        at android.media.AudioTrack.native_set_playback_params(Native Method)
        at android.media.AudioTrack.setPlaybackParams(AudioTrack.java:1422)
12-25 18:54:37.640 1668-1668/? E/NotificationService: Suppressing notification from package com.letv.android.supermanager by user request.
12-25 18:54:37.725 1668-1685/? W/AppOps: isskipsystem  code:40  uid:1013
12-25 18:54:37.742 3645-3652/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]
```

**Comment by Android4MediaPlayer** [comment]
java.lang.IllegalArgumentException: arguments out of range
        at android.media.AudioTrack.native_set_playback_params(Native Method)
        at android.media.AudioTrack.setPlaybackParams(AudioTrack.java:1422)
使用soundtouch呗

**Comment by YBill** [comment]
**我们项目对音频的处理不太多，基本就是播放各种格式的音频文件，最多也就是个变速功能。此外还有播放视频功能，可能SoundTouch不太合适引导项目中。

**Comment by BryanSharp** [comment]
小米8，Android9.0系统有这个问题,目前未解决
