### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wangjie123haha** [bilibili/ijkplayer#4616]
![Uploading 图片.png…]()

**Comment by wangjie123haha** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.ijkplayervideo-1/base.apk", zip file "/data/app/com.example.ijkplayervideo-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.ijkplayervideo-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.ijkplayervideo-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.ijkplayervideo-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.ijkplayervideo-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.ijkplayervideo-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.ijkplayervideo-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.ijkplayervideo-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.ijkplayervideo-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.ijkplayervideo-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.ijkplayervideo-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:366)
        at java.lang.System.loadLibrary(System.java:988)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:190)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:231)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:227)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:218)
        at com.example.ijkplayervideo.mvp.ui.activity.VideoPlayer.createPlayer(VideoPlayer.java:97)
