### ISSUE TITLE
重复跑了2万次，出现了crash异常

### ISSUE THREAD

**Issue by ThisZhu** [bilibili/ijkplayer#4632]
我封装了一个mx播放器，底层用的是ijkplayer，本质是这样的：
mx调用start（）方法时动态创建textureview，并且用addview方法添加到根布局中，mx调用stop（）方法时将textureview从根布局中移除。在onSurfaceTextureAvailable中创建并准备ijkplayer播放器，在onSurfaceTextureDestroyed中停止并销毁ijkplayer播放器。

我在在一个无限循环中 创建mx播放器，用mx播放一个本地视频20s，然后停止播放并销毁mx，期间mx可能在前台也可能是在后台运行。我这样循环了2万多次，直到出现下面的异常。

日志如下：
Thread Name:Thread[main,5,main]
java.lang.IllegalStateException
	at tv.danmaku.ijk.media.player.IjkMediaPlayer._prepareAsync(Native Method)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.prepareAsync(IjkMediaPlayer.java:515)
	at com.createled.cxsx.dsapp.player.manager.IjkPlayerManager.onViewAvailable(IjkPlayerManager.java:313)
	at com.createled.cxsx.dsapp.player.controller.MediaControl.onSurfaceTextureAvailable(MediaControl.java:307)
	at android.view.TextureView.getHardwareLayer(TextureView.java:368)
	at android.view.View.updateDisplayListIfDirty(View.java:15157)
	at android.view.View.draw(View.java:15954)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.draw(View.java:16187)
	at android.view.View.updateDisplayListIfDirty(View.java:15180)
	at android.view.View.draw(View.java:15954)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.updateDisplayListIfDirty(View.java:15175)
	at android.view.View.draw(View.java:15954)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.updateDisplayListIfDirty(View.java:15175)
	at android.view.View.draw(View.java:15954)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.updateDisplayListIfDirty(View.java:15175)
	at android.view.View.draw(View.java:15954)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.updateDisplayListIfDirty(View.java:15175)
	at android.view.View.draw(View.java:15954)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
	at android.view.View.draw(View.java:16187)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
	at android.view.View.updateDisplayListIfDirty(View.java:15180)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2623)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2442)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2075)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5422)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

这是我的部分代码：
public void onSurfaceTextureAvailable(SurfaceTexture surfaceTexture, int width, int height）{
 
        surface = new Surface(surfaceTexture);

        init();

        if (ijkMediaPlayer != null) {
            ijkMediaPlayer.setSurface(surface);
            ijkMediaPlayer.prepareAsync();

        }
}

public boolean onSurfaceTextureDestroyed(SurfaceTexture surface) {

        this.surface=null;

        if(ijkMediaPlayer!=null) {
            ijkMediaPlayer.setSurface(null);
            ijkMediaPlayer.pause();
            ijkMediaPlayer.stop();
            ijkMediaPlayer.release();
            ijkMediaPlayer=null;
        }

        return false;
}

private void init(){

       ijkMediaPlayer=new IjkMediaPlayer();

       ijkMediaPlayer.setLooping(true);

       ijkMediaPlayer.setDataSource(context, Uri.fromFile(file));

       ijkMediaPlayer.setOnPreparedListener(new IMediaPlayer.OnPreparedListener() {
            @Override
            public void onPrepared(IMediaPlayer iMediaPlayer) {
                ijkMediaPlayer.start();
                LogUtil.v(TAG,"ijkPlayer  started!");
            }
        });
}

public void start(){
      textureView=ViewFactory.getInstance().creViewFromOtherLayout();

      textureView.setSurfaceTextureListener(this);

}

public void stop() {

     if(ijkMediaPlayer!=null) {
            
            this.surface=null;
            ijkMediaPlayer.setSurface(null);
            ijkMediaPlayer.pause();
            ijkMediaPlayer.stop();
            ijkMediaPlayer.release();
        }

     ViewFactory.getInstance().removeView(textureView);

}

**Comment by ThisZhu** [comment]
补充下，我是开启了硬解的，运行的设备也是支持的

**Comment by zengyunpeng** [comment]
setLooping(true)能循环播放视频吗?我这不生效,只播放一次
