### ISSUE TITLE
arm64-v8a android端播放视频崩溃

### ISSUE THREAD

**Issue by heylee-svg** [bilibili/ijkplayer#4860]
java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer._setExternalRenderer(long) (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1setExternalRenderer and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1setExternalRenderer__J)
09-16 14:51:09.867 22722 22722 E AndroidRuntime: 	at tv.danmaku.ijk.media.player.IjkMediaPlayer._setExternalRenderer(Native Method)
09-16 14:51:09.867 22722 22722 E AndroidRuntime: 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.setExternalRenderer(IjkMediaPlayer.java:323)

**Comment by befovy** [comment]
`_setExternalRenderer` 这个应该在 bilibili/ijkplayer 中是没有的把，你是用了其他的 fork 版本？ @heylee-svg

**Comment by heylee-svg** [comment]
有 就是 IJKPlayer能调出来的方法

**Comment by befovy** [comment]
https://github.com/bilibili/ijkplayer 真没有这个。
在 https://github.com/lupengyun/YunIjkPlayer 中找到 _setExternalRenderer 方法。
