### ISSUE TITLE
Black screen when view multiple live streaming on Android

### ISSUE THREAD

**Issue by ProFive** [bilibili/ijkplayer#5156]
Dear all, 
Please me, I have a problem that can not display live streaming (some time is a black screen) when run on Android (it's not happening on iOS.)

 I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
 W/System.err: java.lang.IllegalStateException
 W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
 W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2632)

![531b304b7c2f8d71d43e](https://user-images.githubusercontent.com/5170616/99629408-861ed680-2a6a-11eb-95e9-61b63a63217f.jpg)

**Comment by b055man** [comment]
Have you made any progress in terms of this issue? I'm observing it as well.

**Comment by ProFive** [comment]
> Have you made any progress in terms of this issue? I'm observing it as well.

Not yet, sometimes still black screen I found the textureId is -1 after create again but doesn't update view.
