### ISSUE TITLE
从ijkplayer切换exoplayer，报解码器初始化错误

### ISSUE THREAD

**Issue by huagengithub** [Bilibili/ijkplayer#5309]
I have a play list witch contains some mp4 and mkv videos, I play mp4 with exoplayer and mkv with ijkplayer.
When change from ijkplayer to exoplayer, app crashes.

Error log:

I/OMXClient: IOmx service obtained
I/WebServer: Path=/storage/emulated/0/Android/data/dhq.CameraFTPRemoteViewer/files/FileCache/52335493/342236307/2021_7/30/1627620900000_Alarm_motion_2021-07-30_20-55-00.mp4/Alarm_motion_2021-07-30_20-55-00.mp4.cache
    Range=bytes=48-
I/ACodec: [OMX.google.aac.decoder] Now Loaded
E/Content-Range: bytes 48-536626/536627
I/ACodec: [HW_HDR] app-pid : 9803
I/ACodec: codec does not support config priority (err -2147483648)
I/ACodec: [OMX.google.aac.decoder] Now Loaded->Idle
I/WebServer: read:::now = :65536
I/WebServer: read:::now = :65536
I/WebServer: read:::now = :65536
I/WebServer: read:::now = :65536
I/WebServer: read:::now = :65536
I/WebServer: read:::now = :65536
I/WebServer: read:::now = :65536
I/WebServer: read:::now = :65536
I/WebServer: read:::now = :12291
I/ACodec: [OMX.google.aac.decoder] Now Idle->Executing
I/ACodec: [OMX.google.aac.decoder] Now Executing
I/ACodec: [OMX.google.aac.decoder] Now handling output port settings change
I/ACodec: [OMX.google.aac.decoder] Now Executing
I/ACodec:  [] Now uninitialized
I/ACodec: [] onAllocateComponent
I/OMXClient: IOmx service obtained
I/ACodec: [OMX.qcom.video.decoder.avc] Now Loaded
D/SurfaceUtils: connecting to surface 0x7050a8a010, reason connectToSurface
E/SurfaceUtils: Failed to connect to surface 0x7050a8a010, err -22
E/MediaCodec: nativeWindowConnect returned an error: Invalid argument (-22)
E/MediaCodec: configure failed with err 0xffffffea, resetting...
I/ACodec:  [OMX.qcom.video.decoder.avc] Now uninitialized
     [] Now kWhatShutdownCompleted event : 8522
I/MediaCodec: Codec shutdown complete
I/ACodec:  [] Now uninitialized
I/ACodec: [] onAllocateComponent
I/OMXClient: IOmx service obtained
W/System: A resource failed to call release. 
W/System: A resource failed to call close. 
W/System: A resource failed to call close. 
I/ACodec: [OMX.qcom.video.decoder.avc] Now Loaded
I/ACodec:  [OMX.qcom.video.decoder.avc] Now uninitialized
     [] Now kWhatShutdownCompleted event : 8522
I/MediaCodec: Codec shutdown complete
W/MediaCodecRenderer: Failed to initialize decoder: OMX.qcom.video.decoder.avc
    java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1960)
        at android.media.MediaCodec.configure(MediaCodec.java:1889)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [320, 240, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [320, 240, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1960)
        at android.media.MediaCodec.configure(MediaCodec.java:1889)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
I/ACodec: [OMX.google.aac.decoder] Now Executing->Idle
I/ACodec: [OMX.google.aac.decoder] Now Idle->Loaded
I/ACodec: [OMX.google.aac.decoder] Now Loaded
     [OMX.google.aac.decoder] Now kWhatShutdownCompleted event : 8522
I/ACodec:  [OMX.google.aac.decoder] Now uninitialized
     [] Now kWhatShutdownCompleted event : 8522
I/MediaCodec: Codec shutdown complete
D/IjkVideoView: Error: 1,1

**Comment by huagengithub** [comment]
**I solved this issue by recreate the player completely.**
