### ISSUE TITLE
android 电信米4 home ijkplayer 硬解销毁重新创建

### ISSUE THREAD

**Issue by changjiashuai** [Bilibili/ijkplayer#541]
```
按home键 log：
10-13 11:24:33.442 8118-10042/com.insta360.explore W/System.err: java.lang.IllegalStateException
10-13 11:24:33.442 8118-10042/com.insta360.explore W/System.err:     at android.media.MediaCodec.releaseOutputBuffer(Native Method)
10-13 11:24:33.442 8118-10042/com.insta360.explore W/System.err:     at dalvik.system.NativeStart.run(Native Method)
10-13 11:24:33.442 8118-10042/com.insta360.explore E/IJKMEDIA: SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer
10-13 11:24:33.462 8118-8118/com.insta360.explore I/TAG: onInfo(): [702,0]
10-13 11:24:33.512 8118-10042/com.insta360.explore W/System.err: java.lang.IllegalStateException
10-13 11:24:33.512 8118-10042/com.insta360.explore W/System.err:     at android.media.MediaCodec.releaseOutputBuffer(Native Method)
10-13 11:24:33.512 8118-10042/com.insta360.explore W/System.err:     at dalvik.system.NativeStart.run(Native Method)
10-13 11:24:33.512 8118-10042/com.insta360.explore E/IJKMEDIA: SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer
10-13 11:24:33.752 8118-8118/com.insta360.explore I/TAG: onPuase isPlaying=false
10-13 11:24:34.252 8118-8118/com.insta360.explore W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection

----
点app图标重新回来log：
10-13 11:25:41.382 8118-8118/com.insta360.explore I/TAG: onResume()
10-13 11:25:41.472 8118-10042/com.insta360.explore W/System.err: java.lang.IllegalStateException
10-13 11:25:41.472 8118-10042/com.insta360.explore W/System.err:     at android.media.MediaCodec.releaseOutputBuffer(Native Method)
10-13 11:25:41.472 8118-10042/com.insta360.explore W/System.err:     at dalvik.system.NativeStart.run(Native Method)
10-13 11:25:41.472 8118-10042/com.insta360.explore E/IJKMEDIA: SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer
10-13 11:25:41.472 8118-10042/com.insta360.explore E/IJKMEDIA: SDL_VoutOverlayAMediaCodec_releaseFrame: SDL_AMediaCodec_releaseOutputBuffer: failed (-10000)
10-13 11:25:41.482 8118-10042/com.insta360.explore W/System.err: java.lang.IllegalStateException
10-13 11:25:41.482 8118-10042/com.insta360.explore W/System.err:     at android.media.MediaCodec.releaseOutputBuffer(Native Method)
10-13 11:25:41.482 8118-10042/com.insta360.explore W/System.err:     at dalvik.system.NativeStart.run(Native Method)
10-13 11:25:41.482 8118-10042/com.insta360.explore E/IJKMEDIA: SDL_AMediaCodecJava_releaseOutputBuffer: releaseOutputBuffer
10-13 11:25:41.482 8118-10042/com.insta360.explore E/IJKMEDIA: SDL_VoutOverlayAMediaCodec_releaseFrame: SDL_AMediaCodec_releaseOutputBuffer: failed (-10000)
10-13 11:25:41.492 8118-10096/com.insta360.explore I/IJKMEDIA: quirk: reconfigure with new codec
10-13 11:25:41.492 8118-10096/com.insta360.explore I/IJKMEDIA: SDL_AMediaCodecJava_delete
10-13 11:25:41.492 252-1233/? E/: Destroy C2D instance
10-13 11:25:41.492 252-1233/? E/: Destroy C2D instance
10-13 11:25:41.502 8118-11304/com.insta360.explore I/OMXClient: Using client-side OMX mux.
10-13 11:25:41.592 8118-10096/com.insta360.explore E/IJKMEDIA: configure 0x1d30050e 0x1d200502
10-13 11:25:41.592 8118-11304/com.insta360.explore I/ACodec: DRC Mode: Dynamic Buffer Mode
10-13 11:25:41.622 8118-10030/com.insta360.explore I/TAG: onRenderSurfaceSizeChanged() playing=true
10-13 11:25:41.642 8118-8118/com.insta360.explore I/TAG: onWindowFocusChanged() hasFocus=true
10-13 11:25:41.642 8118-8118/com.insta360.explore I/TAG: onWindowFocusChanged() isBind=true
10-13 11:25:43.642 8118-10096/com.insta360.explore I/IJKMEDIA: quirk: reconfigure with new codec
10-13 11:25:43.642 8118-10096/com.insta360.explore I/IJKMEDIA: SDL_AMediaCodecJava_delete
10-13 11:25:43.642 252-20715/? E/: Destroy C2D instance
10-13 11:25:43.642 252-20715/? E/: Destroy C2D instance
10-13 11:25:43.652 8118-11352/com.insta360.explore I/OMXClient: Using client-side OMX mux.
10-13 11:25:43.732 8118-10096/com.insta360.explore E/IJKMEDIA: configure 0x22c00522 0x1d200502
10-13 11:25:43.742 8118-11352/com.insta360.explore I/ACodec: DRC Mode: Dynamic Buffer Mode
10-13 11:25:44.852 8118-10095/com.insta360.explore I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: INFO_OUTPUT_FORMAT_CHANGED
10-13 11:25:44.852 8118-10095/com.insta360.explore I/IJKMEDIA: AMEDIACODEC__INFO_OUTPUT_FORMAT_CHANGED
10-13 11:25:44.852 8118-10095/com.insta360.explore I/IJKMEDIA: AMEDIACODEC__INFO_OUTPUT_FORMAT_CHANGED
10-13 11:25:44.852 8118-10095/com.insta360.explore I/IJKMEDIA:     width-height: (2880 x 1440)
10-13 11:25:44.852 8118-10095/com.insta360.explore I/IJKMEDIA:     color-format: (QCOM_FORMATYUV420PackedSemiPlanar32m: 0x7fa30c04)
10-13 11:25:44.852 8118-10095/com.insta360.explore I/IJKMEDIA:     stride:       (2944)
10-13 11:25:44.852 8118-10095/com.insta360.explore I/IJKMEDIA:     slice-height: (1440)
10-13 11:25:44.852 8118-10095/com.insta360.explore I/IJKMEDIA:     crop:         (0, 0, 2879, 1439)
10-13 11:25:47.402 8118-8118/com.insta360.explore W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection

从log看codec 被销毁又重新创建的，现在我想实现的效果是，按home退出，点击图标重新后来继续播放，有什么方法可以设置不用销毁吗？@bbcallen

**Comment by Android4MediaPlayer** [comment]
因为surfaceView销毁了 这个需要重新配置surface，你可以尝试添加 欢迎patch

**Comment by bbcallen** [comment]
Possibly fixed
