### ISSUE TITLE
ijkmp_prepare_async()=-3 错误怎么解决?

### ISSUE THREAD

**Issue by Knightwood** [Bilibili/ijkplayer#5469]
我用了https://github.com/lm3515/TvBao库里的ijkplayer, 它用的是https://github.com/lm3515/RLIJKPlayer 提供的so文件. 我不会修改编译ijkplayer, 所以就用了这个老旧的库去播放视频和支持rtsp流的录制,

播放rtsp流的时候, 如果连接不上失败,会报错, 但是,再次重新播放时,会报另一个错误

连接不上的报错：
D/IJKMEDIA: IjkMediaPlayer_prepareAsync
D/IJKMEDIA: ijkmp_prepare_async()
W/IJKMEDIA: remove 'timeout' option for rtmp.
I/IJKMEDIA: ===== versions =====
I/IJKMEDIA: ijkplayer    : k0.7.6-3-g3cf3fd4
I/IJKMEDIA: FFmpeg       : ff3.2--ijk0.7.5--20161205--001
I/IJKMEDIA: libavutil    : 55.34.100
I/IJKMEDIA: libavcodec   : 57.64.100
I/IJKMEDIA: libavformat  : 57.56.100
I/IJKMEDIA: libswscale   : 4.2.100
I/IJKMEDIA: libswresample: 2.3.100
I/IJKMEDIA: ===== options =====
I/IJKMEDIA: player-opts : max_cached_duration          = 3000
I/IJKMEDIA: player-opts : infbuf                       = 1
I/IJKMEDIA: player-opts : packet-buffering             = 0
I/IJKMEDIA: format-opts : ijkapplication               = 488717937312
I/IJKMEDIA: format-opts : probesize                    = 16384
I/IJKMEDIA: format-opts : analyzeduration              = 50000
I/IJKMEDIA: codec-opts  : skip_loop_filter             = 0
I/IJKMEDIA: codec-opts  : skip_frame                   = 0
I/IJKMEDIA: ===================
I/IJKMEDIA: SDL_RunThread: [7890] ff_msg_loop
D/IJKMEDIA: message_loop
D/IJKMEDIA: ijkmp_prepare_async()=0
D/IJKMEDIA: FFP_MSG_FLUSH:
I/IJKMEDIA: SDL_RunThread: [7892] ff_read
W/IJKMEDIA: remove 'timeout' option for rtmp.
I/IJKMEDIA: SDL_RunThread: [7891] ff_vout
E/IJKMEDIA: Connection to tcp://192.168.6.19:1935?timeout=0 failed: Connection refused
E/IJKMEDIA: rtsp://192.168.6.19:1935: Connection refused
D/IJKMEDIA: FFP_MSG_ERROR: 0
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [7892]
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
D/NiceVideoPlayer: onError ——> STATE_ERROR ———— what：-10000, extra: 0

上面连接失败后, 调用reset()重置, 再次调用prepareAsync()试图重新播放
这次的报错:

D/IJKMEDIA: IjkMediaPlayer_prepareAsync
D/IJKMEDIA: ijkmp_prepare_async()
D/IJKMEDIA: ijkmp_prepare_async()=-3
W/System.err: java.lang.IllegalStateException
W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer._prepareAsync(Native Method)
W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.prepareAsync(IjkMediaPlayer.java:494)

这是怎么回事, 我该怎么解决?

**Comment by Knightwood** [comment]
在setDataSources之前应该reset，但是我的流程里reset放在了setDataSources之后。
