### ISSUE TITLE
W/System.err:     at com.insta360.explore.IjkMediaPlayerVideoActivity.onDestroy()

### ISSUE THREAD

**Issue by changjiashuai** [Bilibili/ijkplayer#550]
```@Override
    protected void onDestroy() {
        super.onDestroy();
        if (DEBUG) {
            Log.i(TAG, "onDestroy()");
        }
        if (mIjkMediaPlayer != null) {
            mIjkMediaPlayer.release();
            mIjkMediaPlayer = null;
    }
```

每次退出Activity 调用onDestroy() 都会打印
```
10-14 14:37:10.295 3311-3311/com.insta360.explore W/System.err:     at com.insta360.explore.IjkMediaPlayerVideoActivity.onDestroy(IjkMediaPlayerVideoActivity.java:908)
10-14 14:37:10.315 3311-3311/com.insta360.explore W/System.err:     at com.insta360.explore.IjkMediaPlayerVideoActivity.onDestroy(IjkMediaPlayerVideoActivity.java:908)

是我调用状态不对？

**Comment by Android4MediaPlayer** [comment]
908行是什么代码

**Comment by changjiashuai** [comment]
```
mIjkMediaPlayer.release();
