### ISSUE TITLE
Crashed on tag:k0.4.3.12 

### ISSUE THREAD

**Issue by jpxiong** [Bilibili/ijkplayer#679]
The new version will cause the crash as the following logs.

```
11-24 15:33:17.506 D/IJKMEDIA(28883): ffpipeline_create_from_android()
11-24 15:33:17.506 D/IJKMEDIA(28883): jni_set_media_player 000 mp=0x77f1ef48
11-24 15:33:17.506 W/dalvikvm(28883): JNI WARNING: instance jfieldID 0x0 not valid for class Ltv/danmaku/ijk/media/player/IjkMediaPlayer; (GetLongField)
11-24 15:33:17.506 W/dalvikvm(28883):              in Ltv/danmaku/ijk/media/player/IjkMediaPlayer;.native_setup:(Ljava/lang/Object;)V (GetLongField)
11-24 15:33:17.506 I/dalvikvm(28883): "main" prio=5 tid=1 RUNNABLE
11-24 15:33:17.506 I/dalvikvm(28883):   | group="main" sCount=0 dsCount=0 obj=0x41e76ca8 self=0x41e654b0
11-24 15:33:17.506 I/dalvikvm(28883):   | sysTid=28883 nice=0 sched=0/0 cgrp=apps handle=1073901908
11-24 15:33:17.506 I/dalvikvm(28883):   | state=R schedstat=( 0 0 0 ) utm=28 stm=17 core=4
11-24 15:33:17.506 I/dalvikvm(28883):   at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_setup(Native Method)
11-24 15:33:17.506 I/dalvikvm(28883):   at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:212)
11-24 15:33:17.506 I/dalvikvm(28883):   at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:192)
```

The reason is `JJK_loadClass__JJKC_IjkMediaPlayer(JNIEnv* )` doesn't be invoked properly.

It works fine after i invoke the `JJK_loadClass__JJKC_IjkMediaPlayer(env);` in `JNI_OnLoad`.

```
JNIEXPORT jint JNI_OnLoad(JavaVM *vm, void *reserved)
{
    JNIEnv* env = NULL;

    g_jvm = vm;
    if ((*vm)->GetEnv(vm, (void**) &env, JNI_VERSION_1_4) != JNI_OK) {
        return -1;
    }
    assert(env != NULL);

    pthread_mutex_init(&g_clazz.mutex, NULL );

    // FindClass returns LocalReference
    IJK_FIND_JAVA_CLASS(env, g_clazz.clazz, JNI_CLASS_IJKPLAYER);
    (*env)->RegisterNatives(env, g_clazz.clazz, g_methods, NELEM(g_methods) );

    JJK_loadClass__JJKC_IjkMediaPlayer(env);   // here !!!!!!!!!!!!!!!!!!!!!!!!!!!
    ijkmp_global_init();
    ijkmp_global_set_inject_callback(inject_callback);

    FFmpegApi_global_init(env);

    return JNI_VERSION_1_4;
}
```

Is there anything I missed ?

**Comment by bbcallen** [comment]
https://github.com/Bilibili/ijkplayer/blob/f0973541d61dfe10f5c5fe9275d1c39168eee081/ijkmedia/ijksdl/android/jjk/internal/jjk_allclasses.c

It is called here.
I intended to make this file auto generated.

**Comment by jpxiong** [comment]
That's strange. There isn't the `jjk_allclasses.c` file  on tag `k0.4.3.12`.

**Comment by jpxiong** [comment]
Got it! Thanks.
