### ISSUE TITLE
在魅蓝手机上关闭视频时崩溃报错

### ISSUE THREAD

**Issue by xiaojianan** [Bilibili/ijkplayer#907]
错误如下
E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
                                                                      Process: , PID: 28487
                                                                      java.util.concurrent.TimeoutException: tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize() timed out after 10 seconds
                                                                          at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                                          at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:811)
                                                                          at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
                                                                          at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
                                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by rogan528** [comment]
解决了吗？怎么解决的？
