### ISSUE TITLE
播放hevc时只有声音没图像

### ISSUE THREAD

**Issue by Long888** [Bilibili/ijkplayer#923]
我在调用mediacodec测试播放hevc视频时，有些视频就解不出图像，但是用java写个小程序调用mediacodec可以解出来。
LOG:
02-14 17:00:18.962: I/IJKMEDIA(26630): max_frame_duration: 10.000
02-14 17:00:18.962: I/IJKMEDIA(26630): Input #0, mpegts, from 'http://127.0.0.1:9104':
02-14 17:00:18.962: I/IJKMEDIA(26630):   Duration: 
02-14 17:00:18.962: I/IJKMEDIA(26630): N/A
02-14 17:00:18.962: I/IJKMEDIA(26630): , start: 
02-14 17:00:18.962: I/IJKMEDIA(26630): 69173.891011
02-14 17:00:18.962: I/IJKMEDIA(26630): , bitrate: 
02-14 17:00:18.962: I/IJKMEDIA(26630): N/A
02-14 17:00:18.962: I/IJKMEDIA(26630):   Program 1 
02-14 17:00:18.962: I/IJKMEDIA(26630):     Metadata:
02-14 17:00:18.962: I/IJKMEDIA(26630):       service_name    : 
02-14 17:00:18.962: I/IJKMEDIA(26630): Service01
02-14 17:00:18.962: I/IJKMEDIA(26630):       service_provider: 
02-14 17:00:18.962: I/IJKMEDIA(26630): FFmpeg
02-14 17:00:18.962: I/IJKMEDIA(26630):     Stream #0:0
02-14 17:00:18.962: I/IJKMEDIA(26630): [0x100]
02-14 17:00:18.962: I/IJKMEDIA(26630): : Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv), 960x540
02-14 17:00:18.962: I/IJKMEDIA(26630): , 
02-14 17:00:18.962: I/IJKMEDIA(26630): 60 tbr, 
02-14 17:00:18.962: I/IJKMEDIA(26630): 90k tbn, 
02-14 17:00:18.962: I/IJKMEDIA(26630): 90k tbc
02-14 17:00:18.962: I/IJKMEDIA(26630):     Stream #0:1
02-14 17:00:18.962: I/IJKMEDIA(26630): [0x101]
02-14 17:00:18.962: I/IJKMEDIA(26630): : Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 73 kb/s
02-14 17:00:18.972: I/IJKMEDIA(26630): SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
02-14 17:00:18.972: I/IJKMEDIA(26630): SDL_Android_AudioTrack: ENCODING_PCM_16BIT
02-14 17:00:18.982: I/IJKMEDIA(26630): SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(1.000000,0.000000)
02-14 17:00:18.982: I/IJKMEDIA(26630): audio_session_id = 443
02-14 17:00:18.982: I/IJKMEDIA(26630): AudioCodec: avcodec, aac
02-14 17:00:18.982: I/IJKMEDIA(26630): SDL_RunThread: [26766] ff_aout_android
02-14 17:00:18.982: D/IJKMEDIA(26630): ffpipenode_create_video_decoder_from_android_mediacodec()
02-14 17:00:18.982: I/IJKMEDIA(26630): API-Level: 19
02-14 17:00:18.982: I/IJKMEDIA(26630): ffpipenode_create_video_decoder_from_android_mediacodec: ffp->mediacodec_hevc=0
02-14 17:00:18.982: I/IJKMEDIA(26630): ffpipenode_create_video_decoder_from_android_mediacodec: ffp->mediacodec_all_videos=0
02-14 17:00:18.982: I/IJKMEDIA(26630): ffpipenode_create_video_decoder_from_android_mediacodec: MediaCodec: HEVC: enabled
02-14 17:00:18.982: I/IJKMEDIA(26630): AMediaFormat: video/hevc, 960x540
02-14 17:00:18.982: D/IJKMEDIA(26630): SDL_AMediaFormatJava_createVideoFormat
02-14 17:00:18.982: E/IJKMEDIA(26630): csd-0: naked
02-14 17:00:18.982: I/IJKMEDIA(26630): amc: rotate notify: 0
02-14 17:00:18.982: D/IJKMEDIA(26630): FFP_MSG_VIDEO_ROTATION_CHANGED: 0
02-14 17:00:18.982: D/IJKMEDIA(26630): ffpipeline_select_mediacodec_l
02-14 17:00:18.982: D/IjkVideoView(26630): MEDIA_INFO_VIDEO_ROTATION_CHANGED: 0
02-14 17:00:18.982: E/(26630): SurfaceView doesn't support rotation (0)!
02-14 17:00:18.982: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630): onSelectCodec: mime=video/hevc, profile=1, level=90
02-14 17:00:18.982: I/MediaCodecList(26630): register mediacode *****************
02-14 17:00:18.992: I/IJKMEDIA(26630): SDL_RunThread: [26767] ff_audio_dec
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.rk.video_decoder.avc
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/avc
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.rk.video_decoder.m2v
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/mpeg2
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.vp8.decoder
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.vp8
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.vp9.decoder
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.vp9
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.rk.video_decoder.h263
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/3gpp
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.rk.video_decoder.m4v
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/mp4v-es
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.rk.video_decoder.rv
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/vnd.rn-realvideo
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.rk.video_decoder.flv1
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/flv
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.rk.video_decoder.vp6
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/vp6
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.rk.video_decoder.vc1
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/vc1
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.rk.video_decoder.wmv3
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-ms-wmv
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.rk.video_decoder.mjpeg
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/mjpeg
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.rk.video_decoder.hevc
02-14 17:00:18.992: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/hevc
02-14 17:00:18.992: I/OMXClient(26630): Using client-side OMX mux.
02-14 17:00:19.002: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630): candidate codec: OMX.rk.video_decoder.hevc rank=700
02-14 17:00:19.002: I/OMXClient(26630): Using client-side OMX mux.
02-14 17:00:19.002: I/IjkMediaCodecInfo(26630):  Unknown Profile Level 0 (0,0)
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.amrnb.decoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/3gpp
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.amrwb.decoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/amr-wb
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.aac.decoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/mp4a-latm
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.g711.alaw.decoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/g711-alaw
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.g711.mlaw.decoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/g711-mlaw
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.vorbis.decoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/vorbis
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.vp8.encoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.h263.encoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.mpeg4.encoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.amrnb.encoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.amrwb.encoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.aac.encoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.flac.encoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: AACEncoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.rk.video_encoder.avc
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkOn2Encoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.raw.decoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/raw
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: OMX.google.mp3.decoder
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/mpeg
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkAudioDecoder_DTS
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/vnd.dts.hd
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkAudioDecoder_WMA
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/x-ms-wma
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkAudioDecoder_WMAPRO
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/x-ms-wmapro
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkAudioDecoder_AC3
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/x-ms-ac3
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkAudioDecoder_RA
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/vnd.rn-realaudio
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkAudioDecoder_WAV
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/wav
02-14 17:00:19.002: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkAudioDecoder_AAC
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/mp4a-latm
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: FLACDecoder
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/flac
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: AACDecoder_MIRRORING
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: audio/mp4a-latm
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkOn2Decoder
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.unknow
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkOn2Decoder
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.unknow
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkOn2Decoder
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.unknow
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkOn2Decoder
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.unknow
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkOn2Decoder
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.unknow
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkOn2Decoder
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.unknow
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkOn2Decoder
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.unknow
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkOn2Decoder
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.unknow
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkOn2Decoder
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.unknow
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkOn2Decoder
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.unknow
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkOn2Decoder
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.unknow
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):   found codec: RkOn2Decoder
02-14 17:00:19.012: D/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630):     mime: video/x-vnd.on2.unknow
02-14 17:00:19.012: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(26630): selected codec: OMX.rk.video_decoder.hevc rank=700
02-14 17:00:19.012: D/IJKMEDIA(26630): SDL_AMediaCodecJava_createByCodecName
02-14 17:00:19.012: I/OMXClient(26630): Using client-side OMX mux.
02-14 17:00:19.012: D/IJKMEDIA(26630): SDL_AMediaCodecJava_init
02-14 17:00:19.012: D/IJKMEDIA(26630): SDL_AMediaCodec_increaseReference(): ref=1
02-14 17:00:19.012: D/IJKMEDIA(26630): SDL_AMediaCodecJava_configure_surface
02-14 17:00:19.012: E/IJKMEDIA(26630): configure acodec:0x1d2004c2 format:0x1d2004b2: surface:0x1d2004ba
02-14 17:00:19.012: E/ACodec(26630): [OMX.rk.video_decoder.hevc] storeMetaDataInBuffers failed w/ err -2147483648
02-14 17:00:19.022: D/IJKMEDIA(26630): SDL_AMediaCodecJava_start
02-14 17:00:19.052: I/IJKMEDIA(26630): reconfigure_codec_l:new acodec: 0x5fab9e08
02-14 17:00:19.052: D/IJKMEDIA(26630): SDL_AMediaCodec_increaseReference(): ref=2
02-14 17:00:19.052: I/IJKMEDIA(26630): VideoCodec: MediaCodec, OMX.rk.video_decoder.hevc
02-14 17:00:19.052: W/IJKMEDIA(26630): fps: 60.000000 (too high)
02-14 17:00:19.052: I/IJKMEDIA(26630): SDL_RunThread: [26783] ff_video_dec
02-14 17:00:19.052: D/IJKMEDIA(26630): FFP_MSG_VIDEO_SIZE_CHANGED: 960, 540
02-14 17:00:19.052: D/IJKMEDIA(26630): FFP_MSG_SAR_CHANGED: 0, 1
02-14 17:00:19.052: I/IJKMEDIA(26630): SDL_RunThread: [26784] amediacodec_input_thread
02-14 17:00:19.052: D/IJKMEDIA(26630): ijkmp_get_msg: FFP_MSG_PREPARED
02-14 17:00:19.052: D/IJKMEDIA(26630): FFP_MSG_PREPARED:
02-14 17:00:19.072: D/IJKMEDIA(26630): IjkMediaPlayer_start
02-14 17:00:19.072: D/IJKMEDIA(26630): ijkmp_start()
02-14 17:00:19.072: D/IJKMEDIA(26630): ijkmp_start()=0
02-14 17:00:19.072: D/IJKMEDIA(26630): ijkmp_get_msg: FFP_REQ_START
02-14 17:00:19.072: D/IJKMEDIA(26630): IjkMediaPlayer_start
02-14 17:00:19.072: D/IJKMEDIA(26630): ijkmp_start()
02-14 17:00:19.072: D/IJKMEDIA(26630): ijkmp_start()=0
02-14 17:00:19.072: D/IJKMEDIA(26630): ijkmp_get_msg: FFP_REQ_START
02-14 17:00:19.152: D/IJKMEDIA(26630): ijkmp_get_msg: FFP_REQ_START
02-14 17:00:19.152: D/IJKMEDIA(26630): ffpipeline_set_surface_need_reconfigure_l(0)
02-14 17:00:19.152: I/IJKMEDIA(26630): feed_input_buffer: same surface, reuse previous surface
02-14 17:00:19.162: D/IJKMEDIA(26630): avcodec/Audio: first frame decoded
02-14 17:00:19.162: D/IJKMEDIA(26630): FFP_MSG_AUDIO_RENDERING_START:
02-14 17:00:19.162: D/IjkVideoView(26630): MEDIA_INFO_AUDIO_RENDERING_START:
02-14 17:00:19.172: E/ACodec(26630): [OMX.rk.video_decoder.hevc] ERROR(0x00000001)
02-14 17:00:19.182: E/ACodec(26630): [OMX.rk.video_decoder.hevc] ERROR(0x00000001)
02-14 17:00:19.182: E/MediaCodec(26630): Codec reported an error. (omx error 0x00000001, internalError -2147483648)
02-14 17:00:19.182: E/ACodec(26630): [OMX.rk.video_decoder.hevc] ERROR(0x00000001)
02-14 17:00:19.182: E/MediaCodec(26630): Codec reported an error. (omx error 0x00000001, internalError -2147483648)
02-14 17:00:19.182: E/MediaCodec(26630): Codec reported an error. (omx error 0x00000001, internalError -2147483648)
02-14 17:00:19.182: E/ACodec(26630): [OMX.rk.video_decoder.hevc] ERROR(0x00000001)
02-14 17:00:19.182: W/System.err(26630): java.lang.IllegalStateException
02-14 17:00:19.182: W/System.err(26630): 	at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
02-14 17:00:19.182: W/System.err(26630): 	at dalvik.system.NativeStart.run(Native Method)
02-14 17:00:19.182: I/IJKMEDIA(26630): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
02-14 17:00:19.182: E/MediaCodec(26630): Codec reported an error. (omx error 0x00000001, internalError -2147483648)
02-14 17:00:19.192: E/ACodec(26630): [OMX.rk.video_decoder.hevc] ERROR(0x00000001)
02-14 17:00:19.192: E/MediaCodec(26630): Codec reported an error. (omx error 0x00000001, internalError -2147483648)
02-14 17:00:19.192: W/System.err(26630): java.lang.IllegalStateException
02-14 17:00:19.192: W/System.err(26630): 	at android.media.MediaCodec.queueInputBuffer(Native Method)
02-14 17:00:19.192: E/ACodec(26630): [OMX.rk.video_decoder.hevc] ERROR(0x00000001)
02-14 17:00:19.192: W/System.err(26630): 	at dalvik.system.NativeStart.run(Native Method)
02-14 17:00:19.192: E/IJKMEDIA(26630): feed_input_buffer: SDL_AMediaCodec_getInputBuffer failed
02-14 17:00:19.192: E/MediaCodec(26630): Codec reported an error. (omx error 0x00000001, internalError -2147483648)
02-14 17:00:19.192: D/IJKMEDIA(26630): SDL_AMediaCodecJava_stop
02-14 17:00:19.192: I/IJKMEDIA(26630): MediaCodec: enqueue_thread_func: exit: -1
02-14 17:00:19.192: I/IJKMEDIA(26630): SDL_JNI_DetachThreadEnv: [26784]
02-14 17:00:19.192: E/ACodec(26630): [OMX.rk.video_decoder.hevc] ERROR(0x00000001)
02-14 17:00:19.192: E/MediaCodec(26630): Codec reported an error. (omx error 0x00000001, internalError -2147483648)
02-14 17:00:19.192: E/ACodec(26630): [OMX.rk.video_decoder.hevc] ERROR(0x00000001)
02-14 17:00:19.192: E/MediaCodec(26630): Codec reported an error. (omx error 0x00000001, internalError -2147483648)
02-14 17:00:19.242: D/IJKMEDIA(26630): SDL_AMediaCodec_decreaseReference(): ref=1
02-14 17:00:19.242: I/IJKMEDIA(26630): MediaCodec: func_run_sync: exit: -1
02-14 17:00:19.242: I/IJKMEDIA(26630): SDL_JNI_DetachThreadEnv: [26783]
02-14 17:00:19.992: D/dalvikvm(26630): GC_FOR_ALLOC freed 4613K, 58% free 5736K/13356K, paused 22ms, total 22ms
02-14 17:00:23.562: D/dalvikvm(26630): GC_FOR_ALLOC freed 2569K, 64% free 4859K/13356K, paused 24ms, total 24ms
02-14 17:00:23.602: D/dalvikvm(26630): GC_FOR_ALLOC freed 689K, 59% free 5523K/13356K, paused 21ms, total 21ms
02-14 17:00:23.662: D/IJKMEDIA(26630): IjkMediaPlayer_reset
02-14 17:00:23.662: D/IJKMEDIA(26630): IjkMediaPlayer_release
02-14 17:00:23.662: D/IJKMEDIA(26630): ijkmp_set_android_surface(surface=0x0)
02-14 17:00:23.662: D/IJKMEDIA(26630): ffpipeline_set_surface()
02-14 17:00:23.662: D/IJKMEDIA(26630): SDL_AMediaCodec_decreaseReference(): ref=0
02-14 17:00:23.662: I/IJKMEDIA(26630): SDL_AMediaCodecJava_delete
02-14 17:00:23.662: W/System.err(26630): java.lang.InterruptedException
02-14 17:00:23.662: W/System.err(26630): 	at java.lang.VMThread.sleep(Native Method)
02-14 17:00:23.662: W/System.err(26630): 	at java.lang.Thread.sleep(Thread.java:1013)
02-14 17:00:23.662: W/System.err(26630): 	at java.lang.Thread.sleep(Thread.java:995)
02-14 17:00:23.662: W/System.err(26630): 	at org.wel.newlive.task.NumberChangeChannelTask.run(NumberChangeChannelTask.java:42)
02-14 17:00:23.662: D/IJKMEDIA(26630): ijkmp_set_android_surface(surface=0x0)=void
02-14 17:00:23.662: D/IJKMEDIA(26630): ijkmp_shutdown_l()
02-14 17:00:23.662: D/IJKMEDIA(26630): message_loop exit
02-14 17:00:23.662: I/IJKMEDIA(26630): SDL_JNI_DetachThreadEnv: [26727]
02-14 17:00:23.672: I/IJKMEDIA(26630): SDL_JNI_DetachThreadEnv: [26728]
02-14 17:00:23.752: I/IJKMEDIA(26630): SDL_JNI_DetachThreadEnv: [26729]

**Comment by Long888** [comment]
http://pan.baidu.com/s/1nuq5K17 用来测试的一段视频

**Comment by Android4MediaPlayer** [comment]
Unknown Profile Level 0 (0,0)，PLZ check HEVC encoder.

**Comment by Long888** [comment]
decoder is no problem ，What is the meaning of Unknown Profile Level 0 (0,0)

**Comment by bbcallen** [comment]
Sorry, I don't maintain MediaCodec with HEVC, I'm not familiar with it.

**Comment by yuazhen** [comment]
@Long888 Did you solved the problem?
