### ISSUE TITLE
android6.0(sdk version 23) 加载so库异常，无法播放

### ISSUE THREAD

**Issue by zyqing1** [Bilibili/ijkplayer#937]
使用android6.0（sdk version 为 23）的sdk编译，播放时加载so库时异常，报错如下
FATAL EXCEPTION: main
     Process: tv.danmaku.ijk.media.sample, PID: 26128
     java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/tv.danmaku.ijk.media.sample-1/lib/arm/libijkffmpeg.so: has text relocations
      at java.lang.Runtime.loadLibrary(Runtime.java:372)
      at java.lang.System.loadLibrary(System.java:1076)
      at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:109)

**Comment by zyqing1** [comment]
已经好了，我自己的问题，打扰了
